export const MASTER_ARTISTS = [
  { name: "Leonardo da Vinci", tooltip: "Italian Renaissance polymath. Pioneered sfumato and chiaroscuro. Painted the Mona Lisa and The Last Supper. Active: c. 1472–1519" },
  { name: "Rembrandt van Rijn", tooltip: "Dutch Golden Age master of chiaroscuro and psychological portraiture. Known for dramatic lighting and introspective self-portraits. Active: c. 1625–1669" },
  { name: "Vincent Willem van Gogh", tooltip: "Post-Impressionist known for bold, expressive brushwork, vibrant color, and emotional intensity. Created Starry Night and Sunflowers. Active: 1881–1890" },
  { name: "Pablo Picasso", tooltip: "Co-founder of Cubism. Reinvented his style through Blue, Rose, African-influenced, Cubist, and Neoclassical periods. Active: c. 1894–1973" },
  { name: "Michelangelo Buonarroti", tooltip: "High Renaissance sculptor and painter. Created the Sistine Chapel ceiling and David. Monumental, anatomically powerful figures. Active: c. 1490–1564" },
  { name: "Salvador Dalí", tooltip: "Surrealist known for dreamlike imagery, melting clocks, and the paranoiac-critical method. Active: c. 1920–1983" },
  { name: "Claude Monet", tooltip: "Founder of Impressionism. Painted en plein air, capturing light and atmosphere. Famous for the Water Lilies series. Active: c. 1860–1926" },
  { name: "Henri Matisse", tooltip: "Fauvist leader known for bold, non-naturalistic color, simplified forms, and decorative patterns. Active: c. 1895–1954" },
  { name: "Edvard Munch", tooltip: "Expressionist pioneer exploring anxiety, mortality, and raw emotion. Painted The Scream. Active: c. 1880–1944" },
  { name: "Gustav Klimt", tooltip: "Vienna Secession co-founder. Known for ornamental gold leaf, sensual figuration, and Byzantine-influenced patterning. Painted The Kiss. Active: c. 1880–1918" },
  { name: "Raphael", tooltip: "High Renaissance master of graceful composition, idealized beauty, and balanced form. Renowned for the School of Athens. Active: c. 1500–1520" },
  { name: "Pierre-Auguste Renoir", tooltip: "Impressionist known for luminous color, soft brushwork, and joyful Parisian scenes. Active: c. 1862–1919" },
  { name: "Johannes Vermeer", tooltip: "Dutch Golden Age master of intimate domestic interiors with subtle light and serene compositions. Only ~35 known works. Active: c. 1653–1675" },
  { name: "Andy Warhol", tooltip: "Pop Art icon. Elevated mass culture imagery through silkscreen printing, celebrity portraits, and Campbell's Soup cans. Active: c. 1952–1987" },
  { name: "Giotto di Bondone", tooltip: "Proto-Renaissance pioneer who introduced naturalistic space and human emotion into painting. Frescoed the Scrovegni Chapel. Active: c. 1290–1337" },
  { name: "Paul Cézanne", tooltip: "Post-Impressionist who bridged Impressionism and Cubism through geometric simplification and multiple viewpoints. Active: c. 1860–1906" },
  { name: "Jan van Eyck", tooltip: "Early Netherlandish master. Advanced oil painting technique with jewel-like detail and luminous glazes. Painted the Ghent Altarpiece. Active: c. 1422–1441" },
  { name: "Caravaggio", tooltip: "Baroque master of dramatic tenebrism. Stark, theatrical lighting and unflinching realism in religious scenes. Active: c. 1592–1610" },
  { name: "Édouard Manet", tooltip: "Precursor to Impressionism. Challenged academic conventions with modern subjects, flat color planes, and bold compositions. Active: c. 1856–1883" },
  { name: "Titian Ramsay Peale II", tooltip: "American naturalist-artist of the Peale dynasty. Known for natural history and scientific expedition illustration. Active: c. 1819–1885" },
  { name: "Piet Mondrian", tooltip: "De Stijl co-founder. Pioneered Neoplasticism with grid compositions using primary colors, black lines, and white planes. Active: c. 1900–1944" },
  { name: "Piero della Francesca", tooltip: "Early Italian Renaissance master of mathematical perspective, serene compositions, and crystalline color. Active: c. 1439–1492" },
  { name: "Paul Klee", tooltip: "Expressionist and Bauhaus teacher. Childlike, whimsical abstraction informed by color theory and musical structures. Active: c. 1898–1940" },
  { name: "Francis Bacon", tooltip: "Post-war British figurative painter. Distorted, anguished figures rendered with visceral brushwork and raw psychological intensity. Active: c. 1929–1992" },
  { name: "Mark Rothko", tooltip: "Abstract Expressionist / Color Field painter. Large luminous rectangles of color evoking emotional and spiritual depth. Active: c. 1936–1970" },
  { name: "Joan Miró", tooltip: "Surrealist known for biomorphic forms, vivid primary colors, and playful, childlike abstraction. Active: c. 1918–1983" },
  { name: "Gustave Courbet", tooltip: "Founder of Realism. Rejected Romanticism for unidealized depictions of rural labor and everyday life. Active: c. 1840–1877" },
  { name: "Hans Holbein the Younger", tooltip: "Northern Renaissance portraitist. Precise, detailed likenesses of Tudor court figures including Henry VIII. Active: c. 1515–1543" },
  { name: "Marc Chagall", tooltip: "Modernist blending Jewish folklore, dreamlike imagery, floating figures, and vibrant, lyrical color. Active: c. 1907–1985" },
  { name: "Nicolas Poussin", tooltip: "French Classical Baroque painter of mythological and historical subjects in idealized, structured landscapes. Active: c. 1624–1665" },
  { name: "William Blake", tooltip: "Romantic visionary. Created illuminated books combining poetry and art with mystical, prophetic imagery. Active: c. 1778–1827" },
  { name: "El Greco", tooltip: "Mannerist painter known for elongated figures, expressive color, and spiritual intensity. Born in Crete, worked in Spain. Active: c. 1560–1614" },
  { name: "Caspar David Friedrich", tooltip: "German Romantic landscapist. Solitary figures contemplating sublime, misty nature. Active: c. 1798–1840" },
  { name: "Winslow Homer", tooltip: "American Realist celebrated for dramatic seascapes, outdoor genre scenes, and powerful watercolor technique. Active: c. 1857–1910" },
  { name: "Marcel Duchamp", tooltip: "Dada and Conceptual art pioneer. Introduced readymades and challenged the definition of art itself. Active: c. 1902–1968" },
  { name: "Giorgione", tooltip: "Venetian Renaissance painter of atmospheric landscapes and poetic, enigmatic mood. Few authenticated works survive. Active: c. 1497–1510" },
  { name: "Frida Kahlo", tooltip: "Mexican artist known for autobiographical symbolism, vibrant folk art influence, and unflinching self-portraiture. Active: c. 1925–1954" },
  { name: "Fra Angelico", tooltip: "Early Italian Renaissance Dominican friar. Luminous, devotional frescoes and altarpieces with serene spiritual grace. Active: c. 1418–1455" },
  { name: "Georges Pierre Seurat", tooltip: "Neo-Impressionist who developed Pointillism, applying scientific color theory through precise dot arrangements. Active: c. 1879–1891" },
  { name: "Jean-Antoine Watteau", tooltip: "French Rococo master of fêtes galantes — elegant garden scenes imbued with theatrical grace and poetic melancholy. Active: c. 1702–1721" },
  { name: "Fernand Léger", tooltip: "Cubist painter of bold, tubular mechanical forms and primary colors, celebrating modern industrial life. Active: c. 1905–1955" },
  { name: "James Abbott McNeill Whistler", tooltip: "Aestheticist painter of tonal harmony and nocturnes. Championed 'art for art's sake.' Active: c. 1855–1903" },
  { name: "Max Ernst", tooltip: "Surrealist and Dada artist. Invented frottage and grattage techniques, creating dreamlike collage-based imagery. Active: c. 1910–1976" },
  { name: "Willem de Kooning", tooltip: "Abstract Expressionist known for aggressive, gestural brushwork and powerful figurative-abstract canvases. Active: c. 1927–1990" },
  { name: "Paolo Uccello", tooltip: "Early Italian Renaissance painter obsessed with perspective and foreshortening, bridging decorative Gothic and Renaissance naturalism. Active: c. 1425–1475" },
  { name: "Kazimir Malevich", tooltip: "Founder of Suprematism. Reduced painting to pure geometric abstraction; created the iconic Black Square. Active: c. 1904–1935" },
  { name: "Andrea Mantegna", tooltip: "Early Italian Renaissance master of archaeological precision, extreme foreshortening, and illusionistic perspective. Active: c. 1448–1506" },
  { name: "Jacopo Tintoretto", tooltip: "Venetian Mannerist known for dramatic compositions, dynamic movement, and theatrical lighting at monumental scale. Active: c. 1539–1594" },
  { name: "Jasper Johns", tooltip: "Neo-Dada / early Pop artist. Explored familiar symbols — flags, targets, numbers — using encaustic and assemblage. Active: from 1954" },
  { name: "Sandro Botticelli", tooltip: "Early Italian Renaissance master of graceful, linear mythological subjects. Painted The Birth of Venus and Primavera. Active: c. 1465–1510" },
  { name: "Umberto Boccioni", tooltip: "Italian Futurist painter and sculptor. Dynamic movement, simultaneity, and the explosive energy of modern speed. Active: c. 1902–1916" },
  { name: "Joachim Patenier", tooltip: "Early Netherlandish pioneer of landscape as an independent genre. Panoramic views with small biblical figures. Active: c. 1500–1524" },
  { name: "Duccio di Buoninsegna", tooltip: "Sienese School Proto-Renaissance painter. Transitioned from Byzantine formality toward emotional, humanistic narrative. Active: c. 1278–1319" },
  { name: "Rogier van der Weyden", tooltip: "Early Netherlandish painter of intense emotional expression, elegant compositions, and devotional drama. Active: c. 1427–1464" },
  { name: "John Constable", tooltip: "English Romantic landscapist. Naturalistic cloud studies and lush depictions of the Suffolk countryside. Active: c. 1802–1837" },
  { name: "Jacques-Louis David", tooltip: "Leading Neoclassical painter. Heroic historical subjects with moral clarity, influenced by Roman Republican ideals. Active: c. 1775–1825" },
  { name: "René Magritte", tooltip: "Belgian Surrealist. Visual paradoxes and philosophical wit using ordinary objects in logically impossible contexts. Active: c. 1926–1967" },
  { name: "Hieronymus Bosch", tooltip: "Northern Renaissance visionary. Fantastical, nightmarish imagery filled with moral allegory and symbolic creatures. Active: c. 1474–1516" },
  { name: "Pieter Bruegel the Elder", tooltip: "Northern Renaissance master of panoramic peasant scenes, proverbs, and allegorical landscapes. Active: c. 1551–1569" },
  { name: "Simone Martini", tooltip: "Gothic / Sienese School painter. Elegant line, rich gilded color, and courtly refinement in religious subjects. Active: c. 1315–1344" },
  { name: "Roy Lichtenstein", tooltip: "Pop Art painter. Appropriated comic strip imagery with Ben-Day dots, bold outlines, and bright primary colors. Active: c. 1957–1997" },
  { name: "Gustave Moreau", tooltip: "French Symbolist. Mythological subjects rendered with jewel-like detail and mystical, otherworldly atmosphere. Active: c. 1852–1898" },
  { name: "Giorgio de Chirico", tooltip: "Founder of Metaphysical painting. Eerie, empty cityscapes with dramatic shadows and philosophical mystery. Active: c. 1909–1978" },
  { name: "Edward Hopper", tooltip: "American Realist known for scenes of urban isolation, dramatic geometric light, and quiet psychological tension. Active: c. 1906–1965" },
  { name: "Lucio Fontana", tooltip: "Argentine-Italian founder of Spatialism. Slashed canvases exploring space and dimension beyond the picture plane. Active: c. 1930–1968" },
  { name: "Franz Marc", tooltip: "German Expressionist, co-founder of Der Blaue Reiter. Vibrant animal paintings with spiritual color symbolism. Active: c. 1900–1916" },
  { name: "William Hogarth", tooltip: "English painter and printmaker. Satirical moral narratives in sequential series. Pioneer of social commentary in art. Active: c. 1720–1764" },
  { name: "Georges Braque", tooltip: "Co-founder of Cubism with Picasso. Pioneer of papier collé, known for muted palette and still-life subjects. Active: c. 1905–1963" },
  { name: "Gerhard Richter", tooltip: "Contemporary German artist spanning photorealistic painting, color charts, and abstract squeegee works. Active: from 1962" },
  { name: "Georges de la Tour", tooltip: "French Baroque painter of candlelit nocturnal scenes with geometric simplification and quiet devotional mood. Active: c. 1616–1652" },
  { name: "Artemisia Gentileschi", tooltip: "Italian Baroque painter. Powerful female heroines, Caravaggesque drama, and emotional intensity. Active: c. 1610–1654" },
  { name: "Jean-François Millet", tooltip: "Barbizon School / Realist. Dignified depictions of peasant labor and rural life in warm, earthy tones. Active: c. 1840–1875" },
  { name: "Francisco de Zurbarán", tooltip: "Spanish Baroque painter of monastic subjects with stark chiaroscuro and sculptural, contemplative realism. Active: c. 1625–1664" },
  { name: "Cimabue", tooltip: "Late Byzantine / Proto-Renaissance. Monumental Madonnas marking the transition from Byzantine formality toward naturalism. Active: c. 1265–1302" },
  { name: "James Ensor", tooltip: "Belgian Expressionist / Symbolist. Grotesque carnival masks, macabre imagery, and biting social satire. Active: c. 1880–1949" },
  { name: "El Lissitzky", tooltip: "Russian Constructivist / Suprematist. Revolutionary graphic design, Proun spatial compositions, and typographic innovation. Active: c. 1917–1941" },
  { name: "Egon Schiele", tooltip: "Austrian Expressionist. Raw, contorted figuration with angular lines, erotic intensity, and psychological exposure. Active: c. 1907–1918" },
  { name: "Dante Gabriel Rossetti", tooltip: "Pre-Raphaelite Brotherhood co-founder. Medieval themes, sensual female beauty, and rich literary symbolism. Active: c. 1848–1882" },
  { name: "Amedeo Clemente Modigliani", tooltip: "School of Paris Expressionist. Distinctive elongated forms and stylized portraits influenced by African and Cycladic sculpture. Active: c. 1906–1920" }
];
