export const MASTER_ARTISTS = [
  "Leonardo da Vinci",
  "Rembrandt van Rijn",
  "vincent willem van gogh",
  "Pablo Picasso",
  "Michelangelo Buonarroti",
  "Salvador Dalí",
  "Claude Monet",
  "Henri Matisse",
  "Edvard Munch",
  "Gustav Klimt",
  "Raphael",
  "Pierre-Auguste Renoir",
  "Johannes Vermeer",
  "Andy Warhol",
  "Giotto di Bondone",
  "Paul Cézanne",
  "Jan van Eyck",
  "Caravaggio",
  "Édouard Manet",
  "Titian Ramsay Peale II",
  "Piet Mondrian",
  "Piero della Francesca",
  "Paul Klee",
  "Francis Bacon",
  "Mark Rothko",
  "Joan Miró",
  "Gustave Courbet",
  "Hans Holbein the Younger",
  "Marc Chagall",
  "Nicolas Poussin",
  "William Blake",
  "El Greco",
  "Caspar David Friedrich",
  "Winslow Homer",
  "Marcel Duchamp",
  "Giorgione",
  "Frida Kahlo",
  "Fra Angelico",
  "Georges Pierre Seurat",
  "Jean-Antoine Watteau",
  "Fernand Léger",
  "James Abbott McNeill Whistler",
  "Max Ernst",
  "Willem de Kooning",
  "Paolo Uccello",
  "Kazimir Malevich",
  "Andrea Mantegna",
  "Jacopo Tintoretto",
  "Jasper Johns",
  "Sandro Botticelli",
  "Umberto Boccioni",
  "Joachim Patenier",
  "Duccio di Buoninsegna",
  "Rogier van der Weyden",
  "John Constable",
  "Jacques-Louis David",
  "René Magritte",
  "Hieronymus Bosch",
  "Pieter Bruegel the Elder",
  "Simone Martini",
  "Roy Lichtenstein",
  "Gustave Moreau",
  "Giorgio de Chirico",
  "Edward Hopper",
  "Lucio Fontana",
  "Franz Marc",
  "William Hogarth",
  "Georges Braque",
  "Gerhard Richter",
  "Georges de la Tour",
  "Artemisia Gentileschi",
  "Jean-François Millet",
  "Francisco de Zurbarán",
  "Cimabue",
  "James Ensor",
  "El Lissitzky",
  "Egon Schiele",
  "Dante Gabriel Rossetti",
  "Amedeo Clemente Modigliani"
];
