export const GRAPHIC_DESIGNERS = [
  { name: "Reza Abedini", tooltip: "Iranian graphic designer blending Persian calligraphy with contemporary design. Known for cultural posters and typography. Active: from 1990s" },
  { name: "Otl Aicher", tooltip: "German designer who created the 1972 Munich Olympics visual identity and the Rotis typeface. Influential systems thinker. Active: c. 1948–1991" },
  { name: "Alan Aldridge", tooltip: "British illustrator and designer known for psychedelic Beatles imagery and The Butterfly Ball. Active: c. 1960s–2017" },
  { name: "John Alvin", tooltip: "American movie poster artist. Created iconic posters for E.T., Blade Runner, and The Lion King. Active: c. 1974–2008" },
  { name: "Gail Anderson", tooltip: "American designer known for expressive, hand-crafted typography. Long-time creative director at SpotCo and Rolling Stone. Active: from 1980s" },
  { name: "Jeff Arwadi", tooltip: "Indonesian graphic designer and musician known for extreme metal album art and underground visual culture. Active: from 1990s" },
  { name: "Roberto Baldazzini", tooltip: "Italian illustrator and comic artist known for sensual, pin-up style work and erotic graphic novels. Active: from 1980s" },
  { name: "Jan Balet", tooltip: "German-American illustrator and designer known for stylized folk-art figures and children's books. Active: c. 1940s–1990s" },
  { name: "Marian Bantjes", tooltip: "Canadian designer celebrated for intricate, ornamental typographic compositions and hand-drawn vector work. Active: from 2003" },
  { name: "Noma Bar", tooltip: "Israeli-British graphic designer known for minimalist negative-space illustrations conveying dual meaning. Active: from 2000s" },
  { name: "Jonathan Barnbrook", tooltip: "British typographer and designer. Created Virus Foundry typefaces. Known for politically charged, provocative design. Active: from 1990s" },
  { name: "Saul Bass", tooltip: "American master of title sequence design and corporate identity. Created iconic logos for AT&T, United Airlines, and Minolta. Active: c. 1946–1996" },
  { name: "Herbert Bayer", tooltip: "Austrian-American Bauhaus designer. Pioneered the universal typeface concept and integrated typography with photography. Active: c. 1921–1985" },
  { name: "Harry Beck", tooltip: "British engineering draftsman who designed the iconic London Underground map using a diagrammatic approach. Created: 1931" },
  { name: "John Bielenberg", tooltip: "American designer and design educator, founder of Project M. Known for community-driven design thinking. Active: from 1980s" },
  { name: "Michael Bierut", tooltip: "American designer and Pentagram partner known for clean, intelligent branding — including Hillary Clinton's 2016 'H' logo. Active: from 1980" },
  { name: "Giambattista Bodoni", tooltip: "Italian typographer who created the Bodoni typeface family. Known for extreme contrast between thick and thin strokes. Active: c. 1768–1813" },
  { name: "Irma Boom", tooltip: "Dutch book designer known for innovative, experimental book architecture. Youngest recipient of the Gutenberg Prize. Active: from 1985" },
  { name: "Sheila Levrant de Bretteville", tooltip: "American feminist designer and educator. Founded the first women's design program at CalArts (1971). Active: from 1968" },
  { name: "Alexey Brodovitch", tooltip: "Russian-American art director who transformed Harper's Bazaar with dynamic, cinematic page layouts. Active: c. 1930–1971" },
  { name: "Neville Brody", tooltip: "British typographer and art director. Defined 1980s magazine design with The Face. Co-founded FontShop. Active: from 1981" },
  { name: "Robert Brownjohn", tooltip: "American designer best known for the projected-body title sequences for the James Bond films From Russia with Love and Goldfinger. Active: c. 1957–1970" },
  { name: "Dick Bruna", tooltip: "Dutch illustrator and designer. Creator of Miffy (Nijntje). Distinctive flat color, thick outlines, and minimalist style. Active: c. 1953–2011" },
  { name: "Peter Buchanan-Smith", tooltip: "American designer and writer. Former art director of The New York Times Op-Ed page. Founded Best Made Company. Active: from 1990s" },
  { name: "Jon Burgerman", tooltip: "British-American artist known for colorful, playful doodle characters and interactive street art. Active: from 2001" },
  { name: "Margaret Calvert", tooltip: "South African-British designer who co-designed the UK's road signage system and the Transport typeface with Jock Kinneir. Active: from 1957" },
  { name: "Eric Carle", tooltip: "American children's book author and illustrator. Created The Very Hungry Caterpillar with distinctive collage technique. Active: c. 1967–2021" },
  { name: "Joe Caroff", tooltip: "American designer who created the iconic James Bond 007 gun logo and numerous Broadway show logos. Active: c. 1950s–2000s" },
  { name: "David Carson", tooltip: "American designer who pioneered grunge typography and deconstructed editorial layouts in Ray Gun magazine. Active: from 1989" },
  { name: "Jacqueline Casey", tooltip: "American designer at MIT. Known for Swiss-influenced, typographic posters that merged clarity with conceptual wit. Active: c. 1955–1989" },
  { name: "William Caslon", tooltip: "English typefounder who created the Caslon typeface, a standard for English-language printing for over two centuries. Active: c. 1720–1766" },
  { name: "Urso Chappell", tooltip: "American World's Fair enthusiast and graphic designer known for documenting and designing expo-related materials. Active: from 1980s" },
  { name: "Elaine Lustig Cohen", tooltip: "American designer who continued her husband Alvin Lustig's studio. Created iconic modernist book covers for Meridian and New Directions. Active: c. 1955–2016" },
  { name: "Fré Cohen", tooltip: "Dutch designer and poster artist of the Amsterdam School style, blending Art Deco geometry with expressionist color. Active: c. 1920–1943" },
  { name: "Vincent Connare", tooltip: "American type designer who created Comic Sans (1994) and Trebuchet MS. Active: from 1993" },
  { name: "Muriel Cooper", tooltip: "American designer who co-founded MIT Media Lab's Visible Language Workshop. Pioneered digital information design. Active: c. 1952–1994" },
  { name: "Wim Crouwel", tooltip: "Dutch typographer and co-founder of Total Design. Known for the gridnik New Alphabet and systematic grid-based design. Active: c. 1952–2019" },
  { name: "Stanisław Czerski", tooltip: "Polish graphic designer and poster artist contributing to the Polish School of Posters tradition. Active: mid-20th century" },
  { name: "Alison Donalty", tooltip: "American graphic designer and art director known for creative direction at major publications. Active: from 1990s" },
  { name: "Stanley Donwood", tooltip: "British artist who has created all of Radiohead's album artwork since 1994. Known for apocalyptic, layered imagery. Active: from 1994" },
  { name: "Aaron Draplin", tooltip: "American designer known for bold, thick-lined vintage-inspired logos. Founded Draplin Design Co. and Field Notes. Active: from 1995" },
  { name: "Hugh Dubberly", tooltip: "American designer and information architect. Former Apple creative manager. Known for systems-thinking and design models. Active: from 1980s" },
  { name: "Charles and Ray Eames", tooltip: "American husband-and-wife design duo. Icons of mid-century modernism in furniture, film, exhibition, and graphic design. Active: c. 1941–1988" },
  { name: "Tom Eckersley", tooltip: "British poster designer known for bold, simplified graphic forms and wartime information posters. Active: c. 1934–1996" },
  { name: "Heinz Edelmann", tooltip: "Czech-German illustrator and designer who created the visual style for the Beatles' Yellow Submarine animated film (1968). Active: c. 1958–2009" },
  { name: "Dick Elffers", tooltip: "Dutch graphic designer and painter known for vibrant, expressive poster designs and murals. Active: c. 1946–1990" },
  { name: "Siavash Fani", tooltip: "Iranian graphic designer known for blending Persian visual culture with modern design principles. Active: from 1990s" },
  { name: "Edward Fella", tooltip: "American designer known for hand-drawn, irregular typography and vernacular-inspired experimental design. Active: from 1980s" },
  { name: "Pablo Ferro", tooltip: "Cuban-American title designer known for kinetic, hand-drawn typography for Kubrick's Dr. Strangelove and other films. Active: c. 1955–2018" },
  { name: "Friedrich Kurt Fiedler", tooltip: "German graphic designer and type designer associated with the New Typography movement. Active: early-to-mid 20th century" },
  { name: "Louise Fili", tooltip: "American designer specializing in restaurant branding, book jackets, and Italian-influenced typographic lettering. Active: from 1978" },
  { name: "Vittorio Fiorucci", tooltip: "Canadian poster designer known for bold, sensual Art Deco–influenced theatrical and event posters. Active: c. 1970s–2008" },
  { name: "Clifton Firth", tooltip: "New Zealand painter and graphic designer known for landscape art and early New Zealand commercial design. Active: early-to-mid 20th century" },
  { name: "Alan Fletcher", tooltip: "British designer and Pentagram co-founder. Known for witty, playful conceptual design and the V&A identity. Active: c. 1959–2006" },
  { name: "Janet Froelich", tooltip: "American art director of The New York Times Magazine (1987–2004). Known for inventive, conceptual editorial layouts. Active: from 1980s" },
  { name: "Adrian Frutiger", tooltip: "Swiss type designer who created Univers and Frutiger typefaces. Revolutionized signage and wayfinding typography. Active: c. 1954–2015" },
  { name: "Shigeo Fukuda", tooltip: "Japanese designer known for optical illusions, visual puns, and impossibly clever poster designs. Active: c. 1956–2009" },
  { name: "Ken Garland", tooltip: "British designer and author of First Things First manifesto (1964), advocating socially responsible design. Active: from 1962" },
  { name: "Tom Geismar", tooltip: "American designer and co-founder of Chermayeff & Geismar. Created logos for Mobil, PBS, Chase Bank, and NBC. Active: from 1957" },
  { name: "Eric Gill", tooltip: "British sculptor, typeface designer, and printmaker. Created Gill Sans and Perpetua typefaces. Active: c. 1905–1940" },
  { name: "Milton Glaser", tooltip: "American designer who created the iconic I ❤ NY logo, the psychedelic Bob Dylan poster, and co-founded New York magazine. Active: c. 1954–2020" },
  { name: "Carin Goldberg", tooltip: "American designer known for conceptual, typographically rich book cover designs for major publishers. Active: c. 1982–2020" },
  { name: "Denise Gonzales Crisp", tooltip: "American designer and educator exploring the boundaries of graphic design through critical, experimental practice. Active: from 1990s" },
  { name: "April Greiman", tooltip: "American designer who pioneered digital design and new-wave typography using early Macintosh computers. Active: from 1976" },
  { name: "Rick Griffith", tooltip: "American designer and typographer, co-founder of MATTER and known for community-engaged design projects. Active: from 1990s" },
  { name: "Catrin G. Grosse", tooltip: "German graphic designer contributing to contemporary European visual communication. Active: from 2000s" },
  { name: "Rudolf Grüttner", tooltip: "German graphic artist known for poster design and visual communication in post-war Germany. Active: mid-to-late 20th century" },
  { name: "Bugra Gulsoy", tooltip: "Turkish actor and graphic designer with a background in visual communication design. Active: from 2000s" },
  { name: "Shekhar Gurera", tooltip: "Indian political cartoonist and illustrator known for editorial cartoons in major Indian publications. Active: from 1990s" },
  { name: "Dave Halili", tooltip: "Filipino-American graphic designer working in brand identity, packaging, and digital design. Active: from 2000s" },
  { name: "Baron Barrymore Halpenny", tooltip: "Canadian aviation historian and illustrator known for detailed technical drawings of World War aircraft. Active: c. 1960s–2000s" },
  { name: "Dorothy E. Hayes", tooltip: "American graphic designer and educator contributing to mid-century commercial and educational design. Active: mid-20th century" },
  { name: "Jessica Helfand", tooltip: "American designer, author, and co-founder of Design Observer. Writer on visual culture and design criticism. Active: from 1989" },
  { name: "Steven Heller", tooltip: "American design writer, critic, and educator. Co-chair of the SVA MFA Design program. Prolific author on design history. Active: from 1974" },
  { name: "Fons Hickmann", tooltip: "German designer known for expressive, culturally engaged poster design and typographic experimentation. Active: from 1990s" },
  { name: "Jon Hicks", tooltip: "British designer who created the Firefox browser logo and the Mailchimp identity. Known for icon design. Active: from 1997" },
  { name: "Jessica Hische", tooltip: "American letterer and type designer known for elaborate drop caps, the Daily Drop Cap project, and expressive hand-lettering. Active: from 2006" },
  { name: "Armin Hofmann", tooltip: "Swiss designer and Basel School of Design teacher. Master of stark, poetic black-and-white poster design. Active: c. 1947–2020" },
  { name: "Julian House", tooltip: "British designer known for Intro studio's music packaging and the hauntological aesthetic of Ghost Box Records artwork. Active: from 1990s" },
  { name: "Max Huber", tooltip: "Swiss-Italian designer known for dynamic, layered compositions and vivid color in poster and exhibition design. Active: c. 1940–1992" },
  { name: "Hans Hulsbosch", tooltip: "Dutch-Australian brand strategist who redesigned the Woolworths and Qantas identities. Active: from 1978" },
  { name: "Angus Hyland", tooltip: "British designer and Pentagram partner known for elegant, conceptual book design and visual identity work. Active: from 1990s" },
  { name: "Mirko Ilić", tooltip: "Bosnian-American designer and illustrator known for politically engaged editorial illustration and poster design. Active: from 1980s" },
  { name: "Breuk Iversen", tooltip: "American interactive designer and design educator combining branding with experiential digital environments. Active: from 1990s" },
  { name: "Tariq Jakobsen", tooltip: "Danish architect and designer working across graphic design and architectural visual communication. Active: from 1990s" },
  { name: "Aurélien Jeanney", tooltip: "French illustrator and graphic designer known for detailed, whimsical editorial and children's book illustration. Active: from 2000s" },
  { name: "Tibor Kalman", tooltip: "Hungarian-American designer and founding editor of Colors magazine. Champion of provocative, socially conscious design. Active: c. 1979–1999" },
  { name: "Ronald Kapaz", tooltip: "Brazilian designer and co-founder of QG.fak studio. Known for culturally rich Brazilian identity and packaging design. Active: from 1990s" },
  { name: "Susan Kare", tooltip: "American designer who created the original Macintosh icons, fonts, and interface elements (1983). Pioneer of pixel art in UI. Active: from 1983" },
  { name: "Ruth Kedar", tooltip: "Brazilian-Israeli-American designer who created the Google logo, refining it from serif to the clean wordmark. Active: from 1990s" },
  { name: "Jeffery Keedy", tooltip: "American type designer and educator. Created the influential Keedy Sans typeface of the 1990s CalArts scene. Active: from 1985" },
  { name: "Chip Kidd", tooltip: "American book cover designer at Knopf. Known for the Jurassic Park cover and innovative, conceptual jackets. Active: from 1986" },
  { name: "Jock Kinneir", tooltip: "British designer who, with Margaret Calvert, designed the UK motorway and road signage system and the Transport typeface. Active: c. 1957–1994" },
  { name: "Barbara Kruger", tooltip: "American conceptual artist and designer. Bold red-and-white text overlays on photographs conveying feminist and consumer critiques. Active: from 1970s" },
  { name: "Nedim Kufi", tooltip: "Iraqi-Dutch graphic designer and poster artist blending Arabic calligraphy with politically charged contemporary design. Active: from 1990s" },
  { name: "Walter Landor", tooltip: "German-American branding pioneer who founded Landor Associates. Created identities for Coca-Cola, FedEx, and BP. Active: c. 1941–1995" },
  { name: "Poul Lange", tooltip: "Danish graphic designer contributing to Scandinavian typographic and poster design traditions. Active: mid-to-late 20th century" },
  { name: "Zuzana Licko", tooltip: "Slovak-American type designer and co-founder of Emigre. Created influential digital typefaces including Mrs Eaves and Matrix. Active: from 1984" },
  { name: "John Lloyd", tooltip: "British television producer and designer with contributions to visual media and creative communication. Active: from 1970s" },
  { name: "Herb Lubalin", tooltip: "American typographer known for expressive display typography, the Avant Garde typeface, and innovative editorial layouts. Active: c. 1945–1981" },
  { name: "Ellen Lupton", tooltip: "American design writer, curator, and educator. Senior curator at Cooper Hewitt. Author of Thinking with Type. Active: from 1985" },
  { name: "John Maeda", tooltip: "American designer and technologist. Former president of RISD. Combines coding with design in generative and interactive work. Active: from 1990s" },
  { name: "O'Plérou", tooltip: "Ivorian designer known for Zouzoukwa, a set of African emoji stickers celebrating African culture and identity. Active: from 2010s" },
  { name: "Martin Majoor", tooltip: "Dutch type designer who created the Scala and Seria typefaces, known for harmonizing serif and sans-serif families. Active: from 1986" },
  { name: "Aldus Manutius", tooltip: "Venetian Renaissance printer and publisher. Invented italic type, the pocket book format, and the modern semicolon. Active: c. 1490–1515" },
  { name: "Oscar Mariné", tooltip: "Spanish graphic designer and art director known for bold, experimental poster and magazine design in Madrid's La Movida scene. Active: from 1980s" },
  { name: "Bruce Mau", tooltip: "Canadian designer known for S,M,L,XL (with Rem Koolhaas) and the Massive Change project on design as global force. Active: from 1985" },
  { name: "Katherine McCoy", tooltip: "American designer and educator who co-chaired Cranbrook Academy's design program, advancing deconstructivist design theory. Active: c. 1971–2003" },
  { name: "Dave McKean", tooltip: "British illustrator and designer known for mixed-media covers for DC Comics' Sandman series, and the film MirrorMask. Active: from 1986" },
  { name: "Philip B. Meggs", tooltip: "American design historian. Author of A History of Graphic Design, the most influential textbook in the field. Active: c. 1968–2002" },
  { name: "Debbie Millman", tooltip: "American designer, author, and host of Design Matters podcast, the longest-running design podcast. Active: from 1993" },
  { name: "Ron Miriello", tooltip: "American designer based in San Diego, known for lifestyle branding, packaging, and environmental graphics. Active: from 1983" },
  { name: "László Moholy-Nagy", tooltip: "Hungarian Bauhaus artist and educator. Pioneered photograms, photo-collage, and integrated typographic-photographic compositions. Active: c. 1920–1946" },
  { name: "Morteza Momayez", tooltip: "Iranian graphic designer, 'father of modern Iranian graphic design.' Merged Persian aesthetics with International Style. Active: c. 1960–2005" },
  { name: "Aries Moross", tooltip: "British designer and illustrator known for vibrant, hand-drawn lettering and bold identity work for music and culture. Active: from 2007" },
  { name: "William Morris", tooltip: "British Arts and Crafts movement founder. Revived handcraft through wallpaper, textile, typeface, and book design. Active: c. 1861–1896" },
  { name: "Josef Müller-Brockmann", tooltip: "Swiss designer and author of Grid Systems in Graphic Design. Master of the International Typographic Style. Active: c. 1950–1996" },
  { name: "Bruno Munari", tooltip: "Italian artist and designer. Pioneer of kinetic art, children's books, and design methodology. Active: c. 1930–1998" },
  { name: "Erik Nitsche", tooltip: "Swiss-American designer known for modernist posters for General Dynamics and his Atoms for Peace campaign. Active: c. 1940–1998" },
  { name: "Wally Olins", tooltip: "British brand consultant and co-founder of Wolff Olins. Pioneered nation branding and corporate identity strategy. Active: c. 1965–2014" },
  { name: "Vaughan Oliver", tooltip: "British designer known for atmospheric, textured album artwork for 4AD Records (Pixies, Cocteau Twins). Active: c. 1982–2019" },
  { name: "István Orosz", tooltip: "Hungarian graphic artist known for anamorphic art, visual paradoxes, and M.C. Escher–influenced impossible geometries. Active: from 1975" },
  { name: "Fra Paalman", tooltip: "Dutch graphic designer contributing to contemporary Dutch design and visual communication. Active: from 2000s" },
  { name: "Robert L. Peters", tooltip: "Canadian designer and president of Icograda (2001–2003). Advocate for design's role in social responsibility. Active: from 1985" },
  { name: "Clive Piercy", tooltip: "British-American designer known for entertainment industry branding, film identity, and Los Angeles cultural design. Active: from 1980s" },
  { name: "Leif Podhajsky", tooltip: "Australian designer known for psychedelic, nature-inspired album artwork for Tame Impala and other bands. Active: from 2009" },
  { name: "Soundarya Rajinikanth", tooltip: "Indian film producer and graphic designer. Combined Tamil film industry creative direction with graphic design practice. Active: c. 2002–2004" },
  { name: "Nadhim Ramzi", tooltip: "Iraqi graphic designer known for Arabic calligraphic design and cross-cultural visual communication work. Active: from 1990s" },
  { name: "Paul Rand", tooltip: "American master of corporate identity. Created logos for IBM, ABC, UPS, and Westinghouse. Author of Thoughts on Design. Active: c. 1936–1996" },
  { name: "Satyajit Ray", tooltip: "Indian filmmaker and designer who hand-designed his own film posters, book covers, and the Ray Roman typeface for Bengali. Active: c. 1947–1992" },
  { name: "Mikhail Rojter", tooltip: "Ukrainian-American designer known for expressive, painterly poster design bridging Eastern European and Western traditions. Active: from 1990s" },
  { name: "Tina Roth-Eisenberg", tooltip: "Swiss-American designer and entrepreneur. Founded swissmiss, CreativeMornings, and Tattly temporary tattoos. Active: from 2005" },
  { name: "Dolly Rudeman", tooltip: "Dutch graphic designer and poster artist associated with the early-20th-century Dutch applied arts movement. Active: c. 1910–1940" },
  { name: "Emil Ruder", tooltip: "Swiss typographer and Basel School teacher. Author of Typography: A Manual of Design. Champion of clarity and grid systems. Active: c. 1942–1970" },
  { name: "Giovanni Russo", tooltip: "Italian graphic designer contributing to contemporary European visual communication and branding. Active: from 1990s" },
  { name: "Mehdi Saeedi", tooltip: "Iranian graphic designer and poster artist blending Persian visual traditions with minimalist, contemporary composition. Active: from 1990s" },
  { name: "Stefan Sagmeister", tooltip: "Austrian-American designer known for provocative, personal work — including carving typography into his own skin. Active: from 1993" },
  { name: "Louise Sandhaus", tooltip: "American designer and CalArts faculty member. Author of Earthquakes, Mudslides, Fires and Riots: California and Graphic Design. Active: from 1990s" },
  { name: "Peter Saville", tooltip: "British designer who defined post-punk and New Wave visual culture through album covers for Joy Division and New Order. Active: from 1978" },
  { name: "Jan Sawka", tooltip: "Polish-American artist known for dramatic, large-scale painted and printed poster art merging illustration with design. Active: c. 1970–2012" },
  { name: "Paula Scher", tooltip: "American designer and Pentagram partner. Known for bold, expressive typographic identities — including the Public Theater and Citibank. Active: from 1972" },
  { name: "Paul Schuitema", tooltip: "Dutch designer who applied Constructivist principles to advertising, using photomontage and asymmetric typography. Active: c. 1926–1973" },
  { name: "Mike Shinoda", tooltip: "American musician (Linkin Park) and graphic designer. Designed album artwork and merchandise with a street-art sensibility. Active: from 1996" },
  { name: "Ghobad Shiva", tooltip: "Iranian graphic designer contributing to contemporary Iranian poster art and typographic design. Active: from 1990s" },
  { name: "Bonnie Siegler", tooltip: "American designer and founder of Eight and a Half studio. Known for branding, editorial, and television design. Active: from 1993" },
  { name: "Christopher Simmons", tooltip: "American designer and MINE co-founder. Known for witty, conceptual branding and design education advocacy. Active: from 1994" },
  { name: "Erik Spiekermann", tooltip: "German typographer who created FF Meta and ITC Officina typefaces. Co-founded MetaDesign and FontShop. Active: from 1972" },
  { name: "Hugh Syme", tooltip: "Canadian designer and illustrator. Created iconic album artwork for Rush for over 40 years. Active: from 1975" },
  { name: "Aaron Tanner", tooltip: "American graphic designer working in contemporary branding, identity, and visual communication. Active: from 2000s" },
  { name: "Marc Tedeschi", tooltip: "American designer and photographer contributing to editorial and commercial design. Active: from 1990s" },
  { name: "Jake Tilson", tooltip: "British artist and designer blending collage, photography, and web-based art in explorations of food culture and place. Active: from 1980s" },
  { name: "Ivana Tomljenović-Meller", tooltip: "Croatian Bauhaus-trained designer and artist known for avant-garde textile design, posters, and photomontage. Active: c. 1926–1986" },
  { name: "Jan Tschichold", tooltip: "German typographer who codified the New Typography movement, then later championed classical book design. Active: c. 1926–1974" },
  { name: "Carol Twombly", tooltip: "American type designer at Adobe who created Trajan, Myriad, and Charlemagne typefaces. Active: c. 1988–1999" },
  { name: "Rudy VanderLans", tooltip: "Dutch-American designer and co-founder/editor of Emigre magazine, a defining voice for digital-age typography. Active: from 1984" },
  { name: "James Victore", tooltip: "American designer known for raw, hand-drawn provocative posters and an unapologetic, personal design ethos. Active: from 1990" },
  { name: "Massimo Vignelli", tooltip: "Italian-American modernist designer. Created the NYC subway map, Knoll identity, and American Airlines branding. Active: c. 1960–2014" },
  { name: "Jurek Wajdowicz", tooltip: "Polish-American designer known for photographic editorial design and socially conscious communication. Active: from 1980s" },
  { name: "Jessica Walsh", tooltip: "American designer, artist, and co-founder of &Walsh studio. Known for bold, colorful conceptual campaigns. Active: from 2010" },
  { name: "Brian Webb", tooltip: "British designer known for postage stamp design and cultural-institution identities with typographic elegance. Active: from 1972" },
  { name: "Wolfgang Weingart", tooltip: "German-Swiss typographer who pioneered New Wave / post-modernist typography at Basel. 'Father of Swiss Punk typography.' Active: from 1968" },
  { name: "Lynda Weinman", tooltip: "American designer and technology educator. Co-founded Lynda.com (now LinkedIn Learning). Active: from 1993" },
  { name: "Bob West", tooltip: "American graphic designer and lettering artist contributing to commercial and editorial design. Active: late 20th century" },
  { name: "Lorraine Wild", tooltip: "American designer and educator. Combines rigorous modernist form with critical, postmodern questioning. Active: from 1980s" },
  { name: "Michael Wolff", tooltip: "British brand designer and co-founder of Wolff Olins, one of the world's most influential identity consultancies. Active: c. 1965–2010s" },
  { name: "Kijuro Yahagi", tooltip: "Japanese graphic designer contributing to mid-century Japanese commercial and poster design. Active: mid-20th century" },
  { name: "Yuri Yokomizo", tooltip: "Japanese designer and typographer contributing to contemporary Japanese visual communication. Active: from 1990s" },
  { name: "Pilar Zeta", tooltip: "Argentine multidisciplinary artist and designer creating immersive, surreal installations and futuristic visual worlds. Active: from 2010s" },
  { name: "Piet Zwart", tooltip: "Dutch designer who merged De Stijl, Constructivism, and Dada in innovative typographic and photographic designs. Active: c. 1919–1966" }
];
