export const ILLUSTRATORS = [
  "Salomon van Abbé",
  "Edwin Austin Abbey",
  "Elenore Abbott",
  "Jacob Bates Abbott",
  "Abed Abdi",
  "Jean Adamson",
  "Dan Adkins",
  "Attila Adorjany",
  "Alex Akerbladh",
  "Constantin Alajalov",
  "Maria Pascual Alberich",
  "Annette Allcock",
  "Thomas B. Allen",
  "Thomas Allom",
  "Chris Van Allsburg",
  "Yoshitaka Amano",
  "Victor Ambrus",
  "Raymond Ameijide",
  "Anne Anderson",
  "Lai Ann",
  "Chris Appelhans",
  "Honor C. Appleton",
  "Cosmo Armstrong",
  "Peter Arno",
  "Hans Arnold",
  "James Arnold",
  "Rodolfo Arotxarena",
  "Steve Augarde",
  "Margaret Ayer",
  "Russell Ayto",
  "Ken Bald",
  "Roberto Baldazzini",
  "Cyrus Leroy Baldridge",
  "Jan Balet",
  "Asun Balzola",
  "Edgar Henry Banger",
  "Eulalie Minfred Banks",
  "Istvan Banyai",
  "George Barbier",
  "Cicely Mary Barker",
  "Kathleen Frances Barker",
  "Carl Barks",
  "Angela Barrett",
  "Niko Barun",
  "Graeme Base",
  "Gary Baseman",
  "Johanna Basford",
  "Rudi Bass",
  "Richard Bassford",
  "John Batchelor",
  "Vincent Batignole",
  "John Dickson Batten",
  "John Bauer",
  "Pauline Baynes",
  "S.G. Hulme Beaman",
  "Aubrey Beardsley",
  "Julie Bell",
  "Ludwig Bemelmans",
  "Earle K. Bergey",
  "Jon Berkeley",
  "Louisa Bertman",
  "Elsa Beskow",
  "Rupert Besley",
  "David Biedrzycki",
  "Alessandro Biffignandi",
  "Ivan Bilibin",
  "Guy Billout",
  "Charles Binger",
  "Ned Bittinger",
  "Mary Blair",
  "Quentin Blake",
  "Ivan Blinov",
  "Cheeming Boey",
  "Hannes Bok",
  "Enoch Bolles",
  "Chesley Bonestell",
  "Melinda Bordelon",
  "Tom Bouden",
  "Anna Boudová Suchardová",
  "Eleanor Vere Boyle",
  "Syd Brak",
  "Anna Brandoli",
  "Kaare Bratung",
  "Lynn Breeze",
  "Molly Brett",
  "Rae Bridgman",
  "Raymond Briggs",
  "Pierre Brissaud",
  "Steve Brodner",
  "Gerald Brom",
  "Jason Brooks",
  "Gordon Browne",
  "Hablot Knight Browne",
  "Margaret Brundage",
  "René Bull",
  "Nancy Ekholm Burkert",
  "Mark Burrier",
  "Priscilla Susan Bury",
  "Sergio Burzi",
  "Matt Busch",
  "Mitch Butler",
  "Felicity Campbell",
  "Aldo Capitanio",
  "Fernando Carcupino",
  "Edd Cartier",
  "Chao Yat",
  "Glenn Chadbourne",
  "Watson Charlton",
  "Earle D. Chesney",
  "Lauren Child",
  "Richard Chopping",
  "Howard Chandler Christy",
  "Edgar Church",
  "Fabio Civitelli",
  "Alan M. Clark",
  "Harry Clarke",
  "John Cecil Clay",
  "John Clymer",
  "Alan E. Cober",
  "Ted CoConis",
  "Anthony Colbert",
  "Hedvig Collin",
  "Coop",
  "Frank Cadogan Cowper",
  "Kinuko Y. Craft",
  "Reed Crandall",
  "Donald Crews",
  "Max Crivello",
  "Robert Crumb",
  "Thelma Cudlipp",
  "Stacy Curtis",
  "Geofrey Darrow",
  "Harry Grant Dart",
  "Honoré Daumier",
  "Jack Davis",
  "Reginald Ben Davis",
  "Jane Mary Dealy",
  "Adam Dechanel",
  "Jason Deeble",
  "Paul Degen",
  "Gertrude Degenhardt",
  "Étienne Delessert",
  "John Henry Dell",
  "Christopher Denise",
  "W.W. Denslow",
  "Vince Deporter",
  "Peter de Sève",
  "Ali Dilem",
  "Brad Diller",
  "Leo and Diane Dillon",
  "Irv Docktor",
  "Richard Staples Dodge",
  "Angela Dominguez",
  "Franco Donatelli",
  "Donelan",
  "Gustave Doré",
  "Denise Dorrance",
  "Ralph Waddell Douglass",
  "Richard Doyle",
  "Roger Drew",
  "Edmund Dulac",
  "Georges Dumitresco",
  "Frederick Melville DuMond",
  "Harvey Dunn",
  "Nicolas Eekman",
  "Lois Ehlert",
  "Edna Eicke",
  "Susan Einzig",
  "Will Elder",
  "David Elliot",
  "Craig Elliott",
  "Gil Elvgren",
  "Ed Emberley",
  "Peter Emmerich",
  "Ed Emshwiller",
  "Jack Endewelt",
  "Mark English",
  "Maginel Wright Enright",
  "Otto Eppers",
  "Erté",
  "Dulah Marie Evans",
  "Carl Eytel",
  "Jules Faber",
  "João Fahrion",
  "Frances C. Fairman",
  "Cathie Felstead",
  "Major Felten",
  "Jules Férat",
  "Nathalie Ferlut",
  "Alfons Figueras",
  "Rod Filbrandt",
  "Leonard Filgate",
  "Virgil Finlay",
  "Steve Fiorilla",
  "James Montgomery Flagg",
  "Jim Flora",
  "René Follet",
  "Mary Hallock Foote",
  "Henry Justice Ford",
  "Hal Foster",
  "Marcia Lane Foster",
  "Julien Fournié",
  "Jane Frank",
  "Malcolm Fraser",
  "Frank Frazetta",
  "Kelly Freas",
  "Anthony Freda",
  "Chandra Free",
  "Barbara C. Freeman",
  "Oli Frey",
  "Brian Froud",
  "Bernie Fuchs",
  "Joseph Fuchs",
  "Thomas Fuchs",
  "Gyo Fujikawa",
  "Magdalena Rosina Funck",
  "Tom Funk",
  "Eva Furnari",
  "Wanda Gág",
  "Dumitru Găleșanu",
  "Hector Garrido",
  "Carolyn Bartlett Gast",
  "Zhenya Gay",
  "Roman Genn",
  "Pencho Georgiev",
  "Eddie Germano",
  "Charles Dana Gibson",
  "Anne Yvonne Gilbert",
  "Eric Gill",
  "Margery Gill",
  "Willi Glasauer",
  "Milton Glaser",
  "Robin Preiss Glasser",
  "Frank Godwin",
  "Ted Goff",
  "Fabian Göranson",
  "Edward Gorey",
  "Ruth Sigrid Grafstrom",
  "Carlos Grangel",
  "Vernon Grant",
  "Elizabeth Shippen Green",
  "Kate Greenaway",
  "Rebecca Guay",
  "Shekhar Gurera",
  "Vee Guthrie",
  "Dick Hafer",
  "Michael Hague",
  "Bob Hall",
  "Marcellus Hall",
  "Baron Barrymore Halpenny",
  "Clifford Harper",
  "Jim Harris",
  "Steven Harris",
  "Ernest William Haslehust",
  "Catherine Haussard",
  "Elisabeth Haussard",
  "Adam Heller",
  "Ruth Heller",
  "Danny Hellman",
  "Brett Helquist",
  "Andrew Kennaway Henderson",
  "Joseph Morgan Henninger",
  "Cornelia Hesse-Honegger",
  "Don Hewitt",
  "Don Hillsman II",
  "Henry Hintermeister",
  "John Henry Hintermeister",
  "Walter Haskell Hinton",
  "Jessica Hische",
  "Susie Hodge",
  "Dick Hodgins Jr.",
  "Rosekrans Hoffman",
  "William Hogarth",
  "Hokusai",
  "Brad Holland",
  "Nicole Hollander",
  "Holling C. Holling",
  "Edgar Alfred Holloway",
  "Winslow Homer",
  "Jeff Hook",
  "Daniel Horne",
  "James Horvath",
  "John Howe",
  "Mentor Huebner",
  "David Hughes",
  "Debbie Hughes",
  "Rian Hughes",
  "Jim Hummel",
  "Barry Hunau",
  "Robert Hunt",
  "Trina Schart Hyman",
  "Robert Ingpen",
  "Koji Ishikawa",
  "Robin Jacques",
  "Al Jaffee",
  "Jago",
  "Zoran Janjetov",
  "Kirk Jarvinen",
  "James Jean",
  "Aurélien Jeanney",
  "Oliver Jeffers",
  "Alfred Garth Jones",
  "Eddie Jones",
  "G. B. Jones",
  "Patrick J. Jones",
  "Piet de Jong",
  "Federico Jordan",
  "Ingrīda Kadaka",
  "Arja Kajermo",
  "Maira Kalman",
  "Jack Kamen",
  "Avi Katz",
  "Cosei Kawa",
  "Charles Keeping",
  "Jack Kent",
  "Dóra Keresztes",
  "Charles Kerins",
  "Kazu Kibuishi",
  "J. D. King",
  "Wyncie King",
  "Josh Kirby",
  "Cem Kızıltuğ",
  "Hilary Knight",
  "Lucy Knisley",
  "Shahar Kober",
  "E. L. Konigsburg",
  "Ben Krefta",
  "Roy Krenkel",
  "Andrea Kruis",
  "Anita Kunz",
  "Agi Lamm",
  "Yvette Lapointe",
  "Antonio Lara de Gavilán",
  "Philippe Lardy",
  "Kivi Larmola",
  "Abigail Larson",
  "Paul Laune",
  "Rick Law",
  "John Lawrence",
  "Edward Lear",
  "Alan Lee",
  "Suzy Lee",
  "John Leech",
  "Alfred Leete",
  "João M. P. Lemos",
  "Lois Lenski",
  "Olive Leonhardt",
  "Cecil Mary Leslie",
  "Michael Leunig",
  "Celia Levetus",
  "Harris Levey",
  "Arnold Levin",
  "Thomas Noyes Lewis",
  "J. C. Leyendecker",
  "Kenneth Norman Lilly",
  "Selena Lin",
  "Oleg Lipchenko",
  "Virginio Livraghi",
  "Andrew Loomis",
  "Rafael Lopez",
  "Félix Lorioux",
  "Frederick Lowenheim",
  "Lubov",
  "Miel Prudencio Ma",
  "Annette Macarthur-Onslow",
  "David W. Mack",
  "Robert Maguire",
  "Matt Mahurin",
  "Gorg Mallia",
  "Mark Marderosian",
  "Marcel Marlier",
  "Michael Martchenko",
  "Antoinette Martignoni",
  "Emily Winfield Martin",
  "Felix Mas",
  "Fortunino Matania",
  "David Burroughs Mattingly",
  "Steve Mattsson",
  "Tatyana Mavrina",
  "John Alan Maxwell",
  "Mercer Mayer",
  "James Mayhew",
  "Angus McBride",
  "Winsor McCay",
  "Jeff McComsey",
  "James E. McConnell",
  "Jerry McDaniel",
  "Jim McDermott",
  "Thomas McIlvaine",
  "Craig McKay",
  "Dave McKean",
  "David McKee",
  "Shawn McManus",
  "Lilian Marguerite Medland",
  "Will G. Mein",
  "Farshid Mesghali",
  "David Messer",
  "Ken Messer",
  "Florence Meyerheim",
  "Ronald Michaud",
  "Yevgeniy Migunov",
  "H. R. Millar",
  "Mr Bingo",
  "Fanny Elizabeth de Mole",
  "Tim Molloy",
  "Chris Monroe",
  "Jeanne Montbaston",
  "Jacqui Morgan",
  "Barry Moser",
  "Colonel Moutarde",
  "Alfons Mucha",
  "Salvatore Murdocca",
  "Kelly Murphy",
  "Namboothiri",
  "Gogu Neagoe",
  "Kadir Nelson",
  "Barbara Nessim",
  "Vicky Newman",
  "Victo Ngai",
  "Kay Nielsen",
  "Christoph Niemann",
  "Adam Niklewicz",
  "Ignacio Noe",
  "Violet Oakley",
  "John O'Carroll",
  "Alan Odle",
  "Elena Odriozola",
  "Power O'Malley",
  "Glen Orbik",
  "István Orosz",
  "Emre Ozdemir",
  "Sidney Paget",
  "Walter Paget",
  "Gaman Palem",
  "John Jude Palencar",
  "Fung Chin Pang",
  "William Papas",
  "Roberto Parada",
  "Eric Parker",
  "Peter Parnall",
  "Maxfield Parrish",
  "Dave Pascal",
  "Alan Stuart Paterson",
  "Frank R. Paul",
  "C. F. Payne",
  "Bob Peak",
  "Mervyn Peake",
  "Susan Beatrice Pearse",
  "Clara Elsene Peck",
  "Thomas Mitchell Peirce",
  "Bob Penuelas",
  "Laura Pérez Vernetti",
  "Domingo F. Periconi",
  "Rosa C. Petherick",
  "Keats Petree",
  "Valerie Petts",
  "Mary Petty",
  "S. D. Phadnis",
  "LeUyen Pham",
  "Craig Phillips",
  "Françoise Pichard",
  "André Pijet",
  "Brian Pilkington",
  "Rose M. M. Pitman",
  "Hanoch Piven",
  "George Wolfe Plank",
  "Willy Pogany",
  "Beatrix Potter",
  "Richard M. Powers",
  "Ernest Prater",
  "Michael Mathias Prechtl",
  "Alice and Martin Provensen",
  "Howard Pyle",
  "Rosane Quintella",
  "Arthur Rackham",
  "Arifur Rahman",
  "Alberto Rapisarda",
  "Chris Raschka",
  "Walter Ratterman",
  "Barb Rausch",
  "Leonard Raven-Hill",
  "Else Raydt",
  "Gardner Rea",
  "Mary A. Reardon",
  "Ralph Reese",
  "Marlene Reidel",
  "Charles M. Relyea",
  "Emma Rendel",
  "Sarah Rhodes",
  "Renée Rienties",
  "Robert Riger",
  "Elizabeth Rivers",
  "David Roberts",
  "Albert Robida",
  "Heath Robinson",
  "Christine Roche",
  "Norman Rockwell",
  "Laura Rodig",
  "Spain Rodriguez",
  "Lucinda Rogers",
  "Valentina Romeo",
  "Artie Romero",
  "Félicien Rops",
  "Don Rosa",
  "Rosalys",
  "Alex Ross",
  "Graham Roumieu",
  "Øystein Runde",
  "Willie Rushton",
  "Mark Ryden",
  "Robert Sabuda",
  "Wiktor Sadowski",
  "Alberto Saichann",
  "Xavier Saint-Just",
  "Armando Salas",
  "B. B. Sams",
  "Dan Santat",
  "Hal Santiago",
  "Norman Saunders",
  "Zina Saunders",
  "Allen Say",
  "Gerald Scarfe",
  "Richard Scarry",
  "Charles Schneeman",
  "Adolf Schrödter",
  "Simon Schwartz",
  "Richard A. Scott",
  "Steve Scott",
  "Henry Seabright",
  "Ronald Searle",
  "Wilhelmina Seegmiller",
  "Adrienne Segur",
  "Maurice Sendak",
  "Kate Seredy",
  "Ben Shahn",
  "Nick Sharratt",
  "Mark Shasha",
  "John Shelley",
  "Ernest Shepard",
  "Claude Allin Shepperson",
  "Dorothy Sherrill",
  "Gary Shipman",
  "David Shrigley",
  "John Sibbick",
  "Shel Silverstein",
  "Anne Simon",
  "Parismita Singh",
  "Peter Sís",
  "Jessie Willcox Smith",
  "Joseph A. Smith",
  "Lane Smith",
  "Cal Sobrepeña",
  "Fermín Solís",
  "Konstantin Somov",
  "Suzy Spafford",
  "Lancelot Speed",
  "Armstrong Sperry",
  "Art Spiegelman",
  "Peter Spier",
  "Minnie Dibdin Spooner",
  "Bob Staake",
  "Ralph Steadman",
  "Frederic Dorr Steele",
  "William Steig",
  "Ralph Stein",
  "Saul Steinberg",
  "Joan Steiner",
  "Karl Stirner",
  "William Stobbs",
  "Barron Storey",
  "Willy Stöwer",
  "Helen Stratton",
  "Drew Struzan",
  "Lillie Sullivan",
  "Arthur Suydam",
  "Hiromi Suzuki",
  "Glynis Sweeny",
  "Christophe Szpajdel",
  "Emanuele Taglietti",
  "Douglas Tait",
  "Shaun Tan",
  "Margaret Tarrant",
  "Robert Tavener",
  "Gary Taxali",
  "Françoise Taylor",
  "Prentiss Taylor",
  "Margaret Tempest",
  "Sir John Tenniel",
  "Henri Thiriet",
  "Béatrice Tillier",
  "Trini Tinturé",
  "Alton S. Tobey",
  "Margot Tomes",
  "Dolly Tree",
  "Stuart Tresilian",
  "Wallace Tripp",
  "Timothy Truman",
  "Tasha Tudor",
  "Michael Turner",
  "Dick Twinney",
  "Chen Uen",
  "Tomi Ungerer",
  "Clive Uptton",
  "Utisz",
  "Boris Vallejo",
  "Alberto Vargas",
  "Gee Vaucher",
  "Agaate Veeber",
  "Max Velthuijs",
  "Vhrsti",
  "Emilio Vilà",
  "Erich von Götha de la Rosière",
  "Charles Wadsworth",
  "Dugald Stewart Walker",
  "Ernest Wallcousins",
  "Charles Waterhouse",
  "Arthur Watts",
  "Betty Temple Watts",
  "Robert Weaver",
  "Emil Weiss",
  "Jack Welch",
  "Don Weller",
  "Paul Wenzel",
  "Michael Whelan",
  "Jon Whitcomb",
  "Garth Williams",
  "Robert Williams",
  "Charles Banks Wilson",
  "George Wilson",
  "Larry Winborg",
  "Eric Winter",
  "David Wisniewski",
  "Jonathan Wolstenholme",
  "Ashley Wood",
  "Leslie Wood",
  "Hildegard Woodward",
  "Shannon Wright",
  "Frank Wu",
  "N. C. Wyeth",
  "Takashi Yanase",
  "Marianne Young",
  "Yu Rong",
  "Margot Zemach",
  "Laura Zuccheri",
  "Lisbeth Zwerger"
];
