export const ILLUSTRATORS = [
  { name: "Salomon van Abbé", tooltip: "Dutch illustrator known for detailed, realistic portraits and book illustrations. Active: 1900-1950" },
  { name: "Edwin Austin Abbey", tooltip: "American painter and illustrator celebrated for historical and Shakespearean scenes. Active: 1870-1911" },
  { name: "Elenore Abbott", tooltip: "American illustrator and painter, noted for children's book and magazine art. Active: 1900-1930" },
  { name: "Jacob Bates Abbott", tooltip: "American illustrator recognized for educational and children's book illustrations. Active: 1850-1880" },
  { name: "Abed Abdi", tooltip: "Palestinian-Israeli painter and illustrator focusing on social and political themes. Active: 1960-present" },
  { name: "Jean Adamson", tooltip: "British author-illustrator famous for the Topsy and Tim series. Active: 1950-2010" },
  { name: "Dan Adkins", tooltip: "American comic book artist known for science fiction and fantasy illustrations. Active: 1960-1990" },
  { name: "Attila Adorjany", tooltip: "Hungarian illustrator and painter with a detailed, narrative style. Active: 1970-present" },
  { name: "Alex Akerbladh", tooltip: "Swedish illustrator and cartoonist, known for humorous and satirical works. Active: 1950-1980" },
  { name: "Constantin Alajalov", tooltip: "Russian-American illustrator celebrated for vibrant, witty covers for The New Yorker. Active: 1920-1970" },
  { name: "Maria Pascual Alberich", tooltip: "Spanish illustrator recognized for romantic and fashion-inspired artwork. Active: 1950-1980" },
  { name: "Annette Allcock", tooltip: "British illustrator known for detailed botanical and natural history drawings. Active: 1970-present" },
  { name: "Thomas B. Allen", tooltip: "American illustrator noted for realistic and atmospheric paintings. Active: 1950-2010" },
  { name: "Thomas Allom", tooltip: "British architect and illustrator famous for topographical and architectural views. Active: 1820-1870" },
  { name: "Chris Van Allsburg", tooltip: "American author-illustrator known for surreal, dreamlike picture books. Active: 1979-present" },
  { name: "Yoshitaka Amano", tooltip: "Japanese artist celebrated for ethereal, fantasy illustrations and character design. Active: 1970-present" },
  { name: "Victor Ambrus", tooltip: "Hungarian-born British illustrator known for historical and archaeological reconstructions. Active: 1960-present" },
  { name: "Raymond Ameijide", tooltip: "French illustrator recognized for elegant, Art Deco-inspired designs. Active: 1920-1950" },
  { name: "Anne Anderson", tooltip: "Scottish illustrator famous for charming, colorful children's book art. Active: 1900-1930" },
  { name: "Lai Ann", tooltip: "Malaysian illustrator known for vibrant, culturally rich digital artwork. Active: 2000-present" },
  { name: "Chris Appelhans", tooltip: "American illustrator and animator noted for whimsical, character-driven designs. Active: 2000-present" },
  { name: "Honor C. Appleton", tooltip: "British illustrator celebrated for delicate watercolors in children's literature. Active: 1900-1950" },
  { name: "Cosmo Armstrong", tooltip: "British illustrator known for humorous and satirical cartoon illustrations. Active: 1890-1920" },
  { name: "Peter Arno", tooltip: "American cartoonist famous for bold, satirical cartoons in The New Yorker. Active: 1925-1968" },
  { name: "Hans Arnold", tooltip: "Swedish illustrator recognized for playful, colorful children's book art. Active: 1950-2010" },
  { name: "James Arnold", tooltip: "British illustrator known for detailed historical and architectural drawings. Active: 1800-1850" },
  { name: "Rodolfo Arotxarena", tooltip: "Spanish illustrator noted for dynamic, expressive comic and poster art. Active: 1970-present" },
  { name: "Steve Augarde", tooltip: "British author-illustrator known for intricate, imaginative children's book illustrations. Active: 1970-present" },
  { name: "Margaret Ayer", tooltip: "American illustrator celebrated for elegant fashion and advertising artwork. Active: 1920-1950" },
  { name: "Russell Ayto", tooltip: "British illustrator famous for quirky, humorous picture book illustrations. Active: 1990-present" },
  { name: "Ken Bald", tooltip: "American comic book artist known for adventure and romance comic illustrations. Active: 1940-1980" },
  { name: "Roberto Baldazzini", tooltip: "Italian illustrator recognized for vibrant, narrative fantasy and sci-fi art. Active: 1970-present" },
  { name: "Cyrus Leroy Baldridge", tooltip: "American illustrator and painter noted for travel and ethnographic illustrations. Active: 1910-1950" },
  { name: "Jan Balet", tooltip: "German-American illustrator celebrated for whimsical, folk art-inspired designs. Active: 1930-1990" },
  { name: "Asun Balzola", tooltip: "Spanish illustrator known for expressive, colorful children's book artwork. Active: 1970-2010" },
  { name: "Edgar Henry Banger", tooltip: "British illustrator famous for detailed botanical and natural history illustrations. Active: 1880-1920" },
  { name: "Eulalie Minfred Banks", tooltip: "American illustrator recognized for charming children's book and magazine art. Active: 1900-1930" },
  { name: "Istvan Banyai", tooltip: "Hungarian illustrator known for clever, wordless picture books and editorial art. Active: 1980-present" },
  { name: "George Barbier", tooltip: "French illustrator celebrated for elegant Art Deco fashion plates. Active: 1910-1930" },
  { name: "Cicely Mary Barker", tooltip: "British illustrator famous for the Flower Fairies series, with delicate watercolors. Active: 1910-1970" },
  { name: "Kathleen Frances Barker", tooltip: "British illustrator known for detailed botanical and children's book illustrations. Active: 1920-1960" },
  { name: "Carl Barks", tooltip: "American cartoonist renowned for Disney duck comics and adventurous storytelling. Active: 1930-1990" },
  { name: "Angela Barrett", tooltip: "British illustrator noted for atmospheric, detailed historical picture books. Active: 1980-present" },
  { name: "Niko Barun", tooltip: "Croatian illustrator recognized for surreal, imaginative digital and traditional art. Active: 2000-present" },
  { name: "Graeme Base", tooltip: "Australian author-illustrator famous for intricate, hidden-object picture books. Active: 1980-present" },
  { name: "Gary Baseman", tooltip: "American artist known for playful, subversive illustrations blending pop and folk art. Active: 1990-present" },
  { name: "Johanna Basford", tooltip: "Scottish illustrator celebrated for intricate, hand-drawn adult coloring books. Active: 2000-present" },
  { name: "Rudi Bass", tooltip: "American illustrator known for vibrant, graphic advertising and poster art. Active: 1930-1970" },
  { name: "Richard Bassford", tooltip: "British illustrator recognized for detailed architectural and topographical drawings. Active: 1850-1890" },
  { name: "John Batchelor", tooltip: "British illustrator famous for highly detailed technical and aviation artwork. Active: 1960-present" },
  { name: "Vincent Batignole", tooltip: "French illustrator known for detailed, atmospheric scenes. Active: 1890-1920." },
  { name: "John Dickson Batten", tooltip: "British painter and illustrator of fairy tales with mystical, symbolic style. Active: 1880-1930." },
  { name: "John Bauer", tooltip: "Swedish illustrator famous for ethereal, folkloric fairy tale art. Active: 1900-1918." },
  { name: "Pauline Baynes", tooltip: "British illustrator renowned for detailed, whimsical drawings for Tolkien and Lewis. Active: 1940-2000." },
  { name: "S.G. Hulme Beaman", tooltip: "British illustrator and creator of Toytown, with charming, narrative style. Active: 1920-1950." },
  { name: "Aubrey Beardsley", tooltip: "English illustrator known for black-and-white Art Nouveau works with erotic, decadent themes. Active: 1890-1898." },
  { name: "Julie Bell", tooltip: "American fantasy artist known for hyperrealistic, muscular figures and vibrant colors. Active: 1990-present." },
  { name: "Ludwig Bemelmans", tooltip: "Austro-Hungarian-American illustrator, creator of Madeline with whimsical, Parisian scenes. Active: 1930-1960." },
  { name: "Earle K. Bergey", tooltip: "American pulp magazine illustrator famous for bold, sensational sci-fi covers. Active: 1930-1960." },
  { name: "Jon Berkeley", tooltip: "Irish illustrator known for detailed, imaginative children's book art. Active: 1990-present." },
  { name: "Louisa Bertman", tooltip: "Contemporary American illustrator with vibrant, graphic editorial style. Active: 2010-present." },
  { name: "Elsa Beskow", tooltip: "Swedish author-illustrator known for idyllic, nature-filled children's book illustrations. Active: 1890-1950." },
  { name: "Rupert Besley", tooltip: "British cartoonist and illustrator with humorous, satirical style. Active: 1980-present." },
  { name: "David Biedrzycki", tooltip: "American children's book illustrator known for playful, colorful digital art. Active: 1990-present." },
  { name: "Alessandro Biffignandi", tooltip: "Italian illustrator specializing in historical and fantasy art with dramatic realism. Active: 1970-2010." },
  { name: "Ivan Bilibin", tooltip: "Russian illustrator famous for stylized, folkloric art with intricate patterns. Active: 1900-1940." },
  { name: "Guy Billout", tooltip: "French-American illustrator known for surreal, minimalist editorial illustrations. Active: 1970-present." },
  { name: "Charles Binger", tooltip: "American illustrator of pulp magazines with dynamic, action-oriented scenes. Active: 1920-1950." },
  { name: "Ned Bittinger", tooltip: "American portrait and children's book illustrator with realistic, expressive style. Active: 1980-present." },
  { name: "Mary Blair", tooltip: "American artist known for modernist, colorful designs for Disney and children's books. Active: 1940-1970." },
  { name: "Quentin Blake", tooltip: "British illustrator famous for lively, sketchy ink drawings for Roald Dahl and others. Active: 1960-present." },
  { name: "Ivan Blinov", tooltip: "Russian illustrator known for detailed, historical and fantasy artwork. Active: 1990-present." },
  { name: "Cheeming Boey", tooltip: "Malaysian-American illustrator known for whimsical, humorous drawings on coffee cups. Active: 2000-present." },
  { name: "Hannes Bok", tooltip: "American fantasy and sci-fi illustrator with mystical, ornate style. Active: 1930-1960." },
  { name: "Enoch Bolles", tooltip: "American pin-up and pulp magazine illustrator known for glamorous, colorful covers. Active: 1920-1950." },
  { name: "Chesley Bonestell", tooltip: "American painter known for realistic, influential astronomical and space art. Active: 1930-1980." },
  { name: "Melinda Bordelon", tooltip: "American illustrator specializing in botanical and nature-themed art. Active: 1990-present." },
  { name: "Tom Bouden", tooltip: "Belgian comic artist and illustrator known for humorous, erotic gay-themed work. Active: 1990-present." },
  { name: "Anna Boudová Suchardová", tooltip: "Czech illustrator known for delicate, Art Nouveau-inspired children's book art. Active: 1900-1930." },
  { name: "Eleanor Vere Boyle", tooltip: "British illustrator and watercolorist known for romantic, Pre-Raphaelite style. Active: 1850-1900." },
  { name: "Syd Brak", tooltip: "American illustrator known for vibrant, psychedelic poster and album cover art. Active: 1960-1980." },
  { name: "Anna Brandoli", tooltip: "Italian illustrator known for whimsical, detailed children's book illustrations. Active: 1990-present." },
  { name: "Kaare Bratung", tooltip: "Norwegian illustrator known for humorous, caricature-style editorial drawings. Active: 1950-1990." },
  { name: "Lynn Breeze", tooltip: "British illustrator known for charming, watercolor children's book art. Active: 1970-2010." },
  { name: "Molly Brett", tooltip: "British children's book illustrator known for anthropomorphic animal scenes in soft colors. Active: 1930-1970." },
  { name: "Rae Bridgman", tooltip: "Canadian illustrator and author known for whimsical, detailed fantasy art. Active: 1990-present." },
  { name: "Raymond Briggs", tooltip: "British author-illustrator known for poignant, graphic novel-style works like The Snowman. Active: 1960-2020." },
  { name: "Pierre Brissaud", tooltip: "French illustrator known for elegant, Art Deco fashion and magazine illustrations. Active: 1910-1940." },
  { name: "Steve Brodner", tooltip: "American editorial illustrator known for sharp, satirical caricatures. Active: 1970-present." },
  { name: "Gerald Brom", tooltip: "American fantasy artist known for dark, gothic illustrations with dramatic lighting. Active: 1990-present." },
  { name: "Jason Brooks", tooltip: "British illustrator known for sleek, fashion-inspired digital art and graphics. Active: 1990-present." },
  { name: "Gordon Browne", tooltip: "British illustrator known for detailed, historical and children's book illustrations. Active: 1870-1930." },
  { name: "Hablot Knight Browne", tooltip: "British illustrator known as Phiz, famous for Dickens novel illustrations. Active: 1830-1870." },
  { name: "Margaret Brundage", tooltip: "American illustrator known for sensual, Art Deco pulp magazine covers. Active: 1930-1950." },
  { name: "René Bull", tooltip: "British illustrator known for detailed, Orientalist and historical drawings. Active: 1890-1930." },
  { name: "Nancy Ekholm Burkert", tooltip: "American illustrator known for meticulous, fairy tale illustrations with rich detail. Active: 1960-2000." },
  { name: "Mark Burrier", tooltip: "American illustrator known for dynamic, comic book and fantasy art. Active: 1990-present." },
  { name: "Priscilla Susan Bury", tooltip: "British botanical illustrator known for precise, colorful plant studies. Active: 1830-1860." },
  { name: "Sergio Burzi", tooltip: "Italian illustrator known for realistic, historical and fantasy artwork. Active: 1970-2010." },
  { name: "Matt Busch", tooltip: "American illustrator known for sci-fi and pop culture poster art. Active: 1990-present." },
  { name: "Mitch Butler", tooltip: "Known for detailed fantasy and horror illustrations with a dark, atmospheric style. Active: 1980s-present." },
  { name: "Felicity Campbell", tooltip: "Specialized in children's book illustrations with a whimsical, colorful approach. Active: 1990s-present." },
  { name: "Aldo Capitanio", tooltip: "Italian illustrator noted for dynamic comic book art and adventure scenes. Active: 1960-1990." },
  { name: "Fernando Carcupino", tooltip: "Argentine illustrator recognized for vibrant, expressive comic and editorial work. Active: 1950-1980." },
  { name: "Edd Cartier", tooltip: "Pioneering pulp magazine illustrator with a clean, imaginative science fiction style. Active: 1930-1960." },
  { name: "Chao Yat", tooltip: "Hong Kong-based illustrator known for detailed, atmospheric fantasy and game art. Active: 1990s-present." },
  { name: "Glenn Chadbourne", tooltip: "American illustrator specializing in macabre, detailed horror and dark fantasy art. Active: 1990s-present." },
  { name: "Watson Charlton", tooltip: "British illustrator of children's books with a gentle, narrative watercolor style. Active: 1920-1950." },
  { name: "Earle D. Chesney", tooltip: "American illustrator known for adventure and Western-themed pulp magazine covers. Active: 1920-1950." },
  { name: "Lauren Child", tooltip: "British author-illustrator famous for collage-like, quirky children's book illustrations. Active: 1990s-present." },
  { name: "Richard Chopping", tooltip: "British illustrator renowned for hyperrealistic, trompe-l'oeil book covers, especially for Ian Fleming. Active: 1940-1990." },
  { name: "Howard Chandler Christy", tooltip: "American illustrator famous for the 'Christy Girl,' a glamorous, idealized feminine style. Active: 1890-1950." },
  { name: "Edgar Church", tooltip: "American illustrator known for detailed, realistic adventure and historical magazine illustrations. Active: 1920-1950." },
  { name: "Fabio Civitelli", tooltip: "Italian comic book artist recognized for dynamic, action-packed historical and adventure series. Active: 1970s-present." },
  { name: "Alan M. Clark", tooltip: "American illustrator specializing in dark fantasy and horror with a painterly, evocative style. Active: 1980s-present." },
  { name: "Harry Clarke", tooltip: "Irish illustrator celebrated for intricate, Art Nouveau-inspired stained glass and book illustrations. Active: 1910-1930." },
  { name: "John Cecil Clay", tooltip: "American illustrator known for humorous, caricature-like magazine and advertising illustrations. Active: 1900-1930." },
  { name: "John Clymer", tooltip: "American illustrator famous for realistic, narrative Western and historical scenes for magazines. Active: 1930-1980." },
  { name: "Alan E. Cober", tooltip: "American illustrator noted for satirical, pen-and-ink editorial drawings and reportage art. Active: 1960-1990." },
  { name: "Ted CoConis", tooltip: "American illustrator recognized for glamorous, stylized pin-up and advertising art. Active: 1950-1980." },
  { name: "Anthony Colbert", tooltip: "British illustrator known for detailed, atmospheric fantasy and science fiction book covers. Active: 1970s-present." },
  { name: "Hedvig Collin", tooltip: "Danish illustrator of children's books with a delicate, folk art-inspired watercolor style. Active: 1920-1960." },
  { name: "Coop", tooltip: "American illustrator and painter famous for bold, retro-style hot rod and counterculture art. Active: 1990s-present." },
  { name: "Frank Cadogan Cowper", tooltip: "British painter and illustrator of the Pre-Raphaelite tradition, known for detailed historical scenes. Active: 1900-1950." },
  { name: "Kinuko Y. Craft", tooltip: "Japanese-American illustrator renowned for luminous, detailed fantasy and fairy tale paintings. Active: 1970s-present." },
  { name: "Reed Crandall", tooltip: "American comic book artist celebrated for clean, precise linework in adventure and superhero comics. Active: 1940-1970." },
  { name: "Donald Crews", tooltip: "American author-illustrator known for bold, graphic children's books about vehicles and transportation. Active: 1960s-present." },
  { name: "Max Crivello", tooltip: "Italian illustrator recognized for vibrant, dynamic comic and advertising art. Active: 1950-1980." },
  { name: "Robert Crumb", tooltip: "American cartoonist famous for detailed, satirical underground comix with a countercultural edge. Active: 1960s-present." },
  { name: "Thelma Cudlipp", tooltip: "American illustrator known for elegant, stylized fashion and magazine illustrations. Active: 1920-1950." },
  { name: "Stacy Curtis", tooltip: "American illustrator specializing in humorous, cartoon-like children's book and editorial art. Active: 1990s-present." },
  { name: "Geofrey Darrow", tooltip: "American comic book artist renowned for incredibly detailed, cyberpunk-inspired mechanical designs. Active: 1980s-present." },
  { name: "Harry Grant Dart", tooltip: "American illustrator and cartoonist known for futuristic, imaginative comic strips and editorial art. Active: 1900-1930." },
  { name: "Honoré Daumier", tooltip: "French painter and caricaturist celebrated for satirical, socially critical lithographs and drawings. Active: 1830-1870." },
  { name: "Jack Davis", tooltip: "American cartoonist famous for energetic, humorous illustrations for MAD Magazine and advertising. Active: 1950-2000." },
  { name: "Reginald Ben Davis", tooltip: "British illustrator known for detailed, atmospheric historical and adventure book illustrations. Active: 1920-1950." },
  { name: "Jane Mary Dealy", tooltip: "British illustrator of children's books with a gentle, narrative watercolor and ink style. Active: 1880-1920." },
  { name: "Adam Dechanel", tooltip: "British illustrator recognized for detailed, atmospheric fantasy and science fiction digital art. Active: 2000s-present." },
  { name: "Jason Deeble", tooltip: "Australian illustrator known for whimsical, detailed children's book and editorial illustrations. Active: 1990s-present." },
  { name: "Paul Degen", tooltip: "American illustrator and cartoonist noted for satirical, pen-and-ink editorial and children's book art. Active: 1970s-present." },
  { name: "Gertrude Degenhardt", tooltip: "German illustrator and painter known for expressive, socially engaged children's book illustrations. Active: 1960-2000." },
  { name: "Étienne Delessert", tooltip: "Swiss illustrator celebrated for surreal, imaginative children's book and editorial illustrations. Active: 1960s-present." },
  { name: "John Henry Dell", tooltip: "American illustrator known for detailed, realistic adventure and Western magazine illustrations. Active: 1900-1930." },
  { name: "Christopher Denise", tooltip: "American illustrator recognized for warm, painterly children's book illustrations with a nostalgic feel. Active: 1990s-present." },
  { name: "W.W. Denslow", tooltip: "American illustrator famous for the original artwork in 'The Wonderful Wizard of Oz,' with a bold graphic style. Active: 1880-1910." },
  { name: "Vince Deporter", tooltip: "American illustrator known for dynamic, colorful comic book and fantasy art. Active: 1980s-present." },
  { name: "Peter de Sève", tooltip: "American illustrator renowned for character-driven, whimsical drawings for The New Yorker and animation. Active: 1980s-present." },
  { name: "Ali Dilem", tooltip: "Algerian cartoonist famous for satirical, politically charged editorial cartoons. Active: 1990s-present." },
  { name: "Brad Diller", tooltip: "American illustrator specializing in detailed, atmospheric fantasy and science fiction digital art. Active: 2000s-present." },
  { name: "Leo and Diane Dillon", tooltip: "American illustrators celebrated for award-winning, culturally diverse children's book art with a unified style. Active: 1960-2010." },
  { name: "Irv Docktor", tooltip: "Known for vibrant, energetic comic book and advertising illustrations. Active: 1940s-1970s." },
  { name: "Richard Staples Dodge", tooltip: "Illustrator of children's books with detailed, whimsical scenes. Active: 1890s-1920s." },
  { name: "Angela Dominguez", tooltip: "Contemporary illustrator with a warm, expressive style for children's literature. Active: 2000s-present." },
  { name: "Franco Donatelli", tooltip: "Italian illustrator known for fantasy and science fiction art. Active: 1970s-1990s." },
  { name: "Donelan", tooltip: "American illustrator of magazine covers and advertisements. Active: 1910s-1930s." },
  { name: "Gustave Doré", tooltip: "French artist renowned for dramatic, intricate wood-engraved illustrations. Active: 1840s-1880s." },
  { name: "Denise Dorrance", tooltip: "Illustrator and cartoonist with a bold, graphic style. Active: 1990s-present." },
  { name: "Ralph Waddell Douglass", tooltip: "American illustrator of books and magazines, often with historical themes. Active: 1920s-1950s." },
  { name: "Richard Doyle", tooltip: "British illustrator known for fairy tale and fantasy drawings. Active: 1840s-1880s." },
  { name: "Roger Drew", tooltip: "Illustrator of children's books with a playful, colorful approach. Active: 1960s-1980s." },
  { name: "Edmund Dulac", tooltip: "French-born illustrator famous for lush, orientalist watercolor book illustrations. Active: 1900s-1940s." },
  { name: "Georges Dumitresco", tooltip: "Romanian illustrator of books and magazines with a classical style. Active: 1930s-1960s." },
  { name: "Frederick Melville DuMond", tooltip: "American illustrator and painter of landscapes and genre scenes. Active: 1880s-1920s." },
  { name: "Harvey Dunn", tooltip: "American illustrator and painter known for dynamic, narrative Western scenes. Active: 1900s-1950s." },
  { name: "Nicolas Eekman", tooltip: "Belgian painter and illustrator with a surrealist, symbolic style. Active: 1920s-1960s." },
  { name: "Lois Ehlert", tooltip: "American children's book author-illustrator known for bold collage art. Active: 1980s-2010s." },
  { name: "Edna Eicke", tooltip: "Illustrator of children's books and magazines in the mid-20th century. Active: 1930s-1960s." },
  { name: "Susan Einzig", tooltip: "British illustrator known for delicate, atmospheric children's book art. Active: 1950s-1980s." },
  { name: "Will Elder", tooltip: "American cartoonist, co-creator of Mad magazine's satirical, detailed style. Active: 1940s-2000s." },
  { name: "David Elliot", tooltip: "New Zealand illustrator of children's books with whimsical, detailed drawings. Active: 1990s-present." },
  { name: "Craig Elliott", tooltip: "American concept artist and illustrator for animation and film. Active: 1990s-present." },
  { name: "Gil Elvgren", tooltip: "American pin-up artist known for glamorous, idealized illustrations. Active: 1930s-1970s." },
  { name: "Ed Emberley", tooltip: "American children's book illustrator famous for simple, instructional drawing style. Active: 1960s-2010s." },
  { name: "Peter Emmerich", tooltip: "Illustrator and graphic designer with a modern, clean aesthetic. Active: 1970s-2000s." },
  { name: "Ed Emshwiller", tooltip: "American artist known for science fiction illustrations and experimental film. Active: 1950s-1980s." },
  { name: "Jack Endewelt", tooltip: "Illustrator of pulp magazines and book covers. Active: 1930s-1950s." },
  { name: "Mark English", tooltip: "American illustrator renowned for textured, painterly magazine and advertising art. Active: 1960s-2000s." },
  { name: "Maginel Wright Enright", tooltip: "American illustrator and sister of Frank Lloyd Wright, known for children's book art. Active: 1900s-1940s." },
  { name: "Otto Eppers", tooltip: "German illustrator of books and magazines with a detailed, realistic style. Active: 1890s-1920s." },
  { name: "Erté", tooltip: "Russian-born Art Deco designer and illustrator known for elegant, stylized fashion art. Active: 1910s-1980s." },
  { name: "Dulah Marie Evans", tooltip: "American illustrator and painter of children's books and magazines. Active: 1900s-1940s." },
  { name: "Carl Eytel", tooltip: "German-American illustrator known for desert landscape paintings and drawings. Active: 1890s-1920s." },
  { name: "Jules Faber", tooltip: "Australian cartoonist and illustrator for children's books and comics. Active: 1990s-present." },
  { name: "João Fahrion", tooltip: "Brazilian illustrator known for colorful, folk-inspired children's book art. Active: 1940s-1970s." },
  { name: "Frances C. Fairman", tooltip: "American illustrator of children's books and educational materials. Active: 1920s-1950s." },
  { name: "Cathie Felstead", tooltip: "British illustrator specializing in decorative, pattern-based designs for books. Active: 1980s-present." },
  { name: "Major Felten", tooltip: "Illustrator of adventure and pulp magazine covers. Active: 1920s-1940s." },
  { name: "Jules Férat", tooltip: "French illustrator known for detailed engravings in books and periodicals. Active: 1860s-1890s." },
  { name: "Nathalie Ferlut", tooltip: "French illustrator of children's books with a soft, whimsical style. Active: 1990s-present." },
  { name: "Alfons Figueras", tooltip: "Spanish cartoonist and illustrator known for humorous comic strips. Active: 1940s-1980s." },
  { name: "Rod Filbrandt", tooltip: "American illustrator of science fiction and fantasy book covers. Active: 1970s-1990s." },
  { name: "Leonard Filgate", tooltip: "Canadian illustrator of children's books and educational materials. Active: 1950s-1980s." },
  { name: "Virgil Finlay", tooltip: "American illustrator famous for intricate stipple technique in pulp magazines. Active: 1930s-1970s." },
  { name: "Steve Fiorilla", tooltip: "American illustrator known for dark fantasy and horror art. Active: 1980s-present." },
  { name: "James Montgomery Flagg", tooltip: "American illustrator best known for the 'I Want You' Uncle Sam poster. Active: 1890s-1960s." },
  { name: "Jim Flora", tooltip: "American graphic artist known for jazzy, abstract album cover illustrations. Active: 1940s-1990s." },
  { name: "René Follet", tooltip: "Belgian comic book artist and illustrator with a realistic, detailed style. Active: 1950s-2010s." },
  { name: "Mary Hallock Foote", tooltip: "American illustrator and writer known for Western frontier scenes. Active: 1870s-1920s." },
  { name: "Henry Justice Ford", tooltip: "British illustrator renowned for fairy tale and mythological book illustrations. Active: 1880s-1920s." },
  { name: "Hal Foster", tooltip: "Canadian-American cartoonist, creator of the comic strip 'Prince Valiant'. Active: 1920s-1970s." },
  { name: "Marcia Lane Foster", tooltip: "Known for detailed botanical and nature illustrations in children's books. Active: 1920s-1950s." },
  { name: "Julien Fournié", tooltip: "French fashion illustrator with elegant, fluid lines and modern haute couture focus. Active: 2000s-present." },
  { name: "Jane Frank", tooltip: "American painter and illustrator blending abstract expressionism with landscape elements. Active: 1950s-1980s." },
  { name: "Malcolm Fraser", tooltip: "Scottish illustrator noted for whimsical, detailed pen-and-ink drawings in fantasy genres. Active: 1970s-2000s." },
  { name: "Frank Frazetta", tooltip: "Iconic fantasy and comic artist known for muscular, dynamic figures and vivid colors. Active: 1940s-2010." },
  { name: "Kelly Freas", tooltip: "Prolific science fiction illustrator with expressive characters and imaginative alien designs. Active: 1950s-2005." },
  { name: "Anthony Freda", tooltip: "Contemporary editorial illustrator using satirical, collage-style imagery for political commentary. Active: 1990s-present." },
  { name: "Chandra Free", tooltip: "Comic book artist and writer with a gothic, surreal style and intricate linework. Active: 2000s-present." },
  { name: "Barbara C. Freeman", tooltip: "British children's book illustrator known for gentle watercolors and pastoral scenes. Active: 1960s-1990s." },
  { name: "Oli Frey", tooltip: "British video game and magazine illustrator, famous for vibrant, futuristic cover art. Active: 1980s-2010s." },
  { name: "Brian Froud", tooltip: "English fantasy artist specializing in faeries and mythical creatures with earthy, detailed art. Active: 1970s-present." },
  { name: "Bernie Fuchs", tooltip: "American illustrator and painter recognized for loose, impressionistic style in advertising and sports. Active: 1950s-2000s." },
  { name: "Joseph Fuchs", tooltip: "American illustrator, brother of Bernie, known for realistic figures and magazine cover work. Active: 1950s-1980s." },
  { name: "Thomas Fuchs", tooltip: "Contemporary digital illustrator with a clean, graphic style for editorial and commercial projects. Active: 2000s-present." },
  { name: "Gyo Fujikawa", tooltip: "Japanese-American children's book illustrator celebrated for multicultural, tender drawings of babies. Active: 1950s-1990s." },
  { name: "Magdalena Rosina Funck", tooltip: "German botanical illustrator noted for precise, hand-colored engravings of plants. Active: 1700s." },
  { name: "Tom Funk", tooltip: "American illustrator and cartoonist with a humorous, stylized approach for magazines and books. Active: 1950s-1980s." },
  { name: "Eva Furnari", tooltip: "Brazilian children's author and illustrator, known for playful, colorful characters and simple lines. Active: 1970s-present." },
  { name: "Wanda Gág", tooltip: "American author-illustrator of children's books, famous for black-and-white lithographs and folk tales. Active: 1920s-1946." },
  { name: "Dumitru Găleșanu", tooltip: "Romanian illustrator and painter, recognized for historical and literary scenes with dramatic lighting. Active: 1900s-1950s." },
  { name: "Hector Garrido", tooltip: "Argentine illustrator known for romantic, detailed cover art for novels and magazines. Active: 1940s-1990s." },
  { name: "Carolyn Bartlett Gast", tooltip: "American illustrator specializing in nature and wildlife art with realistic watercolor techniques. Active: 1970s-2000s." },
  { name: "Zhenya Gay", tooltip: "Russian-American illustrator of children's books, noted for delicate line drawings and whimsical animals. Active: 1920s-1950s." },
  { name: "Roman Genn", tooltip: "Contemporary American illustrator and painter, known for satirical political cartoons and portraits. Active: 1990s-present." },
  { name: "Pencho Georgiev", tooltip: "Bulgarian illustrator and comic artist, recognized for dynamic action scenes and fantasy themes. Active: 1980s-present." },
  { name: "Eddie Germano", tooltip: "American pin-up and glamour illustrator, famous for curvaceous, idealized female figures. Active: 1940s-1960s." },
  { name: "Charles Dana Gibson", tooltip: "American illustrator who created the 'Gibson Girl,' an iconic image of idealized femininity. Active: 1880s-1930s." },
  { name: "Anne Yvonne Gilbert", tooltip: "British illustrator known for intricate, decorative pen-and-ink work in fantasy and children's books. Active: 1970s-present." },
  { name: "Eric Gill", tooltip: "British sculptor, typeface designer, and illustrator, noted for clean lines and religious themes. Active: 1900s-1940." },
  { name: "Margery Gill", tooltip: "British children's book illustrator, recognized for charming, detailed drawings of rural life. Active: 1950s-1980s." },
  { name: "Willi Glasauer", tooltip: "German illustrator and caricaturist, known for humorous, exaggerated portraits and editorial art. Active: 1970s-2000s." },
  { name: "Milton Glaser", tooltip: "Influential American graphic designer and illustrator, creator of the 'I ♥ NY' logo. Active: 1950s-2020." },
  { name: "Robin Preiss Glasser", tooltip: "American illustrator famous for the 'Fancy Nancy' series, with exuberant, detailed watercolors. Active: 1990s-present." },
  { name: "Frank Godwin", tooltip: "American illustrator and comic strip artist, known for realistic pen-and-ink illustrations and adventure stories. Active: 1910s-1950s." },
  { name: "Ted Goff", tooltip: "Contemporary American illustrator specializing in humorous, cartoon-style graphics for business and education. Active: 1980s-present." },
  { name: "Fabian Göranson", tooltip: "Swedish illustrator and concept artist, noted for dark fantasy and sci-fi themes with digital painting. Active: 2000s-present." },
  { name: "Edward Gorey", tooltip: "American writer and illustrator, famous for macabre, cross-hatched drawings in gothic tales. Active: 1950s-2000." },
  { name: "Ruth Sigrid Grafstrom", tooltip: "American illustrator known for fashion and advertising art with elegant, stylized figures. Active: 1920s-1950s." },
  { name: "Carlos Grangel", tooltip: "Spanish character designer and illustrator, recognized for work on animated films with whimsical creatures. Active: 1990s-present." },
  { name: "Vernon Grant", tooltip: "American illustrator and cartoonist, creator of the 'Snap, Crackle and Pop' characters for Rice Krispies. Active: 1920s-1990." },
  { name: "Elizabeth Shippen Green", tooltip: "American illustrator, part of the 'Red Rose Girls,' known for romantic, detailed watercolor illustrations. Active: 1890s-1950s." },
  { name: "Kate Greenaway", tooltip: "English children's book illustrator, celebrated for idyllic, pastoral scenes and distinctive costume designs. Active: 1870s-1901." },
  { name: "Rebecca Guay", tooltip: "American fantasy illustrator, known for ethereal, painterly style in Magic: The Gathering cards. Active: 1990s-present." },
  { name: "Shekhar Gurera", tooltip: "Indian illustrator and visual artist, recognized for vibrant, narrative-driven illustrations in media. Active: 2000s-present." },
  { name: "Vee Guthrie", tooltip: "American illustrator specializing in children's books with soft, colorful watercolors and friendly characters. Active: 1970s-2000s." },
  { name: "Dick Hafer", tooltip: "American illustrator known for pulp magazine covers and adventure art with bold compositions. Active: 1930s-1960s." },
  { name: "Michael Hague", tooltip: "American children's book illustrator, famous for richly detailed, romantic fantasy illustrations. Active: 1970s-present." },
  { name: "Bob Hall", tooltip: "American comic book artist and illustrator, known for superhero work and dynamic storytelling. Active: 1970s-2000s." },
  { name: "Marcellus Hall", tooltip: "American illustrator and cartoonist, recognized for witty, graphic illustrations in The New Yorker. Active: 1990s-present." },
  { name: "Baron Barrymore Halpenny", tooltip: "British illustrator and aviation artist, noted for detailed technical drawings of aircraft. Active: 1950s-1990s." },
  { name: "Clifford Harper", tooltip: "British illustrator known for anarchist woodcut and linocut prints. Active: 1970s-present." },
  { name: "Jim Harris", tooltip: "American illustrator specializing in humorous, detailed fantasy and children's book art. Active: 1980s-present." },
  { name: "Steven Harris", tooltip: "American illustrator recognized for vibrant, surreal digital and traditional fantasy art. Active: 1990s-present." },
  { name: "Ernest William Haslehust", tooltip: "British watercolorist known for picturesque landscapes and rural scenes. Active: 1890-1949." },
  { name: "Catherine Haussard", tooltip: "French illustrator noted for delicate, whimsical children's book illustrations. Active: 1990s-present." },
  { name: "Elisabeth Haussard", tooltip: "French illustrator celebrated for elegant, narrative-driven botanical and fantasy art. Active: 1990s-present." },
  { name: "Adam Heller", tooltip: "American illustrator known for bold, graphic editorial and advertising artwork. Active: 1980s-present." },
  { name: "Ruth Heller", tooltip: "American author-illustrator famous for colorful, educational children's books on nature. Active: 1970s-2004." },
  { name: "Danny Hellman", tooltip: "American illustrator recognized for satirical, edgy comic and editorial illustrations. Active: 1980s-present." },
  { name: "Brett Helquist", tooltip: "American illustrator best known for detailed, gothic-style art in Lemony Snicket books. Active: 1990s-present." },
  { name: "Andrew Kennaway Henderson", tooltip: "New Zealand illustrator noted for natural history and botanical watercolors. Active: 1920-1970." },
  { name: "Joseph Morgan Henninger", tooltip: "American illustrator known for dynamic, realistic pulp magazine and adventure art. Active: 1930-1960." },
  { name: "Cornelia Hesse-Honegger", tooltip: "Swiss scientific illustrator famous for detailed watercolors of mutated insects. Active: 1960s-present." },
  { name: "Don Hewitt", tooltip: "American illustrator recognized for clean, modernist editorial and advertising designs. Active: 1950-1980." },
  { name: "Don Hillsman II", tooltip: "American illustrator known for vibrant, Afrocentric digital and traditional art. Active: 1990s-present." },
  { name: "Henry Hintermeister", tooltip: "American illustrator celebrated for nostalgic, detailed scenes of American family life. Active: 1890-1945." },
  { name: "John Henry Hintermeister", tooltip: "American illustrator known for romanticized historical and genre paintings. Active: 1870-1945." },
  { name: "Walter Haskell Hinton", tooltip: "American illustrator noted for realistic aviation and wartime poster art. Active: 1910-1950." },
  { name: "Jessica Hische", tooltip: "American lettering artist and illustrator famous for ornate, vintage-inspired typography. Active: 2000s-present." },
  { name: "Susie Hodge", tooltip: "British author-illustrator known for accessible, educational art history and craft books. Active: 1990s-present." },
  { name: "Dick Hodgins Jr.", tooltip: "American cartoonist recognized for humorous, character-driven editorial cartoons. Active: 1950-2000." },
  { name: "Rosekrans Hoffman", tooltip: "American illustrator known for whimsical, colorful children's book and magazine art. Active: 1920-1960." },
  { name: "William Hogarth", tooltip: "English painter and printmaker famous for satirical, narrative moral works. Active: 1720-1764." },
  { name: "Hokusai", tooltip: "Japanese ukiyo-e artist renowned for dynamic woodblock prints like The Great Wave. Active: 1779-1849." },
  { name: "Brad Holland", tooltip: "American illustrator celebrated for surreal, painterly editorial and book art. Active: 1970s-present." },
  { name: "Nicole Hollander", tooltip: "American cartoonist known for witty, feminist comic strip Sylvia. Active: 1970s-present." },
  { name: "Holling C. Holling", tooltip: "American author-illustrator famous for detailed, educational children's geography books. Active: 1920-1973." },
  { name: "Edgar Alfred Holloway", tooltip: "British illustrator noted for etchings and portraits of literary figures. Active: 1910-1980." },
  { name: "Winslow Homer", tooltip: "American painter and illustrator renowned for realistic marine and rural scenes. Active: 1857-1910." },
  { name: "Jeff Hook", tooltip: "American illustrator known for vibrant, graphic fantasy and science fiction art. Active: 1980s-present." },
  { name: "Daniel Horne", tooltip: "American illustrator recognized for detailed, atmospheric fantasy and horror book covers. Active: 1980s-present." },
  { name: "James Horvath", tooltip: "American illustrator known for humorous, cartoonish children's book and character art. Active: 1990s-present." },
  { name: "John Howe", tooltip: "Canadian illustrator famous for epic, detailed fantasy art for Tolkien works. Active: 1980s-present." },
  { name: "Mentor Huebner", tooltip: "American illustrator noted for realistic, dramatic pulp magazine and adventure covers. Active: 1930-1960." },
  { name: "David Hughes", tooltip: "British illustrator known for dark, satirical pen-and-ink editorial drawings. Active: 1980s-present." },
  { name: "Debbie Hughes", tooltip: "American illustrator recognized for colorful, whimsical children's book and greeting card art. Active: 1990s-present." },
  { name: "Rian Hughes", tooltip: "British designer and illustrator famous for retro-futuristic typography and comic art. Active: 1980s-present." },
  { name: "Jim Hummel", tooltip: "American cartoonist known for humorous, slice-of-life comic strip Hummel. Active: 1970s-present." },
  { name: "Barry Hunau", tooltip: "American illustrator noted for realistic, detailed wildlife and natural history art. Active: 1970s-present." },
  { name: "Robert Hunt", tooltip: "American illustrator celebrated for vibrant, narrative fantasy and science fiction art. Active: 1980s-present." },
  { name: "Trina Schart Hyman", tooltip: "American illustrator famous for detailed, folkloric children's book illustrations. Active: 1960-2004." },
  { name: "Robert Ingpen", tooltip: "Australian illustrator renowned for detailed, atmospheric watercolors of fantasy and classics. Active: 1960s-present." },
  { name: "Koji Ishikawa", tooltip: "Japanese illustrator known for cute, character-driven manga and children's book art. Active: 1990s-present." },
  { name: "Robin Jacques", tooltip: "British illustrator noted for intricate, cross-hatched pen-and-ink fairy tale art. Active: 1940-1995." },
  { name: "Al Jaffee", tooltip: "American cartoonist famous for inventive Mad Magazine folds-ins and satire. Active: 1940s-2020." },
  { name: "Jago", tooltip: "British illustrator known for bold, graphic digital art for video games and books. Active: 2000s-present." },
  { name: "Zoran Janjetov", tooltip: "Serbian comic artist recognized for detailed, surreal science fiction illustrations. Active: 1980s-present." },
  { name: "Kirk Jarvinen", tooltip: "American illustrator noted for realistic, dramatic fantasy and role-playing game art. Active: 1990s-present." },
  { name: "James Jean", tooltip: "Taiwanese-American illustrator famous for ethereal, intricate painterly and comic art. Active: 2000s-present." },
  { name: "Aurélien Jeanney", tooltip: "French illustrator known for vibrant, narrative-driven digital fantasy and concept art. Active: 2000s-present." },
  { name: "Oliver Jeffers", tooltip: "Whimsical, minimalist style with hand-lettered text. Active: 2000s-present." },
  { name: "Alfred Garth Jones", tooltip: "Detailed Art Nouveau and fantasy illustrations. Active: 1890s-1920s." },
  { name: "Eddie Jones", tooltip: "Known for dynamic, action-oriented comic book art. Active: 1970s-2000s." },
  { name: "G. B. Jones", tooltip: "Punk and queer zine aesthetics with a DIY feel. Active: 1980s-present." },
  { name: "Patrick J. Jones", tooltip: "Realistic fantasy and sci-fi art with dramatic lighting. Active: 1990s-present." },
  { name: "Piet de Jong", tooltip: "Archaeological illustrator known for precise reconstructions. Active: 1920s-1960s." },
  { name: "Federico Jordan", tooltip: "Vibrant, stylized illustrations often for children's books. Active: 2000s-present." },
  { name: "Ingrīda Kadaka", tooltip: "Latvian illustrator with folk art influences and bold colors. Active: 1970s-2000s." },
  { name: "Arja Kajermo", tooltip: "Swedish illustrator with a dark, surreal and humorous style. Active: 1990s-present." },
  { name: "Maira Kalman", tooltip: "Naive, colorful paintings with witty observational text. Active: 1980s-present." },
  { name: "Jack Kamen", tooltip: "Clean-lined, often romantic or humorous comic and advertising art. Active: 1940s-1980s." },
  { name: "Avi Katz", tooltip: "Israeli illustrator with a loose, expressive ink and watercolor style. Active: 1970s-present." },
  { name: "Cosei Kawa", tooltip: "Japanese illustrator with a soft, dreamlike and whimsical aesthetic. Active: 2000s-present." },
  { name: "Charles Keeping", tooltip: "Powerful, atmospheric line drawings, often for historical subjects. Active: 1950s-1980s." },
  { name: "Jack Kent", tooltip: "Simple, cartoonish style for humorous children's books. Active: 1960s-1980s." },
  { name: "Dóra Keresztes", tooltip: "Hungarian illustrator with intricate, pattern-filled folk-inspired art. Active: 2010s-present." },
  { name: "Charles Kerins", tooltip: "American commercial artist known for bold poster and advertising design. Active: 1930s-1960s." },
  { name: "Kazu Kibuishi", tooltip: "Creator of Amulet; cinematic, detailed graphic novel art. Active: 2000s-present." },
  { name: "J. D. King", tooltip: "Fantasy illustrator with a painterly, often dark and mystical style. Active: 1990s-present." },
  { name: "Wyncie King", tooltip: "Puck magazine cartoonist known for satirical pen-and-ink drawings. Active: 1900s-1930s." },
  { name: "Josh Kirby", tooltip: "British artist known for chaotic, detailed cover art for Terry Pratchett. Active: 1950s-2001." },
  { name: "Cem Kızıltuğ", tooltip: "Turkish illustrator with a vibrant, graphic and often surreal style. Active: 2000s-present." },
  { name: "Hilary Knight", tooltip: "Elegant, lively line work, best known for Eloise. Active: 1950s-present." },
  { name: "Lucy Knisley", tooltip: "Autobiographical comics with a clean, expressive and heartfelt style. Active: 2000s-present." },
  { name: "Shahar Kober", tooltip: "Israeli illustrator with a warm, textured and character-driven style. Active: 2000s-present." },
  { name: "E. L. Konigsburg", tooltip: "Author-illustrator with precise, thoughtful pen-and-ink drawings. Active: 1960s-2010s." },
  { name: "Ben Krefta", tooltip: "British illustrator known for detailed, imaginative fantasy scenes. Active: 1990s-present." },
  { name: "Roy Krenkel", tooltip: "Influential fantasy artist with a dynamic, sketchy ink style. Active: 1950s-1980s." },
  { name: "Andrea Kruis", tooltip: "German illustrator known for humorous, cartoon-style children's books. Active: 1980s-present." },
  { name: "Anita Kunz", tooltip: "Satirical and conceptual illustrations with a painterly, sophisticated style. Active: 1970s-present." },
  { name: "Agi Lamm", tooltip: "Hungarian-born illustrator of delicate, decorative fashion and fairy-tale art. Active: 1920s-1960s." },
  { name: "Yvette Lapointe", tooltip: "Canadian illustrator with a soft, colorful and whimsical style. Active: 1970s-2000s." },
  { name: "Antonio Lara de Gavilán", tooltip: "Spanish illustrator known for detailed historical and fantasy scenes. Active: 1970s-2000s." },
  { name: "Philippe Lardy", tooltip: "Swiss illustrator with a clean, graphic and often architectural style. Active: 1980s-present." },
  { name: "Kivi Larmola", tooltip: "Finnish illustrator with a bold, graphic and often humorous style. Active: 1970s-2000s." },
  { name: "Abigail Larson", tooltip: "Gothic and whimsical illustrations with a delicate, inky style. Active: 2000s-present." },
  { name: "Paul Laune", tooltip: "American illustrator known for rugged, realistic Western and adventure scenes. Active: 1920s-1950s." },
  { name: "Rick Law", tooltip: "Concept artist for animation, known for dynamic, stylized character designs. Active: 1990s-present." },
  { name: "John Lawrence", tooltip: "British wood engraver with a robust, traditional illustrative style. Active: 1960s-present." },
  { name: "Edward Lear", tooltip: "Nonsense verse illustrator with quirky, detailed pen drawings. Active: 1830s-1880s." },
  { name: "Alan Lee", tooltip: "Ethereal, watercolor-based fantasy art, notably for Tolkien. Active: 1970s-present." },
  { name: "Suzy Lee", tooltip: "Korean illustrator known for innovative, wordless picture books. Active: 2000s-present." },
  { name: "John Leech", tooltip: "Victorian caricaturist and illustrator for Punch and Dickens. Active: 1840s-1860s." },
  { name: "Alfred Leete", tooltip: "British graphic artist, creator of the iconic 'Lord Kitchener' poster. Active: 1900s-1930s." },
  { name: "João M. P. Lemos", tooltip: "Portuguese illustrator with a detailed, often historical or architectural focus. Active: 1970s-2000s." },
  { name: "Lois Lenski", tooltip: "American author-illustrator known for regionalist, documentary-style drawings. Active: 1920s-1970s." },
  { name: "Olive Leonhardt", tooltip: "British illustrator of children's books with a gentle, decorative style. Active: 1920s-1950s." },
  { name: "Cecil Mary Leslie", tooltip: "British illustrator known for charming, detailed animal and fairy drawings. Active: 1920s-1960s." },
  { name: "Michael Leunig", tooltip: "Australian cartoonist with a simple, philosophical and whimsical line. Active: 1960s-present." },
  { name: "Celia Levetus", tooltip: "British illustrator and stained-glass designer with an Arts and Crafts style. Active: 1890s-1920s." },
  { name: "Harris Levey", tooltip: "Known for detailed narrative illustrations in children's books. Active: 1950-1980." },
  { name: "Arnold Levin", tooltip: "Specialized in vibrant, whimsical illustrations for educational publications. Active: 1960-1990." },
  { name: "Thomas Noyes Lewis", tooltip: "Produced elegant, detailed illustrations for magazines and advertisements. Active: 1890-1920." },
  { name: "J. C. Leyendecker", tooltip: "Iconic American illustrator known for bold, idealized figures and advertising art. Active: 1896-1951." },
  { name: "Kenneth Norman Lilly", tooltip: "British wildlife illustrator celebrated for precise, lifelike animal depictions. Active: 1930-1970." },
  { name: "Selena Lin", tooltip: "Contemporary illustrator blending traditional Chinese and modern digital techniques. Active: 2000-present." },
  { name: "Oleg Lipchenko", tooltip: "Ukrainian-Canadian illustrator known for intricate, surreal pen-and-ink works. Active: 1990-present." },
  { name: "Virginio Livraghi", tooltip: "Italian illustrator recognized for dynamic, colorful comic and advertising art. Active: 1950-1980." },
  { name: "Andrew Loomis", tooltip: "Influential American illustrator and author known for figure drawing and instructional books. Active: 1920-1959." },
  { name: "Rafael Lopez", tooltip: "Mexican-American illustrator celebrated for vibrant, culturally rich children's book art. Active: 1990-present." },
  { name: "Félix Lorioux", tooltip: "French illustrator known for delicate, whimsical watercolors in children's literature. Active: 1900-1960." },
  { name: "Frederick Lowenheim", tooltip: "German illustrator specializing in detailed, atmospheric historical and fantasy scenes. Active: 1880-1920." },
  { name: "Lubov", tooltip: "Russian illustrator noted for expressive, folk art-inspired children's book illustrations. Active: 1970-2000." },
  { name: "Miel Prudencio Ma", tooltip: "Filipino illustrator known for vibrant, narrative-driven digital and traditional art. Active: 2010-present." },
  { name: "Annette Macarthur-Onslow", tooltip: "Australian illustrator recognized for detailed botanical and wildlife watercolors. Active: 1960-2000." },
  { name: "David W. Mack", tooltip: "American comic book artist and painter known for mixed-media, abstract storytelling. Active: 1990-present." },
  { name: "Robert Maguire", tooltip: "American pulp and paperback cover artist known for dramatic, noir-style illustrations. Active: 1950-1990." },
  { name: "Matt Mahurin", tooltip: "American illustrator and filmmaker noted for dark, surreal mixed-media works. Active: 1980-present." },
  { name: "Gorg Mallia", tooltip: "Maltese illustrator and educator known for satirical, socially conscious cartoon art. Active: 1990-present." },
  { name: "Mark Marderosian", tooltip: "American illustrator celebrated for colorful, character-driven children's book art. Active: 1980-present." },
  { name: "Marcel Marlier", tooltip: "Belgian illustrator famous for the 'Martine' series, featuring gentle, detailed watercolors. Active: 1950-2010." },
  { name: "Michael Martchenko", tooltip: "Canadian illustrator known for lively, humorous art in children's books like 'The Paper Bag Princess'. Active: 1980-present." },
  { name: "Antoinette Martignoni", tooltip: "Italian illustrator recognized for elegant, fashion-inspired drawings and advertisements. Active: 1920-1960." },
  { name: "Emily Winfield Martin", tooltip: "American illustrator and author known for dreamy, vintage-style children's book art. Active: 2000-present." },
  { name: "Felix Mas", tooltip: "Spanish painter and illustrator celebrated for sensual, Art Deco-inspired female figures. Active: 1960-present." },
  { name: "Fortunino Matania", tooltip: "Italian illustrator renowned for highly detailed, realistic historical and wartime scenes. Active: 1900-1960." },
  { name: "David Burroughs Mattingly", tooltip: "American science fiction and fantasy illustrator known for atmospheric, detailed cover art. Active: 1970-2010." },
  { name: "Steve Mattsson", tooltip: "Swedish illustrator specializing in dynamic, colorful comic and graphic novel art. Active: 1990-present." },
  { name: "Tatyana Mavrina", tooltip: "Russian illustrator and painter known for vibrant, folk art-inspired children's book illustrations. Active: 1920-1990." },
  { name: "John Alan Maxwell", tooltip: "American illustrator recognized for dramatic, realistic pulp magazine and book covers. Active: 1920-1960." },
  { name: "Mercer Mayer", tooltip: "American author-illustrator famous for the 'Little Critter' series, featuring whimsical, detailed art. Active: 1960-present." },
  { name: "James Mayhew", tooltip: "British illustrator and author known for lyrical, narrative-driven children's book illustrations. Active: 1980-present." },
  { name: "Angus McBride", tooltip: "British historical illustrator celebrated for meticulously researched, dynamic military scenes. Active: 1970-2007." },
  { name: "Winsor McCay", tooltip: "Pioneering American cartoonist and animator known for 'Little Nemo' and intricate, surreal art. Active: 1898-1934." },
  { name: "Jeff McComsey", tooltip: "American comic book artist and writer known for gritty, action-oriented graphic novels. Active: 2000-present." },
  { name: "James E. McConnell", tooltip: "American illustrator specializing in detailed, realistic aviation and technical art. Active: 1950-1990." },
  { name: "Jerry McDaniel", tooltip: "American illustrator recognized for vibrant, cartoon-style advertising and children's art. Active: 1960-2000." },
  { name: "Jim McDermott", tooltip: "American illustrator known for humorous, caricature-style editorial and comic art. Active: 1970-2010." },
  { name: "Thomas McIlvaine", tooltip: "American illustrator celebrated for detailed, romanticized historical and genre scenes. Active: 1870-1910." },
  { name: "Craig McKay", tooltip: "American illustrator specializing in dynamic, colorful fantasy and science fiction art. Active: 1980-present." },
  { name: "Dave McKean", tooltip: "British illustrator and filmmaker known for mixed-media, surreal art in comics like 'Sandman'. Active: 1980-present." },
  { name: "David McKee", tooltip: "British author-illustrator famous for 'Elmer the Patchwork Elephant', featuring bold, colorful art. Active: 1960-present." },
  { name: "Shawn McManus", tooltip: "American comic book artist known for expressive, detailed work on titles like 'The Sandman'. Active: 1980-present." },
  { name: "Lilian Marguerite Medland", tooltip: "British-Australian illustrator celebrated for precise, scientific bird and wildlife drawings. Active: 1910-1950." },
  { name: "Will G. Mein", tooltip: "American illustrator recognized for humorous, caricature-style editorial and advertising art. Active: 1920-1960." },
  { name: "Farshid Mesghali", tooltip: "Iranian illustrator and animator known for minimalist, poetic children's book art. Active: 1960-present." },
  { name: "David Messer", tooltip: "American illustrator specializing in realistic, detailed portrait and historical art. Active: 1970-2010." },
  { name: "Ken Messer", tooltip: "American illustrator known for vibrant, cartoon-style advertising and children's book art. Active: 1950-1990." },
  { name: "Florence Meyerheim", tooltip: "German illustrator recognized for delicate, Art Nouveau-inspired book illustrations. Active: 1900-1930." },
  { name: "Ronald Michaud", tooltip: "American illustrator celebrated for dramatic, realistic paperback and magazine cover art. Active: 1960-2000." },
  { name: "Yevgeniy Migunov", tooltip: "Soviet-era illustrator known for detailed, realistic children's book art. Active: 1960-1990." },
  { name: "H. R. Millar", tooltip: "British illustrator of fantasy and adventure with detailed, atmospheric scenes. Active: 1880-1940." },
  { name: "Mr Bingo", tooltip: "Contemporary British illustrator with a bold, humorous, and often irreverent style. Active: 2000-present." },
  { name: "Fanny Elizabeth de Mole", tooltip: "Australian botanical illustrator known for precise, scientific watercolor renderings. Active: 1860-1900." },
  { name: "Tim Molloy", tooltip: "Australian illustrator with a quirky, graphic style often featuring surreal characters. Active: 1990-present." },
  { name: "Chris Monroe", tooltip: "American illustrator known for whimsical, folk art-inspired children's book illustrations. Active: 1990-present." },
  { name: "Jeanne Montbaston", tooltip: "French medieval illuminator known for vibrant, detailed manuscript illustrations. Active: 1340-1360." },
  { name: "Jacqui Morgan", tooltip: "British illustrator specializing in detailed, nature-inspired watercolor and ink work. Active: 1970-2010." },
  { name: "Barry Moser", tooltip: "American wood engraver and illustrator known for dramatic, high-contrast biblical and literary scenes. Active: 1970-present." },
  { name: "Colonel Moutarde", tooltip: "Contemporary French illustrator with a retro, pop art style and bold colors. Active: 2010-present." },
  { name: "Alfons Mucha", tooltip: "Czech Art Nouveau master known for elegant, decorative posters with flowing lines. Active: 1880-1930." },
  { name: "Salvatore Murdocca", tooltip: "American children's book illustrator with a lively, cartoonish style. Active: 1980-present." },
  { name: "Kelly Murphy", tooltip: "American illustrator known for atmospheric, narrative-driven children's book art. Active: 2000-present." },
  { name: "Namboothiri", tooltip: "Indian illustrator renowned for traditional Kerala mural-style paintings. Active: 1950-1990." },
  { name: "Gogu Neagoe", tooltip: "Romanian illustrator known for detailed, folk art-inspired children's book illustrations. Active: 1960-2000." },
  { name: "Kadir Nelson", tooltip: "American painter and illustrator celebrated for powerful, realistic depictions of African American history. Active: 1990-present." },
  { name: "Barbara Nessim", tooltip: "American illustrator and digital artist known for feminist, pop art-inspired works. Active: 1960-present." },
  { name: "Vicky Newman", tooltip: "British illustrator specializing in delicate, nature-themed watercolor and ink drawings. Active: 1980-2020." },
  { name: "Victo Ngai", tooltip: "Contemporary illustrator known for intricate, pattern-rich digital art with Asian influences. Active: 2010-present." },
  { name: "Kay Nielsen", tooltip: "Danish illustrator of fairy tales with ethereal, Art Nouveau-influenced style. Active: 1900-1950." },
  { name: "Christoph Niemann", tooltip: "German illustrator and graphic designer known for clever, conceptual visual metaphors. Active: 1990-present." },
  { name: "Adam Niklewicz", tooltip: "Polish-American illustrator with a surreal, detailed pen-and-ink style. Active: 1980-present." },
  { name: "Ignacio Noe", tooltip: "Argentine illustrator known for bold, graphic linocut and woodcut prints. Active: 1960-2000." },
  { name: "Violet Oakley", tooltip: "American muralist and illustrator known for allegorical, Renaissance-inspired works. Active: 1890-1960." },
  { name: "John O'Carroll", tooltip: "Irish illustrator specializing in humorous, cartoon-style editorial drawings. Active: 1970-2010." },
  { name: "Alan Odle", tooltip: "British illustrator of the 1920s known for grotesque, satirical pen-and-ink drawings. Active: 1910-1940." },
  { name: "Elena Odriozola", tooltip: "Spanish illustrator with a delicate, minimalist style using soft colors and clean lines. Active: 1990-present." },
  { name: "Power O'Malley", tooltip: "American illustrator known for dynamic, action-packed comic and adventure art. Active: 1930-1970." },
  { name: "Glen Orbik", tooltip: "American illustrator renowned for pulp-style pin-up and noir cover art. Active: 1990-2015." },
  { name: "István Orosz", tooltip: "Hungarian graphic artist known for anamorphic and optical illusion illustrations. Active: 1970-present." },
  { name: "Emre Ozdemir", tooltip: "Turkish illustrator with a vibrant, contemporary digital art style. Active: 2010-present." },
  { name: "Sidney Paget", tooltip: "British illustrator famous for defining the visual image of Sherlock Holmes. Active: 1880-1908." },
  { name: "Walter Paget", tooltip: "British illustrator known for historical and adventure book illustrations. Active: 1880-1930." },
  { name: "Gaman Palem", tooltip: "Indian illustrator known for traditional Kalamkari textile-inspired narrative art. Active: 1950-1990." },
  { name: "John Jude Palencar", tooltip: "American fantasy illustrator known for dark, atmospheric book cover art. Active: 1980-present." },
  { name: "Fung Chin Pang", tooltip: "Hong Kong illustrator specializing in detailed, traditional Chinese ink painting styles. Active: 1960-2000." },
  { name: "William Papas", tooltip: "South African illustrator and cartoonist known for satirical, line-drawing political cartoons. Active: 1950-1990." },
  { name: "Roberto Parada", tooltip: "Chilean illustrator known for vibrant, surreal digital art and comic book styles. Active: 1990-present." },
  { name: "Eric Parker", tooltip: "British illustrator of mid-20th century known for detailed, realistic aviation and technical art. Active: 1930-1970." },
  { name: "Peter Parnall", tooltip: "American illustrator celebrated for minimalist, nature-themed children's book art. Active: 1960-2010." },
  { name: "Maxfield Parrish", tooltip: "American painter and illustrator known for luminous, idyllic fantasy scenes. Active: 1890-1960." },
  { name: "Dave Pascal", tooltip: "American illustrator known for bold, graphic poster and advertising art. Active: 1970-2010." },
  { name: "Alan Stuart Paterson", tooltip: "Scottish illustrator known for detailed, humorous cartoon and caricature work. Active: 1930-1970." },
  { name: "Frank R. Paul", tooltip: "American illustrator famous for pioneering, imaginative science fiction cover art. Active: 1910-1960." },
  { name: "C. F. Payne", tooltip: "American illustrator known for caricature-style portraits with textured, painterly effects. Active: 1970-present." },
  { name: "Bob Peak", tooltip: "American illustrator renowned for dynamic, colorful movie poster and advertising art. Active: 1950-1990." },
  { name: "Mervyn Peake", tooltip: "British writer and illustrator known for grotesque, detailed pen drawings of fantasy worlds. Active: 1930-1960." },
  { name: "Susan Beatrice Pearse", tooltip: "British illustrator of children's books with delicate, watercolor floral and nature scenes. Active: 1890-1930." },
  { name: "Clara Elsene Peck", tooltip: "American illustrator known for romantic, idealized depictions of women and children. Active: 1900-1940." },
  { name: "Thomas Mitchell Peirce", tooltip: "American illustrator specializing in detailed, realistic historical and genre scenes. Active: 1870-1910." },
  { name: "Bob Penuelas", tooltip: "Known for dynamic skateboard and surf culture illustrations with bold lines. Active: 1990s-present." },
  { name: "Laura Pérez Vernetti", tooltip: "Spanish illustrator blending surrealism and pop art in graphic novels. Active: 1990s-present." },
  { name: "Domingo F. Periconi", tooltip: "Italian-American illustrator of pulp magazine covers with dramatic scenes. Active: 1920s-1940s." },
  { name: "Rosa C. Petherick", tooltip: "British illustrator of children's books with delicate watercolor scenes. Active: 1890s-1910s." },
  { name: "Keats Petree", tooltip: "American illustrator known for whimsical, folk art-inspired children's books. Active: 1990s-present." },
  { name: "Valerie Petts", tooltip: "British illustrator of children's books with gentle, pastoral watercolor style. Active: 1970s-2000s." },
  { name: "Mary Petty", tooltip: "American cartoonist for The New Yorker, depicting upper-class satire. Active: 1920s-1960s." },
  { name: "S. D. Phadnis", tooltip: "Indian illustrator known for mythological and historical book art. Active: 1950s-1980s." },
  { name: "LeUyen Pham", tooltip: "Vietnamese-American illustrator of children's books with vibrant, expressive characters. Active: 2000s-present." },
  { name: "Craig Phillips", tooltip: "New Zealand illustrator with bold, graphic fantasy and sci-fi art. Active: 2000s-present." },
  { name: "Françoise Pichard", tooltip: "French illustrator of children's books with soft, dreamlike watercolors. Active: 1970s-2000s." },
  { name: "André Pijet", tooltip: "Polish-French illustrator known for Art Deco posters and fashion designs. Active: 1920s-1950s." },
  { name: "Brian Pilkington", tooltip: "Icelandic illustrator of folk tales with detailed, whimsical ink drawings. Active: 1980s-present." },
  { name: "Rose M. M. Pitman", tooltip: "British illustrator of botanical and nature subjects in watercolor. Active: 1880s-1910s." },
  { name: "Hanoch Piven", tooltip: "Israeli illustrator creating portraits from everyday objects in collage. Active: 1990s-present." },
  { name: "George Wolfe Plank", tooltip: "American illustrator known for elegant fashion and advertising art. Active: 1910s-1940s." },
  { name: "Willy Pogany", tooltip: "Hungarian-American illustrator of fantasy with ornate, mythological themes. Active: 1900s-1950s." },
  { name: "Beatrix Potter", tooltip: "British author-illustrator of children's books with delicate watercolor animals. Active: 1890s-1940s." },
  { name: "Richard M. Powers", tooltip: "American illustrator of sci-fi covers with surreal, abstract imagery. Active: 1950s-1980s." },
  { name: "Ernest Prater", tooltip: "British illustrator of adventure and historical novels with detailed scenes. Active: 1920s-1950s." },
  { name: "Michael Mathias Prechtl", tooltip: "German illustrator known for satirical and political caricatures. Active: 1950s-2000s." },
  { name: "Alice and Martin Provensen", tooltip: "American illustrators of children's books with stylized, folk art scenes. Active: 1940s-1980s." },
  { name: "Howard Pyle", tooltip: "American illustrator and teacher, known for historical and adventure art. Active: 1870s-1910s." },
  { name: "Rosane Quintella", tooltip: "Brazilian illustrator of children's books with colorful, playful characters. Active: 1990s-present." },
  { name: "Arthur Rackham", tooltip: "British illustrator of fairy tales with intricate, gothic pen-and-ink work. Active: 1890s-1930s." },
  { name: "Arifur Rahman", tooltip: "Bangladeshi cartoonist and illustrator known for satirical social commentary. Active: 2000s-present." },
  { name: "Alberto Rapisarda", tooltip: "Italian illustrator of children's books with bright, cartoonish style. Active: 1970s-2000s." },
  { name: "Chris Raschka", tooltip: "American illustrator of children's books with loose, expressive watercolors. Active: 1990s-present." },
  { name: "Walter Ratterman", tooltip: "American illustrator of magazine covers and advertisements in realistic style. Active: 1910s-1940s." },
  { name: "Barb Rausch", tooltip: "American illustrator known for fantasy and role-playing game art. Active: 1980s-2000s." },
  { name: "Leonard Raven-Hill", tooltip: "British cartoonist and illustrator for Punch, with satirical pen drawings. Active: 1890s-1930s." },
  { name: "Else Raydt", tooltip: "German illustrator of children's books with gentle, narrative watercolors. Active: 1900s-1930s." },
  { name: "Gardner Rea", tooltip: "American cartoonist for The New Yorker, known for humorous single-panel gags. Active: 1920s-1960s." },
  { name: "Mary A. Reardon", tooltip: "American illustrator of children's educational books with clear, engaging art. Active: 1950s-1980s." },
  { name: "Ralph Reese", tooltip: "American comic book and fantasy illustrator with dynamic, detailed style. Active: 1970s-2000s." },
  { name: "Marlene Reidel", tooltip: "German illustrator of children's books with soft, fairy-tale watercolors. Active: 1950s-1990s." },
  { name: "Charles M. Relyea", tooltip: "American illustrator of posters and advertisements in Art Nouveau style. Active: 1890s-1920s." },
  { name: "Emma Rendel", tooltip: "Swedish illustrator and cartoonist known for dark, surreal graphic novels. Active: 2000s-present." },
  { name: "Sarah Rhodes", tooltip: "British illustrator of botanical and natural history subjects in watercolor. Active: 1840s-1870s." },
  { name: "Renée Rienties", tooltip: "Dutch illustrator of children's books with whimsical, colorful characters. Active: 1950s-1980s." },
  { name: "Robert Riger", tooltip: "American illustrator and photographer known for dynamic sports art. Active: 1950s-1990s." },
  { name: "Elizabeth Rivers", tooltip: "British illustrator and printmaker with modernist, woodcut style. Active: 1930s-1960s." },
  { name: "David Roberts", tooltip: "Scottish illustrator of historical and architectural subjects with detailed accuracy. Active: 1820s-1860s." },
  { name: "Albert Robida", tooltip: "French illustrator and futurist, depicting imaginative technological scenes. Active: 1860s-1920s." },
  { name: "Heath Robinson", tooltip: "British cartoonist known for absurdly complex contraptions in pen drawings. Active: 1900s-1940s." },
  { name: "Christine Roche", tooltip: "British illustrator of children's books with humorous, cartoon-like style. Active: 1970s-2000s." },
  { name: "Norman Rockwell", tooltip: "American illustrator famous for idealized, narrative scenes of everyday life. Active: 1910s-1970s." },
  { name: "Laura Rodig", tooltip: "Chilean illustrator and painter with expressive, modernist figurative art. Active: 1920s-1970s." },
  { name: "Spain Rodriguez", tooltip: "American underground comix illustrator known for gritty, political themes. Active: 1960s-2010s." },
  { name: "Lucinda Rogers", tooltip: "British illustrator known for observational drawings of urban life in ink. Active: 1990s-present." },
  { name: "Valentina Romeo", tooltip: "Contemporary illustrator known for vibrant, whimsical digital art with fantasy themes. Active: 2010s-present." },
  { name: "Artie Romero", tooltip: "Comic book artist with a dynamic, detailed style, often in horror and superhero genres. Active: 1990s-present." },
  { name: "Félicien Rops", tooltip: "Belgian Symbolist known for erotic, macabre etchings and illustrations. Active: 1850s-1890s." },
  { name: "Don Rosa", tooltip: "Comic artist famous for detailed, adventure-filled Scrooge McDuck stories. Active: 1980s-2000s." },
  { name: "Rosalys", tooltip: "French illustrator of elegant, romantic children's book art with delicate lines. Active: 1920s-1950s." },
  { name: "Alex Ross", tooltip: "American painter renowned for photorealistic superhero art in comics. Active: 1990s-present." },
  { name: "Graham Roumieu", tooltip: "Canadian illustrator with a quirky, humorous style using ink and watercolor. Active: 2000s-present." },
  { name: "Øystein Runde", tooltip: "Norwegian illustrator known for detailed, atmospheric fantasy and children's book art. Active: 1990s-present." },
  { name: "Willie Rushton", tooltip: "British cartoonist and satirist with a distinctive, humorous pen-and-ink style. Active: 1960s-1990s." },
  { name: "Mark Ryden", tooltip: "American painter blending pop surrealism with classical techniques in detailed works. Active: 1990s-present." },
  { name: "Robert Sabuda", tooltip: "Master of intricate, innovative pop-up book engineering and illustration. Active: 1990s-present." },
  { name: "Wiktor Sadowski", tooltip: "Polish illustrator known for dark, surreal fantasy art with meticulous detail. Active: 2000s-present." },
  { name: "Alberto Saichann", tooltip: "Contemporary digital illustrator specializing in vibrant, character-driven fantasy scenes. Active: 2010s-present." },
  { name: "Xavier Saint-Just", tooltip: "French illustrator of elegant, Art Nouveau-inspired decorative and book art. Active: 1890s-1920s." },
  { name: "Armando Salas", tooltip: "Cuban-American illustrator known for colorful, dynamic comic and advertising art. Active: 1950s-1980s." },
  { name: "B. B. Sams", tooltip: "American illustrator of whimsical, detailed children's book and magazine art. Active: 1920s-1950s." },
  { name: "Dan Santat", tooltip: "Award-winning children's book author-illustrator with energetic, humorous digital art. Active: 2000s-present." },
  { name: "Hal Santiago", tooltip: "Filipino comic book artist known for action-packed, dynamic superhero illustrations. Active: 1970s-1990s." },
  { name: "Norman Saunders", tooltip: "American pulp magazine and comic book artist with bold, vibrant cover paintings. Active: 1930s-1980s." },
  { name: "Zina Saunders", tooltip: "Contemporary illustrator and portraitist with a satirical, colorful digital style. Active: 1990s-present." },
  { name: "Allen Say", tooltip: "Japanese-American author-illustrator known for serene, watercolor-based picture books. Active: 1970s-present." },
  { name: "Gerald Scarfe", tooltip: "British caricaturist with an exaggerated, satirical pen-and-ink style. Active: 1960s-present." },
  { name: "Richard Scarry", tooltip: "Beloved children's book illustrator of detailed, bustling animal-filled worlds. Active: 1940s-1990s." },
  { name: "Charles Schneeman", tooltip: "American illustrator known for realistic, detailed science fiction and fantasy art. Active: 1930s-1960s." },
  { name: "Adolf Schrödter", tooltip: "German painter and illustrator of Romantic and Biedermeier genre scenes. Active: 1820s-1860s." },
  { name: "Simon Schwartz", tooltip: "German comic artist and illustrator with a graphic, expressive black-and-white style. Active: 2000s-present." },
  { name: "Richard A. Scott", tooltip: "American illustrator specializing in detailed, atmospheric fantasy and game art. Active: 1990s-present." },
  { name: "Steve Scott", tooltip: "Comic book artist known for dynamic, detailed superhero illustrations. Active: 1980s-2000s." },
  { name: "Henry Seabright", tooltip: "British illustrator of whimsical, detailed fairy tale and children's book art. Active: 1880s-1910s." },
  { name: "Ronald Searle", tooltip: "British cartoonist famous for the satirical St Trinian's school illustrations. Active: 1940s-2000s." },
  { name: "Wilhelmina Seegmiller", tooltip: "American illustrator known for delicate, floral-themed Art Nouveau designs. Active: 1890s-1920s." },
  { name: "Adrienne Segur", tooltip: "French illustrator of enchanting, detailed fairy tale and children's book art. Active: 1930s-1960s." },
  { name: "Maurice Sendak", tooltip: "Iconic children's book author-illustrator of imaginative, sometimes dark works. Active: 1950s-2010s." },
  { name: "Kate Seredy", tooltip: "Hungarian-American author-illustrator of folk-inspired, warm children's book art. Active: 1930s-1960s." },
  { name: "Ben Shahn", tooltip: "American social realist painter and illustrator with a expressive, graphic style. Active: 1920s-1960s." },
  { name: "Nick Sharratt", tooltip: "British children's book illustrator known for bold, colorful, and playful artwork. Active: 1980s-present." },
  { name: "Mark Shasha", tooltip: "American illustrator and painter of detailed, atmospheric maritime and historical scenes. Active: 1980s-present." },
  { name: "John Shelley", tooltip: "British illustrator known for intricate, detailed pen-and-ink fantasy and children's art. Active: 1980s-present." },
  { name: "Ernest Shepard", tooltip: "British illustrator famous for classic pen-and-ink drawings of Winnie-the-Pooh. Active: 1900s-1970s." },
  { name: "Claude Allin Shepperson", tooltip: "British illustrator of elegant, detailed historical and genre scenes. Active: 1880s-1920s." },
  { name: "Dorothy Sherrill", tooltip: "American illustrator known for charming, detailed children's book and magazine art. Active: 1920s-1950s." },
  { name: "Gary Shipman", tooltip: "Contemporary digital illustrator specializing in vibrant, character-driven fantasy art. Active: 2000s-present." },
  { name: "David Shrigley", tooltip: "British artist known for humorous, crude line drawings with satirical text. Active: 1990s-present." },
  { name: "John Sibbick", tooltip: "British paleoartist renowned for detailed, realistic dinosaur illustrations. Active: 1980s-present." },
  { name: "Shel Silverstein", tooltip: "American poet and illustrator of whimsical, pen-and-ink children's book art. Active: 1950s-1990s." },
  { name: "Anne Simon", tooltip: "French comic artist and illustrator with a delicate, expressive watercolor style. Active: 2000s-present." },
  { name: "Parismita Singh", tooltip: "Indian graphic novelist and illustrator blending folk art with contemporary themes. Active: 2000s-present." },
  { name: "Peter Sís", tooltip: "Czech-American illustrator known for intricate, symbolic picture book art. Active: 1980s-present." },
  { name: "Jessie Willcox Smith", tooltip: "American illustrator famous for idealized, sentimental children and motherhood scenes. Active: 1880s-1930s." },
  { name: "Joseph A. Smith", tooltip: "American illustrator known for detailed, realistic wildlife and natural history art. Active: 1970s-present." },
  { name: "Lane Smith", tooltip: "Whimsical, textured collage style with a retro feel. Active: 1980s-present." },
  { name: "Cal Sobrepeña", tooltip: "Dynamic, comic-influenced illustrations with bold lines. Active: 1990s-present." },
  { name: "Fermín Solís", tooltip: "Expressive, humorous cartoon style with simple lines. Active: 1990s-present." },
  { name: "Konstantin Somov", tooltip: "Elegant, Rococo-inspired watercolors with nostalgic themes. Active: 1890s-1930s." },
  { name: "Suzy Spafford", tooltip: "Charming, cheerful watercolor characters like Suzy's Zoo. Active: 1960s-present." },
  { name: "Lancelot Speed", tooltip: "Detailed, dramatic pen-and-ink illustrations for fantasy. Active: 1890s-1930s." },
  { name: "Armstrong Sperry", tooltip: "Vivid, adventurous illustrations for children's literature. Active: 1930s-1960s." },
  { name: "Art Spiegelman", tooltip: "Raw, expressive comics with historical and personal themes. Active: 1970s-present." },
  { name: "Peter Spier", tooltip: "Detailed, lively watercolors capturing everyday scenes. Active: 1950s-2000s." },
  { name: "Minnie Dibdin Spooner", tooltip: "Delicate, sentimental watercolors for children's books. Active: 1890s-1920s." },
  { name: "Bob Staake", tooltip: "Bold, graphic vector art with a modern, geometric style. Active: 1980s-present." },
  { name: "Ralph Steadman", tooltip: "Frenetic, ink-splattered caricatures with satirical edge. Active: 1960s-present." },
  { name: "Frederic Dorr Steele", tooltip: "Realistic, atmospheric pen drawings for Sherlock Holmes. Active: 1890s-1940s." },
  { name: "William Steig", tooltip: "Expressive, loose line drawings with witty humor. Active: 1930s-2000s." },
  { name: "Ralph Stein", tooltip: "Clean, modernist illustrations for magazines and advertising. Active: 1930s-1970s." },
  { name: "Saul Steinberg", tooltip: "Witty, conceptual line drawings blending cartoon and fine art. Active: 1940s-1990s." },
  { name: "Joan Steiner", tooltip: "Ingenious photographic collages using everyday objects. Active: 1990s-present." },
  { name: "Karl Stirner", tooltip: "Bold, expressive woodcut and linocut prints. Active: 1920s-1960s." },
  { name: "William Stobbs", tooltip: "Vigorous, sketch-like illustrations for children's classics. Active: 1950s-1980s." },
  { name: "Barron Storey", tooltip: "Intense, layered mixed-media works with narrative depth. Active: 1960s-present." },
  { name: "Willy Stöwer", tooltip: "Detailed, dramatic maritime paintings and illustrations. Active: 1890s-1930s." },
  { name: "Helen Stratton", tooltip: "Romantic, Pre-Raphaelite-inspired book illustrations. Active: 1890s-1920s." },
  { name: "Drew Struzan", tooltip: "Iconic, photorealistic movie poster paintings. Active: 1970s-present." },
  { name: "Lillie Sullivan", tooltip: "Charming, folk art-style illustrations for children. Active: 1920s-1950s." },
  { name: "Arthur Suydam", tooltip: "Gritty, detailed horror and comic book artwork. Active: 1980s-present." },
  { name: "Hiromi Suzuki", tooltip: "Elegant, minimalist watercolors with poetic themes. Active: 1990s-present." },
  { name: "Glynis Sweeny", tooltip: "Whimsical, colorful illustrations for educational media. Active: 1990s-present." },
  { name: "Christophe Szpajdel", tooltip: "Ornate, Gothic-inspired logo designs for metal bands. Active: 1990s-present." },
  { name: "Emanuele Taglietti", tooltip: "Sensational, pulp-style poster art for Italian films. Active: 1970s-1990s." },
  { name: "Douglas Tait", tooltip: "Dynamic, comic book-influenced fantasy illustrations. Active: 1990s-present." },
  { name: "Shaun Tan", tooltip: "Surreal, detailed paintings exploring identity and memory. Active: 1990s-present." },
  { name: "Margaret Tarrant", tooltip: "Gentle, fairy-tale watercolors for children's books. Active: 1910s-1950s." },
  { name: "Robert Tavener", tooltip: "Bold, graphic linocuts of British landscapes and architecture. Active: 1950s-2000s." },
  { name: "Gary Taxali", tooltip: "Retro, pop art-inspired illustrations with vintage charm. Active: 1990s-present." },
  { name: "Françoise Taylor", tooltip: "Elegant, stylized fashion and advertising illustrations. Active: 1950s-1980s." },
  { name: "Prentiss Taylor", tooltip: "Lyrical, modernist lithographs and book illustrations. Active: 1920s-1970s." },
  { name: "Margaret Tempest", tooltip: "Sweet, pastoral watercolors for the Little Grey Rabbit series. Active: 1920s-1970s." },
  { name: "Sir John Tenniel", tooltip: "Precise, satirical pen drawings for Punch and Alice. Active: 1840s-1900s." },
  { name: "Henri Thiriet", tooltip: "Vibrant, Art Deco-style posters and illustrations. Active: 1920s-1950s." },
  { name: "Béatrice Tillier", tooltip: "Detailed, expressive comic book art with historical themes. Active: 1990s-present." },
  { name: "Trini Tinturé", tooltip: "Humorous, colorful cartoons and children's illustrations. Active: 1970s-present." },
  { name: "Alton S. Tobey", tooltip: "Realistic, historical paintings for educational contexts. Active: 1930s-1990s." },
  { name: "Margot Tomes", tooltip: "Whimsical, folk art-inspired illustrations for children. Active: 1960s-1990s." },
  { name: "Dolly Tree", tooltip: "Glamorous, Art Deco costume and fashion illustrations. Active: 1920s-1940s." },
  { name: "Stuart Tresilian", tooltip: "Dynamic, action-packed illustrations for boys' adventure stories. Active: 1920s-1950s." },
  { name: "Wallace Tripp", tooltip: "Witty, cartoonish animal illustrations with playful humor. Active: 1960s-1990s." },
  { name: "Timothy Truman", tooltip: "Gritty, detailed comic book art with Western and fantasy themes. Active: 1980s-present." },
  { name: "Tasha Tudor", tooltip: "Charming, nostalgic watercolors of rural and family life. Active: 1930s-2000s." },
  { name: "Michael Turner", tooltip: "Dynamic, stylized comic book art with clean lines. Active: 1990s-2000s." },
  { name: "Dick Twinney", tooltip: "Detailed, naturalistic wildlife illustrations. Active: 1960s-2000s." },
  { name: "Chen Uen", tooltip: "Renowned Taiwanese illustrator known for dynamic brushwork and historical themes. Active: 1970s-2010s." },
  { name: "Tomi Ungerer", tooltip: "Provocative satirical illustrator with bold, subversive line work. Active: 1950s-2010s." },
  { name: "Clive Uptton", tooltip: "British illustrator celebrated for detailed, atmospheric historical scenes. Active: 1930s-1970s." },
  { name: "Utisz", tooltip: "Hungarian illustrator known for elegant Art Nouveau-inspired graphic designs. Active: 1900s-1930s." },
  { name: "Boris Vallejo", tooltip: "Fantasy artist famous for hyper-realistic, muscular heroic figures. Active: 1970s-present." },
  { name: "Alberto Vargas", tooltip: "Pin-up artist renowned for glamorous, airbrushed Vargas Girls. Active: 1910s-1980s." },
  { name: "Gee Vaucher", tooltip: "Anarcho-punk collagist with politically charged, surreal imagery. Active: 1970s-present." },
  { name: "Agaate Veeber", tooltip: "Estonian illustrator known for delicate, folk-inspired children's book art. Active: 1920s-1960s." },
  { name: "Max Velthuijs", tooltip: "Dutch children's illustrator with simple, expressive watercolor characters. Active: 1960s-2000s." },
  { name: "Vhrsti", tooltip: "Czech illustrator recognized for whimsical, detailed pen-and-ink drawings. Active: 1990s-present." },
  { name: "Emilio Vilà", tooltip: "Spanish illustrator noted for vibrant, modernist poster designs. Active: 1920s-1960s." },
  { name: "Erich von Götha de la Rosière", tooltip: "Austrian illustrator known for ornate, romantic historical illustrations. Active: 1890s-1920s." },
  { name: "Charles Wadsworth", tooltip: "American illustrator celebrated for detailed, narrative magazine covers. Active: 1900s-1930s." },
  { name: "Dugald Stewart Walker", tooltip: "American illustrator famous for ethereal, Pre-Raphaelite-inspired fairy tales. Active: 1900s-1930s." },
  { name: "Ernest Wallcousins", tooltip: "British illustrator known for dramatic, chiaroscuro historical scenes. Active: 1900s-1940s." },
  { name: "Charles Waterhouse", tooltip: "American military artist with precise, documentary-style combat scenes. Active: 1950s-2000s." },
  { name: "Arthur Watts", tooltip: "British cartoonist known for witty, minimalist line drawings in Punch. Active: 1900s-1930s." },
  { name: "Betty Temple Watts", tooltip: "American illustrator recognized for charming, domestic scene watercolors. Active: 1920s-1950s." },
  { name: "Robert Weaver", tooltip: "American illustrator pioneering loose, expressive reportage-style art. Active: 1950s-1990s." },
  { name: "Emil Weiss", tooltip: "German illustrator known for detailed, realistic scientific and nature drawings. Active: 1890s-1930s." },
  { name: "Jack Welch", tooltip: "American illustrator famous for dynamic, action-packed pulp magazine covers. Active: 1930s-1960s." },
  { name: "Don Weller", tooltip: "American illustrator celebrated for bold, graphic Western and automotive art. Active: 1960s-2000s." },
  { name: "Paul Wenzel", tooltip: "German illustrator known for meticulous, architectural cityscape drawings. Active: 1880s-1920s." },
  { name: "Michael Whelan", tooltip: "Fantasy and sci-fi artist renowned for luminous, detailed book covers. Active: 1970s-present." },
  { name: "Jon Whitcomb", tooltip: "American illustrator famous for glamorous, idealized fashion and advertising art. Active: 1930s-1970s." },
  { name: "Garth Williams", tooltip: "Beloved children's book illustrator with gentle, expressive charcoal drawings. Active: 1940s-1990s." },
  { name: "Robert Williams", tooltip: "American artist known for psychedelic, cartoonish lowbrow and pop surrealism. Active: 1960s-present." },
  { name: "Charles Banks Wilson", tooltip: "American illustrator and painter known for realistic regionalist portraits. Active: 1930s-2000s." },
  { name: "George Wilson", tooltip: "American pulp and sci-fi illustrator with vibrant, action-packed covers. Active: 1950s-1980s." },
  { name: "Larry Winborg", tooltip: "American illustrator recognized for humorous, caricatured editorial cartoons. Active: 1970s-2010s." },
  { name: "Eric Winter", tooltip: "British illustrator known for lively, colorful children's book and poster art. Active: 1920s-1960s." },
  { name: "David Wisniewski", tooltip: "American illustrator famous for intricate, dramatic cut-paper illustrations. Active: 1980s-2000s." },
  { name: "Jonathan Wolstenholme", tooltip: "British illustrator celebrated for detailed, whimsical trompe-l'œil paintings. Active: 1970s-present." },
  { name: "Ashley Wood", tooltip: "Australian illustrator known for gritty, painterly comic and concept art. Active: 1990s-present." },
  { name: "Leslie Wood", tooltip: "British illustrator famous for vibrant, stylized railway and travel posters. Active: 1920s-1960s." },
  { name: "Hildegard Woodward", tooltip: "American illustrator known for charming, folk-art inspired children's books. Active: 1930s-1970s." },
  { name: "Shannon Wright", tooltip: "American illustrator recognized for emotive, graphic novel-style character art. Active: 2000s-present." },
  { name: "Frank Wu", tooltip: "American illustrator known for imaginative, detailed sci-fi and fantasy art. Active: 1990s-present." },
  { name: "N. C. Wyeth", tooltip: "American illustrator famous for dramatic, richly colored adventure scenes. Active: 1900s-1940s." },
  { name: "Takashi Yanase", tooltip: "Japanese illustrator and animator, creator of the beloved character Anpanman. Active: 1950s-2010s." },
  { name: "Marianne Young", tooltip: "British illustrator known for delicate, botanical and nature-inspired drawings. Active: 1890s-1930s." },
  { name: "Yu Rong", tooltip: "Chinese illustrator celebrated for vibrant, culturally rich paper-cut style art. Active: 2000s-present." },
  { name: "Margot Zemach", tooltip: "American illustrator known for lively, humorous folk tale watercolors. Active: 1960s-1990s." },
  { name: "Laura Zuccheri", tooltip: "Italian illustrator recognized for detailed, atmospheric fantasy and sci-fi art. Active: 1990s-present." },
  { name: "Lisbeth Zwerger", tooltip: "Austrian illustrator renowned for ethereal, delicate watercolor fairy tales. Active: 1970s-present." }
];
