export const ART_MOVEMENTS = [
  { name: "Abstract art", tooltip: "Non-representational art emphasizing shapes, colors, and forms over realistic depiction. Active: 1910-present." },
  { name: "Art Brut", tooltip: "Raw, outsider art created by non-professionals, often with intense emotional expression. Active: 1940s-present." },
  { name: "Abstract expressionism", tooltip: "Post-WWII American movement emphasizing spontaneous, abstract, and emotional painting. Active: 1940s-1960s." },
  { name: "Abstract illusionism", tooltip: "Abstract art creating optical illusions of three-dimensional space on flat surfaces. Active: 1970s-present." },
  { name: "Academic art", tooltip: "Style taught by European academies, emphasizing classical techniques and historical subjects. Active: 17th-19th centuries." },
  { name: "Action painting", tooltip: "Subset of abstract expressionism focusing on the physical act of painting. Active: 1940s-1960s." },
  { name: "Aestheticism", tooltip: "Late 19th-century movement valuing beauty and artistic experience over moral or narrative content. Active: 1860s-1900." },
  { name: "Afrofuturism", tooltip: "Cultural aesthetic combining African diaspora culture with technology and futurism. Active: 1990s-present." },
  { name: "Altermodern", tooltip: "Contemporary art movement responding to globalization with hybrid, nomadic forms. Active: 2000s-present." },
  { name: "American Barbizon school", tooltip: "American adaptation of French Barbizon, focusing on rural landscapes and naturalism. Active: 1850s-1900." },
  { name: "American Impressionism", tooltip: "American version of French Impressionism, with loose brushwork and light effects. Active: 1880s-1920s." },
  { name: "American realism", tooltip: "Early 20th-century movement depicting everyday American life with straightforward accuracy. Active: 1900-1940." },
  { name: "American Scene Painting", tooltip: "Interwar movement portraying American rural and urban scenes, often nostalgically. Active: 1920s-1940s." },
  { name: "Analytical art", tooltip: "Russian avant-garde style analyzing and deconstructing artistic elements systematically. Active: 1910s-1920s." },
  { name: "Animation", tooltip: "Art of creating moving images through sequential frames, often in film or digital media. Active: 1900s-present." },
  { name: "Antipodeans", tooltip: "Australian group advocating for figurative art against abstract trends in the 1950s. Active: 1950s-1960s." },
  { name: "Arabesque", tooltip: "Decorative style using intricate, flowing patterns, often in Islamic and Renaissance art. Active: Medieval-present." },
  { name: "Arbeitsrat für Kunst", tooltip: "German post-WWI artists' council promoting social engagement and avant-garde architecture. Active: 1918-1921." },
  { name: "Art & Language", tooltip: "Conceptual art group focusing on language, theory, and critique of art institutions. Active: 1960s-present." },
  { name: "Art Deco", tooltip: "Stylized decorative arts movement featuring geometric shapes and luxury materials. Active: 1920s-1940s." },
  { name: "Art Informel", tooltip: "European abstract movement emphasizing spontaneity and informal, gestural techniques. Active: 1940s-1950s." },
  { name: "Art Nouveau", tooltip: "Decorative style characterized by flowing, organic lines and natural forms. Active: 1890-1910." },
  { name: "Art photography", tooltip: "Photography created as fine art, emphasizing aesthetic and conceptual expression. Active: 19th century-present." },
  { name: "Arte Povera", tooltip: "Italian movement using humble, everyday materials to challenge traditional art values. Active: 1960s-1970s." },
  { name: "Artificial intelligence art", tooltip: "Art created or influenced by AI algorithms, exploring technology and creativity. Active: 2010s-present." },
  { name: "Arts and Crafts movement", tooltip: "Late 19th-century reaction against industrialization, emphasizing handmade craftsmanship. Active: 1880-1910." },
  { name: "ASCII art", tooltip: "Art created using characters from the ASCII text encoding system, often digital. Active: 1960s-present." },
  { name: "Ashcan School", tooltip: "Early 20th-century American realists depicting gritty urban life in New York. Active: 1900-1915." },
  { name: "Assemblage", tooltip: "Art made by assembling found objects into three-dimensional compositions. Active: 1950s-present." },
  { name: "Australian Tonalism", tooltip: "Early 20th-century Australian style using muted colors and atmospheric effects. Active: 1910s-1930s." },
  { name: "Les Automatistes", tooltip: "Canadian abstract group inspired by surrealism and automatic drawing techniques. Active: 1940s-1950s." },
  { name: "Auto-destructive art", tooltip: "Art designed to decay or destroy itself, often as a political or conceptual statement. Active: 1960s-present." },
  { name: "Avant-garde", tooltip: "Umbrella term for innovative, experimental art pushing boundaries of tradition. Active: 19th century-present." },
  { name: "Bacone school", tooltip: "Informal group of British artists influenced by Francis Bacon's figurative expressionism. Active: 1950s-1970s." },
  { name: "Barbizon school", tooltip: "French landscape painters working en plein air, emphasizing naturalism. Active: 1830s-1870s." },
  { name: "Baroque", tooltip: "17th-century European style characterized by drama, movement, and ornate detail. Active: 1600-1750." },
  { name: "Bauhaus", tooltip: "German school combining crafts and fine arts, emphasizing functional design. Active: 1919-1933." },
  { name: "Berlin Secession", tooltip: "German artists' group breaking from academic traditions to embrace modernism. Active: 1898-1913." },
  { name: "Black Arts Movement", tooltip: "African American movement linking art with black nationalism and social activism. Active: 1965-1975." },
  { name: "Bengal School of Art", tooltip: "Indian nationalist art movement reviving traditional styles and themes. Active: 1900s-1920s." },
  { name: "Brutalism", tooltip: "Architectural style using raw concrete and bold geometric forms. Active: 1950s-1970s." },
  { name: "Cave painting", tooltip: "Prehistoric art found on cave walls, depicting animals and human figures. Active: Paleolithic era." },
  { name: "Classical Realism", tooltip: "20th-century revival of traditional realist techniques and classical ideals. Active: 1960s-present." },
  { name: "Cloisonnism", tooltip: "Post-Impressionist style using bold outlines and flat areas of color. Active: 1880s-1890s." },
  { name: "COBRA", tooltip: "European avant-garde group emphasizing spontaneous, expressive, and figurative art. Active: 1948-1951." },
  { name: "Color Field", tooltip: "Abstract painting style focusing on large areas of solid color. Active: 1940s-1960s." },
  { name: "Context art", tooltip: "Art that emphasizes the surrounding environment or situation in its meaning. Active: 1960s-present." },
  { name: "Computer art", tooltip: "Art created using computers, exploring digital techniques and algorithms. Active: 1960s-present." },
  { name: "Concrete art", tooltip: "Abstract art based on mathematical or geometric principles, devoid of symbolism. Active: 1930s-1960s." },
  { name: "Conceptual art", tooltip: "Art where the idea or concept is more important than the physical object. Active: 1960s-present." },
  { name: "Constructivism", tooltip: "Abstract geometric forms emphasizing industrial materials and social purpose. Active: 1915-1930s" },
  { name: "Crystal Cubism", tooltip: "Purified Cubism with flattened, overlapping geometric planes in subdued colors. Active: 1914-1918" },
  { name: "Cubo-Futurism", tooltip: "Russian fusion of Cubist fragmentation with Futurist dynamism and motion. Active: 1912-1915" },
  { name: "Cubism", tooltip: "Analytic fragmentation of objects into geometric planes from multiple viewpoints. Active: 1907-1914" },
  { name: "Cynical realism", tooltip: "Chinese post-1989 art using irony to critique social and political conditions. Active: 1990s-present" },
  { name: "Dada", tooltip: "Anti-art movement embracing absurdity, chance, and protest against bourgeois values. Active: 1916-1924" },
  { name: "Dakar School", tooltip: "Post-independence Senegalese art blending modernist styles with African themes. Active: 1960s-1970s" },
  { name: "Dansaekhwa", tooltip: "Korean monochrome painting emphasizing materiality, process, and meditative repetition. Active: 1970s-present" },
  { name: "Danube school", tooltip: "German Renaissance art characterized by expressive landscapes and vibrant colors. Active: 1490-1540" },
  { name: "Dau-al-Set", tooltip: "Catalan post-war avant-garde group exploring surrealism and existential themes. Active: 1948-1956" },
  { name: "De Stijl (Neoplasticism)", tooltip: "Abstract art using only horizontal/vertical lines and primary colors. Active: 1917-1931" },
  { name: "Deconstructivism", tooltip: "Architectural style fragmenting structures with non-rectilinear shapes and chaos. Active: 1980s-present" },
  { name: "Didacticism", tooltip: "Art intended to instruct or convey moral, political, or educational messages. Active: Ancient-present" },
  { name: "Digital art", tooltip: "Art created using digital technology as an essential part of the process. Active: 1960s-present" },
  { name: "Early Netherlandish painting", tooltip: "Detailed oil painting with symbolic realism and religious themes. Active: 1420-1520" },
  { name: "Ecological Art", tooltip: "Art addressing environmental issues, sustainability, and human-nature relationships. Active: 1960s-present" },
  { name: "Environmental art", tooltip: "Site-specific works using natural materials and landscapes as medium. Active: 1960s-present" },
  { name: "Modern European ink painting", tooltip: "Contemporary reinterpretation of traditional East Asian ink techniques. Active: 1950s-present" },
  { name: "Excessivism", tooltip: "Critique of consumerism through exaggerated depictions of material excess. Active: 2015-present" },
  { name: "Exoticism", tooltip: "Art depicting foreign cultures as romanticized, mysterious, or primitive. Active: 18th-20th centuries" },
  { name: "Expressionism", tooltip: "Distorted forms and vivid colors to convey emotional experience. Active: 1905-1920s" },
  { name: "Fantastic realism", tooltip: "Vienna School style blending precise realism with surreal, fantastical imagery. Active: 1946-present" },
  { name: "Fauvism", tooltip: "Bold, non-naturalistic colors and simplified forms for emotional impact. Active: 1904-1908" },
  { name: "Feminist art", tooltip: "Art challenging patriarchal norms and highlighting women's experiences. Active: 1960s-present" },
  { name: "Figurative art", tooltip: "Artwork that represents real objects, especially the human figure. Active: Ancient-present" },
  { name: "Figuration Libre", tooltip: "French 1980s movement with spontaneous, cartoonish, and playful imagery. Active: 1981-1990s" },
  { name: "Fine Art", tooltip: "Art created primarily for aesthetic and intellectual purposes. Active: Renaissance-present" },
  { name: "Fin de siècle", tooltip: "Late 19th-century art reflecting decadence, symbolism, and cultural anxiety. Active: 1880-1914" },
  { name: "Folk art", tooltip: "Traditional crafts and decorative arts by untrained artists. Active: Ancient-present" },
  { name: "Flemish painting", tooltip: "Richly detailed oil painting with emphasis on texture and realism. Active: 15th-17th centuries" },
  { name: "Fluxus", tooltip: "Interdisciplinary avant-garde movement emphasizing process, play, and anti-commercialism. Active: 1960s-1970s" },
  { name: "Funk art", tooltip: "West Coast 1960s movement using found objects and irreverent humor. Active: 1960s-1970s" },
  { name: "Futurism", tooltip: "Italian celebration of speed, technology, and violence through dynamic forms. Active: 1909-1944" },
  { name: "Generative art", tooltip: "Art created using autonomous systems, algorithms, or rule-based processes. Active: 1960s-present" },
  { name: "Geometric abstract art", tooltip: "Non-representational art using geometric shapes and precise compositions. Active: 1910s-present" },
  { name: "Glitch art", tooltip: "Aesthetic embracing digital errors and system malfunctions as artistic medium. Active: 1990s-present" },
  { name: "Graffiti/Street Art", tooltip: "Public, often unsanctioned art using urban surfaces as canvas. Active: 1960s-present" },
  { name: "Gutai group", tooltip: "Japanese post-war avant-garde emphasizing material experimentation and performance. Active: 1954-1972" },
  { name: "Gothic art", tooltip: "Medieval art characterized by elongated forms, religious themes, and intricate detail. Active: 12th-16th centuries" },
  { name: "Happening", tooltip: "Performance art event blurring boundaries between art and life, often improvised. Active: 1950s-1960s" },
  { name: "Harlem Renaissance", tooltip: "African American cultural movement celebrating Black identity and heritage. Active: 1918-1930s" },
  { name: "Heidelberg School", tooltip: "Australian Impressionist painting capturing the unique light and landscape. Active: 1880s-1890s" },
  { name: "Hudson River School", tooltip: "American landscape painting romanticizing nature's grandeur and spirituality. Active: 1825-1875" },
  { name: "Hurufiyya", tooltip: "Modern Arab art movement incorporating Arabic calligraphy as abstract form. Active: 1950s-present" },
  { name: "Hypermodernism", tooltip: "Contemporary art exploring digital culture, globalization, and technological excess. Active: 2000s-present" },
  { name: "Hyperrealism", tooltip: "Art creating illusion of reality with extreme detail and precision. Active: 1970s-present" },
  { name: "Impressionism", tooltip: "Capturing fleeting light and atmosphere with visible brushstrokes and bright colors. Active: 1860s-1880s" },
  { name: "Incoherents", tooltip: "Parisian anti-establishment group exhibiting absurd, humorous, and satirical works. Active: 1882-1893" },
  { name: "Interactive Art", tooltip: "Art requiring viewer participation to complete or experience the work. Active: 1960s-present" },
  { name: "Institutional critique", tooltip: "Art examining and challenging the structures of museums and galleries. Active: 1960s-present" },
  { name: "International Gothic", tooltip: "Elegant, detailed courtly style with elongated figures and rich colors. Active: 1375-1425." },
  { name: "International Typographic Style", tooltip: "Clean, grid-based design emphasizing objectivity and sans-serif typography. Active: 1950s-1970s." },
  { name: "Japonisme", tooltip: "Western artists adopting Japanese aesthetics like flat planes and asymmetry. Active: 1860s-1900." },
  { name: "Japanese art", tooltip: "Diverse traditions including ukiyo-e prints, ink painting, and calligraphy. Active: Ancient-present." },
  { name: "Kinetic art", tooltip: "Art incorporating real or apparent movement, often mechanical. Active: 1920s-present." },
  { name: "Kinetic Pointillism", tooltip: "Pointillism with moving elements or optical effects. Active: 1960s-1970s." },
  { name: "Kitsch movement", tooltip: "Deliberate use of garish, sentimental, or mass-produced aesthetics. Active: 1970s-present." },
  { name: "Land art", tooltip: "Large-scale works using natural landscapes and materials. Active: 1960s-present." },
  { name: "Les Nabis", tooltip: "Post-Impressionist group emphasizing flat patterns and symbolic color. Active: 1888-1900." },
  { name: "Letterism", tooltip: "Avant-garde movement focusing on letters and typography as art. Active: 1940s-1960s." },
  { name: "Light and Space", tooltip: "California-based art exploring perception through light and translucent materials. Active: 1960s-present." },
  { name: "Lowbrow", tooltip: "Pop surrealism drawing from underground comics and punk culture. Active: 1970s-present." },
  { name: "Lyco art", tooltip: "Movement blending lyrical and conceptual approaches, often abstract. Active: 1970s-1980s." },
  { name: "Lyrical abstraction", tooltip: "Expressive, gestural abstract painting emphasizing emotion. Active: 1945-1960." },
  { name: "Magic realism", tooltip: "Realistic depiction with surreal or fantastical elements. Active: 1920s-present." },
  { name: "Mail art", tooltip: "Art sent through postal systems, emphasizing communication and networks. Active: 1960s-present." },
  { name: "Mannerism", tooltip: "Stylized, elongated figures and complex compositions after Renaissance. Active: 1520-1600." },
  { name: "Massurrealism", tooltip: "Blend of mass media imagery with surrealist techniques. Active: 1990s-present." },
  { name: "Maximalism", tooltip: "Ornate, layered aesthetic embracing excess and complexity. Active: 1970s-present." },
  { name: "Metaphysical painting", tooltip: "Dreamlike scenes with eerie light and enigmatic objects. Active: 1910-1920." },
  { name: "Mingei", tooltip: "Japanese folk craft movement valuing handmade, utilitarian objects. Active: 1920s-present." },
  { name: "Minimalism", tooltip: "Reduced forms, geometric shapes, and industrial materials. Active: 1960s-present." },
  { name: "Modernism", tooltip: "Break from tradition, emphasizing innovation and abstraction. Active: 1860s-1970s." },
  { name: "Modular constructivism", tooltip: "Constructivist art using repeated geometric modules. Active: 1960s-1970s." },
  { name: "Naive art", tooltip: "Childlike, untrained style with bright colors and simple forms. Active: 19th century-present." },
  { name: "Neoclassicism", tooltip: "Revival of classical Greek and Roman themes and clarity. Active: 1760s-1840s." },
  { name: "Neo-Dada", tooltip: "Post-WWII revival of Dada's absurdity and anti-art stance. Active: 1950s-1960s." },
  { name: "Neo-expressionism", tooltip: "Emotional, raw figurative painting rejecting minimalism. Active: 1970s-1980s." },
  { name: "Neo-Fauvism", tooltip: "Late 20th-century revival of Fauvism's bold, non-naturalistic color. Active: 1960s-1970s." },
  { name: "Neo-figurative", tooltip: "Return to figurative art with expressive or distorted forms. Active: 1950s-1960s." },
  { name: "Neogeo", tooltip: "1980s art critiquing consumerism with geometric abstraction. Active: 1980s-1990s." },
  { name: "Neoism", tooltip: "Anti-art movement blending plagiarism, performance, and media. Active: 1979-1990s." },
  { name: "Neo-primitivism", tooltip: "Modern art inspired by tribal or folk art styles. Active: 1900s-1930s." },
  { name: "Neo-romanticism", tooltip: "Romantic revival emphasizing emotion, nature, and myth. Active: 1930s-1950s." },
  { name: "Net art", tooltip: "Art created and distributed via the internet. Active: 1990s-present." },
  { name: "New Objectivity", tooltip: "German realist style critiquing society with sharp detail. Active: 1920s-1930s." },
  { name: "New Sculpture", tooltip: "Late Victorian sculpture emphasizing naturalism and symbolism. Active: 1880s-1900." },
  { name: "Northern landscape style", tooltip: "European landscape painting emphasizing mood and light. Active: 17th-19th centuries." },
  { name: "Northwest School", tooltip: "Pacific Northwest artists inspired by nature and indigenous art. Active: 1930s-1940s." },
  { name: "Nuclear art", tooltip: "Art reflecting atomic age anxieties with abstract forms. Active: 1940s-1960s." },
  { name: "Nueva Figuración", tooltip: "Latin American figurative art with political and social themes. Active: 1960s-1970s." },
  { name: "Objective abstraction", tooltip: "British abstract art focusing on formal elements and process. Active: 1930s-1936." },
  { name: "Op Art", tooltip: "Optical art creating illusions of movement through patterns. Active: 1960s-1970s." },
  { name: "Orphism", tooltip: "Abstract style emphasizing pure color and light, derived from Cubism. Active: 1912-1914." },
  { name: "Patna School of Painting", tooltip: "Indian painting style blending Mughal and British influences. Active: 1760s-1880s." },
  { name: "Photorealism", tooltip: "Hyper-realistic painting mimicking photographic detail. Active: 1960s-present." },
  { name: "Panfuturism", tooltip: "Futurist-inspired movement emphasizing technology and dynamism. Active: 1910s-1920s." },
  { name: "Paris School", tooltip: "Diverse group of artists in Paris, often modernist and expressive. Active: 1900-1940." },
  { name: "Pixel art", tooltip: "Digital art using pixel-level detail, often nostalgic. Active: 1980s-present." },
  { name: "Plasticien", tooltip: "Quebec abstract art movement focusing on geometric purity. Active: 1950s-1960s." },
  { name: "Plein Air", tooltip: "Painting outdoors to capture natural light and atmosphere. Active: 19th century onward." },
  { name: "Pointillism", tooltip: "Using small dots of pure color to form images. Active: 1880s-1910s." },
  { name: "Pop art", tooltip: "Incorporating imagery from popular culture and mass media. Active: 1950s-1970s." },
  { name: "Post-Impressionism", tooltip: "Emphasizing symbolic content and abstract qualities. Active: 1880s-1910s." },
  { name: "Postminimalism", tooltip: "Focusing on process, materials, and conceptual ideas. Active: 1960s-1970s." },
  { name: "Precisionism", tooltip: "Depicting industrial and urban subjects with clean lines. Active: 1920s-1930s." },
  { name: "Pre-Raphaelitism", tooltip: "Detailed, vibrant works inspired by medieval art. Active: 1848-1850s." },
  { name: "Primitivism", tooltip: "Adopting styles from non-Western or prehistoric art. Active: late 19th-early 20th century." },
  { name: "Private Press", tooltip: "Handcrafted books emphasizing artistic design and typography. Active: late 19th century onward." },
  { name: "Process art", tooltip: "Highlighting the act of creation and materials over finished product. Active: 1960s-1970s." },
  { name: "Progressive Art Movement", tooltip: "Indian movement blending modernist styles with social themes. Active: 1940s-1950s." },
  { name: "Psychedelic art", tooltip: "Vibrant, swirling designs inspired by altered states of consciousness. Active: 1960s-1970s." },
  { name: "Purism", tooltip: "Clean, geometric forms emphasizing order and precision. Active: 1918-1925." },
  { name: "Qajar art", tooltip: "Persian art with detailed portraiture and decorative elements. Active: 1785-1925." },
  { name: "Qinglü shanshui", tooltip: "Chinese blue-green landscape painting using mineral pigments. Active: Tang Dynasty onward." },
  { name: "Quito School", tooltip: "Baroque religious art from colonial Ecuador, known for dramatic expression. Active: 17th-18th centuries." },
  { name: "Rasquache", tooltip: "Chicano aesthetic using found objects and vibrant, makeshift art. Active: late 20th century onward." },
  { name: "Rayonism", tooltip: "Abstract art depicting rays of light and dynamic energy. Active: 1911-1914." },
  { name: "Realism", tooltip: "Depicting everyday subjects with accuracy and without idealization. Active: 1840s-1880s." },
  { name: "Regionalism", tooltip: "American art focusing on rural and small-town scenes. Active: 1930s-1940s." },
  { name: "Remodernism", tooltip: "Reviving spiritual and figurative elements in contemporary art. Active: 2000 onward." },
  { name: "Renaissance", tooltip: "Revival of classical ideals, emphasizing perspective and humanism. Active: 14th-17th centuries." },
  { name: "Retrofuturism", tooltip: "Blending past aesthetics with futuristic themes and technology. Active: 1970s onward." },
  { name: "Rococo", tooltip: "Ornate, playful style with light colors and asymmetrical designs. Active: 1730s-1770s." },
  { name: "Romanesque", tooltip: "Medieval art characterized by solid forms and religious themes. Active: 1000-1200." },
  { name: "Romanticism", tooltip: "Emphasizing emotion, nature, and individualism. Active: late 18th-mid-19th century." },
  { name: "Samikshavad", tooltip: "Indian art movement focusing on critical realism and social issues. Active: 1970s onward." },
  { name: "San Ildefonso school", tooltip: "Pueblo pottery known for black-on-black designs and polished surfaces. Active: early 20th century onward." },
  { name: "Serial art", tooltip: "Creating works in series based on systematic repetition or variation. Active: 1960s onward." },
  { name: "Shanshui", tooltip: "Traditional Chinese landscape painting emphasizing nature and spirituality. Active: 5th century onward." },
  { name: "Shin hanga", tooltip: "Japanese prints blending traditional ukiyo-e with Western influences. Active: 1910s-1960s." },
  { name: "Shock art", tooltip: "Art intended to provoke strong reactions through controversial content. Active: 1980s onward." },
  { name: "Site-specific art", tooltip: "Art created for and integrated into a particular location. Active: 1960s onward." },
  { name: "Skeuomorph", tooltip: "Design elements that mimic older materials or functions in new objects. Active: ancient times onward." },
  { name: "Sōsaku hanga", tooltip: "Japanese creative prints where artists handle all production stages. Active: 1900s-1960s." },
  { name: "Socialist realism", tooltip: "Art promoting socialist ideals with realistic, heroic depictions. Active: 1930s-1980s." },
  { name: "Sots art", tooltip: "Soviet unofficial art parodying socialist realism and propaganda. Active: 1970s-1980s." },
  { name: "Southern School", tooltip: "Chinese literati painting emphasizing expressive brushwork and spontaneity. Active: 10th century onward." },
  { name: "Space art", tooltip: "Art depicting astronomical themes and space exploration. Active: 20th century onward." },
  { name: "Street art", tooltip: "Public, often unsanctioned art including graffiti and murals. Active: 1960s onward." },
  { name: "Stuckism", tooltip: "Advocating for figurative painting over conceptual art. Active: 1999 onward." },
  { name: "Studio style", tooltip: "Academic painting emphasizing controlled studio conditions and technique. Active: 19th century." },
  { name: "Sumatraism", tooltip: "Indonesian art movement blending local traditions with modern styles. Active: 1930s-1940s." },
  { name: "Superflat", tooltip: "Japanese art with flat planes, influenced by anime and consumer culture. Active: 2000 onward." },
  { name: "Suprematism", tooltip: "Abstract art using basic geometric forms and limited colors. Active: 1915-1930s." },
  { name: "Surrealism", tooltip: "Exploring the unconscious mind through dreamlike and bizarre imagery. Active: 1920s-1960s." },
  { name: "Symbolism", tooltip: "Using symbols to represent ideas and emotions beyond literal meaning. Active: 1880s-1910s." },
  { name: "Synchromism", tooltip: "Abstract art focusing on color harmonies and musical rhythms. Active: 1912-1919." },
  { name: "Synthetism", tooltip: "Simplifying forms and using flat areas of bold color. Active: 1880s-1890s." },
  { name: "Tachisme (Informel)", tooltip: "Abstract painting with spontaneous brushstrokes and drips. Active: 1940s-1950s." },
  { name: "Temporary art", tooltip: "Artworks designed to exist only briefly, emphasizing process over permanence. Active: 1960s-present" },
  { name: "Toyism", tooltip: "Figurative, narrative style with masked artists using bright colors and symbolic toys. Active: 1992-present" },
  { name: "Transgressive art", tooltip: "Challenges societal norms through shocking, taboo subjects and imagery. Active: 1970s-present" },
  { name: "Tonalism", tooltip: "American landscape painting emphasizing mood, atmosphere, and subdued color harmonies. Active: 1880-1915" },
  { name: "Ukiyo-e", tooltip: "Japanese woodblock prints depicting everyday life, theater, and beautiful women. Active: 17th-19th centuries" },
  { name: "Underground comix", tooltip: "Countercultural comics with adult themes, satire, and DIY aesthetics. Active: 1960s-1970s" },
  { name: "Vancouver School", tooltip: "Photoconceptualism exploring landscape, memory, and identity through large-scale photos. Active: 1980s-present" },
  { name: "Vanitas", tooltip: "Still-life paintings symbolizing life's transience with skulls, flowers, and hourglasses. Active: 16th-17th centuries" },
  { name: "Verdadism", tooltip: "Puerto Rican social realism depicting harsh realities of poverty and colonialism. Active: 1940s-1950s" },
  { name: "Video art", tooltip: "Uses video technology as artistic medium, often exploring time and perception. Active: 1960s-present" },
  { name: "Visual Art", tooltip: "Broad term encompassing all art forms primarily visual in nature. Active: Ancient times-present" },
  { name: "Viennese Actionism", tooltip: "Radical performance art using body, blood, and ritual to confront trauma. Active: 1960-1971" },
  { name: "Vorticism", tooltip: "British abstract movement emphasizing angular forms and industrial energy. Active: 1914-1918" },
  { name: "Women's Art Movement", tooltip: "Feminist art challenging patriarchal norms and promoting women's experiences. Active: 1960s-1980s" },
  { name: "Young British Artists", tooltip: "Provocative, conceptual art using everyday materials and sensational themes. Active: 1988-1999" },
  { name: "Young Poland", tooltip: "Polish modernist movement embracing symbolism, folklore, and national identity. Active: 1890-1918" },
  { name: "Zhe school", tooltip: "Contemporary Chinese ink painting blending traditional techniques with modern abstraction. Active: 1980s-present" }
];
