export const ART_MOVEMENTS = [
  "Abstract art",
  "Art Brut",
  "Abstract expressionism",
  "Abstract illusionism",
  "Academic art",
  "Action painting",
  "Aestheticism",
  "Afrofuturism",
  "Altermodern",
  "American Barbizon school",
  "American Impressionism",
  "American realism",
  "American Scene Painting",
  "Analytical art",
  "Animation",
  "Antipodeans",
  "Arabesque",
  "Arbeitsrat für Kunst",
  "Art & Language",
  "Art Deco",
  "Art Informel",
  "Art Nouveau",
  "Art photography",
  "Arte Povera",
  "Artificial intelligence art",
  "Arts and Crafts movement",
  "ASCII art",
  "Ashcan School",
  "Assemblage",
  "Australian Tonalism",
  "Les Automatistes",
  "Auto-destructive art",
  "Avant-garde",
  "Bacone school",
  "Barbizon school",
  "Baroque",
  "Bauhaus",
  "Berlin Secession",
  "Black Arts Movement",
  "Bengal School of Art",
  "Brutalism",
  "Cave painting",
  "Classical Realism",
  "Cloisonnism",
  "COBRA",
  "Color Field",
  "Context art",
  "Computer art",
  "Concrete art",
  "Conceptual art",
  "Constructivism",
  "Crystal Cubism",
  "Cubo-Futurism",
  "Cubism",
  "Cynical realism",
  "Dada",
  "Dakar School",
  "Dansaekhwa",
  "Danube school",
  "Dau-al-Set",
  "De Stijl (Neoplasticism)",
  "Deconstructivism",
  "Didacticism",
  "Digital art",
  "Early Netherlandish painting",
  "Ecological Art",
  "Environmental art",
  "Modern European ink painting",
  "Excessivism",
  "Exoticism",
  "Expressionism",
  "Fantastic realism",
  "Fauvism",
  "Feminist art",
  "Figurative art",
  "Figuration Libre",
  "Fine Art",
  "Fin de siècle",
  "Folk art",
  "Flemish painting",
  "Fluxus",
  "Funk art",
  "Futurism",
  "Generative art",
  "Geometric abstract art",
  "Glitch art",
  "Graffiti/Street Art",
  "Gutai group",
  "Gothic art",
  "Happening",
  "Harlem Renaissance",
  "Heidelberg School",
  "Hudson River School",
  "Hurufiyya",
  "Hypermodernism",
  "Hyperrealism",
  "Impressionism",
  "Incoherents",
  "Interactive Art",
  "Institutional critique",
  "International Gothic",
  "International Typographic Style",
  "Japonisme",
  "Japanese art",
  "Kinetic art",
  "Kinetic Pointillism",
  "Kitsch movement",
  "Land art",
  "Les Nabis",
  "Letterism",
  "Light and Space",
  "Lowbrow",
  "Lyco art",
  "Lyrical abstraction",
  "Magic realism",
  "Mail art",
  "Mannerism",
  "Massurrealism",
  "Maximalism",
  "Metaphysical painting",
  "Mingei",
  "Minimalism",
  "Modernism",
  "Modular constructivism",
  "Naive art",
  "Neoclassicism",
  "Neo-Dada",
  "Neo-expressionism",
  "Neo-Fauvism",
  "Neo-figurative",
  "Neogeo",
  "Neoism",
  "Neo-primitivism",
  "Neo-romanticism",
  "Net art",
  "New Objectivity",
  "New Sculpture",
  "Northern landscape style",
  "Northwest School",
  "Nuclear art",
  "Nueva Figuración",
  "Objective abstraction",
  "Op Art",
  "Orphism",
  "Patna School of Painting",
  "Photorealism",
  "Panfuturism",
  "Paris School",
  "Pixel art",
  "Plasticien",
  "Plein Air",
  "Pointillism",
  "Pop art",
  "Post-Impressionism",
  "Postminimalism",
  "Precisionism",
  "Pre-Raphaelitism",
  "Primitivism",
  "Private Press",
  "Process art",
  "Progressive Art Movement",
  "Psychedelic art",
  "Purism",
  "Qajar art",
  "Qinglü shanshui",
  "Quito School",
  "Rasquache",
  "Rayonism",
  "Realism",
  "Regionalism",
  "Remodernism",
  "Renaissance",
  "Retrofuturism",
  "Rococo",
  "Romanesque",
  "Romanticism",
  "Samikshavad",
  "San Ildefonso school",
  "Serial art",
  "Shanshui",
  "Shin hanga",
  "Shock art",
  "Site-specific art",
  "Skeuomorph",
  "Sōsaku hanga",
  "Socialist realism",
  "Sots art",
  "Southern School",
  "Space art",
  "Street art",
  "Stuckism",
  "Studio style",
  "Sumatraism",
  "Superflat",
  "Suprematism",
  "Surrealism",
  "Symbolism",
  "Synchromism",
  "Synthetism",
  "Tachisme (Informel)",
  "Temporary art",
  "Toyism",
  "Transgressive art",
  "Tonalism",
  "Ukiyo-e",
  "Underground comix",
  "Vancouver School",
  "Vanitas",
  "Verdadism",
  "Video art",
  "Visual Art",
  "Viennese Actionism",
  "Vorticism",
  "Women's Art Movement",
  "Young British Artists",
  "Young Poland",
  "Zhe school"
];
