export const ART_STYLES = [
  { name: "Classical art", tooltip: "Ancient Greek and Roman artistic traditions emphasizing harmony, proportion, idealized beauty, and naturalistic human form. c. 800 BCE – 400 CE" },
  { name: "Minoan art", tooltip: "Bronze Age civilization of Crete. Vibrant frescoes of nature, marine life, and athletic scenes with flowing, dynamic forms. c. 2700–1450 BCE" },
  { name: "Aegean art", tooltip: "Art of the Bronze Age Aegean civilizations — Minoan, Cycladic, and Mycenaean — featuring stylized figures and marine motifs. c. 3000–1100 BCE" },
  { name: "Ancient Greek art", tooltip: "Art spanning Archaic, Classical, and Hellenistic periods. Idealized human proportion, mythological subjects, and architectural sculpture. c. 800–31 BCE" },
  { name: "Roman art", tooltip: "Art of the Roman Republic and Empire. Realistic portraiture, historical relief sculpture, mosaics, and illusionistic wall painting. c. 500 BCE – 476 CE" },
  { name: "Medieval art", tooltip: "Art of the European Middle Ages. Hierarchical composition, gold grounds, religious iconography, and manuscript illumination. c. 500–1400" },
  { name: "Early Christian", tooltip: "Art created by and for early Christians, adapting Roman forms for biblical subjects. Catacombs, sarcophagi, and basilica mosaics. c. 100–500" },
  { name: "Migration Period", tooltip: "Art of Germanic and Celtic peoples during the fall of Rome. Intricate animal interlace, metalwork, and polychrome jewelry. c. 300–700" },
  { name: "Anglo-Saxon", tooltip: "Art of early medieval England. Elaborate metalwork, manuscript illumination, and interlace patterns blending Celtic and Germanic styles. c. 450–1066" },
  { name: "Visigothic", tooltip: "Art of the Visigoths in Iberia. Horseshoe arches, metalwork with gemstone inlay, and manuscript illumination. c. 500–711" },
  { name: "Pre-Romanesque", tooltip: "Diverse early medieval European styles preceding Romanesque. Includes Carolingian, Ottonian, and Asturian architectural and decorative arts. c. 500–1000" },
  { name: "Insular", tooltip: "Art of the British Isles and Ireland, blending Celtic, Anglo-Saxon, and Christian traditions. Famous for the Book of Kells. c. 600–900" },
  { name: "Viking", tooltip: "Scandinavian art characterized by intricate animal interlace, runic carving, ship ornamentation, and metalwork. c. 790–1100" },
  { name: "Byzantine", tooltip: "Art of the Eastern Roman Empire. Gold-ground mosaics, icon painting, hierarchical composition, and spiritual solemnity. c. 330–1453" },
  { name: "Merovingian", tooltip: "Art of the Frankish Merovingian dynasty. Metalwork, gemstone cloisonné, Christian manuscripts, and animal-style ornament. c. 450–750" },
  { name: "Carolingian", tooltip: "Art under Charlemagne and successors. Revival of classical forms, lavish manuscripts, ivories, and monumental architecture. c. 780–900" },
  { name: "Ottonian", tooltip: "Art of the Saxon dynasty in the Holy Roman Empire. Expressive manuscript painting, metalwork, and monumental church sculpture. c. 936–1056" },
  { name: "Romanesque", tooltip: "European art and architecture with massive stone construction, rounded arches, sculptural church portals, and vivid wall painting. c. 1000–1200" },
  { name: "Norman-Sicilian", tooltip: "Fusion of Norman, Byzantine, and Islamic artistic traditions in Sicily. Splendid mosaics, geometric inlay, and muqarnas decoration. c. 1060–1200" },
  { name: "Gothic", tooltip: "European style with soaring pointed arches, ribbed vaults, stained glass, and elongated sculptural figures. c. 1140–1500" },
  { name: "International Gothic", tooltip: "Late medieval courtly style across Europe. Elegant figures, rich patterning, naturalistic detail, and gilded backgrounds. c. 1375–1425" },
  { name: "Renaissance", tooltip: "Revival of classical ideals in Italy and Europe. Linear perspective, anatomical accuracy, humanism, and balanced composition. c. 1400–1600" },
  { name: "Italian Renaissance", tooltip: "Centered in Florence, Rome, and Venice. Groundbreaking perspective, classical proportion, and mastery of oil and fresco painting. c. 1400–1600" },
  { name: "Renaissance Classicism", tooltip: "The High Renaissance ideal of balance, harmony, and perfection typified by Leonardo, Raphael, and Michelangelo. c. 1490–1527" },
  { name: "Early Netherlandish painting", tooltip: "Northern European painting with meticulous realism, oil glazing technique, and intimate domestic and religious scenes. c. 1420–1550" },
  { name: "Early Cretan School", tooltip: "Post-Byzantine icon painting tradition on Venetian-ruled Crete, blending Byzantine and Western styles. c. 1400–1500" },
  { name: "Mannerism and Late Renaissance", tooltip: "Elongated proportions, complex poses, vivid color, and intellectual sophistication departing from High Renaissance harmony. c. 1520–1600" },
  { name: "Baroque", tooltip: "Dramatic use of light and shadow, rich color, emotional intensity, grandeur, and dynamic movement. c. 1600–1750" },
  { name: "Dutch Golden Age painting", tooltip: "Flourishing of Dutch art featuring realistic genre scenes, landscapes, still lifes, and portraiture. c. 1588–1672" },
  { name: "Flemish Baroque painting", tooltip: "Rubens-led Flemish tradition of exuberant color, fleshy forms, dynamic composition, and Counter-Reformation subjects. c. 1585–1700" },
  { name: "Caravaggisti", tooltip: "Followers of Caravaggio's dramatic tenebrism — stark contrasts of light and darkness with theatrical realism. c. 1600–1650" },
  { name: "Rococo", tooltip: "Lighthearted, ornamental style featuring pastel colors, curved forms, playful subjects, and aristocratic elegance. c. 1720–1780" },
  { name: "Neoclassicism", tooltip: "Revival of Greek and Roman ideals emphasizing clarity, symmetry, heroic virtue, and restrained emotion. c. 1760–1850" },
  { name: "Later Cretan School", tooltip: "Continuation of Cretan icon painting tradition with increasing Western influence after the fall of Crete to the Ottomans. c. 1500–1700" },
  { name: "Heptanese School", tooltip: "Greek painting tradition on the Ionian Islands, transitioning from Byzantine to Western academic styles. c. 1650–1830" },
  { name: "Romanticism", tooltip: "Emphasis on emotion, individualism, the sublime in nature, and dramatic narrative over rational classical order. c. 1780–1850" },
  { name: "Nazarene movement", tooltip: "German-Austrian painters reviving sincere, religious art modeled on early Italian Renaissance and medieval models. c. 1809–1850" },
  { name: "The Ancients", tooltip: "Group of English Romantic artists inspired by William Blake, painting pastoral and visionary landscapes at Shoreham. c. 1824–1835" },
  { name: "Purismo", tooltip: "Italian movement advocating return to the purity and grace of pre-Raphael and medieval Italian painting. c. 1830–1860" },
  { name: "Düsseldorf school", tooltip: "German academic painting school known for finely detailed landscapes, genre scenes, and historical subjects. c. 1819–1895" },
  { name: "Hudson River School", tooltip: "American landscape painting movement celebrating the sublime wilderness of North America with luminous, panoramic vistas. c. 1825–1875" },
  { name: "Luminism", tooltip: "American landscape painting emphasizing serene, glowing light effects, calm waters, and smooth, concealed brushwork. c. 1850–1875" },
  { name: "Modern Greek art", tooltip: "Greek art from the 19th century onward. Academic portraiture, landscape, and the emergence of Hellenic modernism. c. 1830–1930" },
  { name: "Norwich school", tooltip: "English school of landscape painters centered in Norwich. Known for atmospheric East Anglian scenery. c. 1803–1833" },
  { name: "Biedermeier", tooltip: "Central European style favoring intimate domestic scenes, simple elegance, and bourgeois sensibility in art and decor. c. 1815–1848" },
  { name: "Academic art", tooltip: "Art following strict European academy standards: idealized figures, historical subjects, polished technique, and classical composition. c. 1830–1900" },
  { name: "Realism", tooltip: "Movement depicting everyday subjects without idealization. Truthful, unembellished representation of contemporary life. c. 1840–1880" },
  { name: "Barbizon school", tooltip: "French landscape painters working near Fontainebleau. Precursors to Impressionism with naturalistic, plein-air scenes. c. 1830–1870" },
  { name: "Peredvizhniki", tooltip: "Russian 'Wanderers' — realist artists depicting Russian social life and landscape, exhibiting via traveling shows. c. 1870–1923" },
  { name: "Abramtsevo Colony", tooltip: "Russian artists' colony reviving folk art traditions through craft, theater design, and neo-Russian decorative arts. c. 1870–1900" },
  { name: "Hague School", tooltip: "Dutch plein-air painters influenced by Barbizon, known for subtle, atmospheric landscapes and seascapes. c. 1860–1900" },
  { name: "American Barbizon School", tooltip: "American landscape painters influenced by French Barbizon naturalism, favoring pastoral rural and woodland scenes. c. 1850–1890" },
  { name: "Spanish Eclecticism", tooltip: "Eclectic Spanish architectural and decorative style mixing Neo-Gothic, Neo-Mudéjar, and Art Nouveau elements. c. 1850–1920" },
  { name: "Macchiaioli", tooltip: "Italian painters who used dabs (macchie) of color and strong chiaroscuro, paralleling French Impressionism. c. 1855–1875" },
  { name: "Pre-Raphaelite Brotherhood", tooltip: "English painters rejecting academic conventions for vivid color, meticulous detail, and medieval literary subjects. c. 1848–1854" },
  { name: "Modern art", tooltip: "Broad term for progressive art from the late 19th century onward, breaking from academic tradition in form, color, and subject. c. 1860–1970" },
  { name: "Impressionism", tooltip: "Capturing fleeting light and atmosphere through loose brushwork, plein-air painting, and contemporary subjects. c. 1860–1886" },
  { name: "American Impressionism", tooltip: "American adaptation of French Impressionism with looser brushwork, bright palette, and domestic and landscape subjects. c. 1880–1920" },
  { name: "Cos Cob Art Colony", tooltip: "American Impressionist colony in Connecticut known for luminous harbor and coastal New England scenes. c. 1890–1920" },
  { name: "Heidelberg School", tooltip: "Australian Impressionist painters capturing the unique light and landscape of the Australian bush in plein air. c. 1886–1900" },
  { name: "Arts and Crafts movement", tooltip: "British reform movement championing handcraftsmanship over industrial manufacture in decorative arts, textiles, and design. c. 1880–1920" },
  { name: "Tonalism", tooltip: "American landscape painting using muted tones, softened forms, and atmospheric mistiness for poetic mood. c. 1880–1920" },
  { name: "Symbolism", tooltip: "Art conveying ideas and emotions through symbolic imagery, dreamlike scenes, and mystical, spiritual themes. c. 1880–1910" },
  { name: "Russian Symbolism", tooltip: "Russian literary and visual arts movement using myth, mysticism, and poetic imagery to evoke spiritual inner realities. c. 1890–1910" },
  { name: "Aesthetic movement", tooltip: "British and American movement championing 'art for art's sake' — beauty as its own justification, independent of moral purpose. c. 1860–1900" },
  { name: "Post-Impressionism", tooltip: "Diverse directions beyond Impressionism — including Cézanne's structure, Seurat's dots, Van Gogh's emotion, and Gauguin's flat color. c. 1886–1905" },
  { name: "Les Nabis", tooltip: "French group of Post-Impressionist painters using flat color, decorative patterns, and spiritual symbolism. c. 1888–1900" },
  { name: "Cloisonnism", tooltip: "Post-Impressionist technique using bold, flat areas of color separated by dark outlines, inspired by cloisonné enamel. c. 1888–1894" },
  { name: "Synthetism", tooltip: "Gauguin's approach of synthesizing the artist's observation, emotion, and aesthetics into simplified, symbolic color forms. c. 1888–1894" },
  { name: "Neo-impressionism", tooltip: "Extension of Impressionism applying scientific color theory through systematic techniques like Pointillism and Divisionism. c. 1886–1906" },
  { name: "Pointillism", tooltip: "Painting technique using tiny distinct dots of pure color that optically blend when viewed from a distance. c. 1886–1906" },
  { name: "Divisionism", tooltip: "Neo-Impressionist technique placing adjacent strokes of contrasting color, relying on optical mixture rather than pigment mixing. c. 1886–1910" },
  { name: "Art Nouveau", tooltip: "Organic, curvilinear decorative style inspired by natural forms. Applied to architecture, furniture, glass, and graphic arts. c. 1890–1910" },
  { name: "Vienna Secession", tooltip: "Austrian art movement breaking from academic tradition. Founded by Klimt, featuring geometric decoration and the Ver Sacrum journal. c. 1897–1905" },
  { name: "Mir iskusstva", tooltip: "Russian 'World of Art' group promoting aesthetic refinement, Western European influences, and theatrical design. c. 1898–1927" },
  { name: "Jugendstil", tooltip: "German and Central European version of Art Nouveau with organic forms, whiplash curves, and nature-inspired ornamentation. c. 1896–1910" },
  { name: "Modernisme", tooltip: "Catalan artistic movement centered in Barcelona, blending Art Nouveau with Mediterranean culture. Gaudí's architecture is iconic. c. 1888–1911" },
  { name: "Russian avant-garde", tooltip: "Radical Russian art experiments in Cubism, Futurism, Suprematism, and Constructivism that reshaped 20th-century visual culture. c. 1890–1930" },
  { name: "Art à la Rue", tooltip: "Movement to bring art into public streets through murals, street furniture, and applied arts, promoting art accessibility. c. 1890–1910" },
  { name: "Young Poland", tooltip: "Polish modernist movement in literature, music, and visual arts, embracing Symbolism, Art Nouveau, and national identity. c. 1890–1918" },
  { name: "Hagenbund", tooltip: "Viennese progressive artists' association exhibiting Impressionist, Expressionist, and early modern works alongside the Secession. c. 1900–1938" },
  { name: "Fauvism", tooltip: "Radical use of wild, non-naturalistic color and simplified forms. 'Les Fauves' (wild beasts) shocked Paris salons. c. 1904–1908" },
  { name: "Expressionism", tooltip: "Distortion of reality to convey emotional experience through vivid color, aggressive brushwork, and psychological intensity. c. 1905–1925" },
  { name: "Die Brücke", tooltip: "German Expressionist group ('The Bridge') using raw color, angular forms, and woodcut techniques to convey modern alienation. c. 1905–1913" },
  { name: "Der Blaue Reiter", tooltip: "Munich-based Expressionist group ('The Blue Rider'). Kandinsky, Marc, and others explored spiritual color and abstract form. c. 1911–1914" },
  { name: "Flemish Expressionism", tooltip: "Belgian Expressionist movement with vivid color, social themes, and raw emotion, centered around the Latem School. c. 1905–1930" },
  { name: "Bloomsbury Group", tooltip: "British intellectual circle whose art featured Post-Impressionist-influenced painting and decorative arts (Bell, Grant). c. 1905–1930" },
  { name: "Cubism", tooltip: "Revolutionary style fracturing objects into geometric planes, showing multiple viewpoints simultaneously. Founded by Picasso and Braque. c. 1907–1922" },
  { name: "Jack of Diamonds", tooltip: "Russian avant-garde group blending French Post-Impressionism and Cubism with native Russian folk traditions. c. 1910–1917" },
  { name: "Orphism", tooltip: "Delaunay's lyrical offshoot of Cubism using pure, prismatic color and circular forms to create visual rhythm. c. 1912–1913" },
  { name: "Purism", tooltip: "Post-Cubist movement by Le Corbusier and Ozenfant, advocating precise, machine-age aesthetics and geometric clarity. c. 1918–1925" },
  { name: "Ashcan School", tooltip: "American realist group painting gritty, everyday urban life in New York City with bold, dark-toned compositions. c. 1900–1915" },
  { name: "Art Deco", tooltip: "Elegant decorative style combining geometric forms, rich materials, lavish ornamentation, and machine-age streamlining. c. 1920–1940" },
  { name: "Futurism", tooltip: "Italian movement celebrating speed, technology, machinery, and dynamism through fragmented, kinetic visual forms. c. 1909–1944" },
  { name: "Russian Futurism", tooltip: "Russian literary and visual art movement merging Cubism with Futurism's energy. Included Mayakovsky and Malevich. c. 1910–1920" },
  { name: "Cubo-Futurism", tooltip: "Russian fusion of Cubist structure and Futurist dynamism, moving toward total geometric abstraction. c. 1912–1916" },
  { name: "Rayonism", tooltip: "Russian abstract movement by Larionov and Goncharova, depicting intersecting rays of reflected light as dynamic energy. c. 1911–1914" },
  { name: "Synchromism", tooltip: "American color-based abstract art, paralleling Orphism. Morgan Russell and Stanton Macdonald-Wright used pure spectral harmonies. c. 1912–1920" },
  { name: "Universal Flowering", tooltip: "Phase of Pavel Filonov's Analytical Art, depicting organic growth and cosmic processes through dense, cell-like forms. c. 1912–1941" },
  { name: "Vorticism", tooltip: "British avant-garde movement led by Wyndham Lewis. Bold, angular, machine-inspired abstract compositions. c. 1914–1915" },
  { name: "Biomorphism", tooltip: "Abstract art using organic, rounded forms suggesting living organisms. Influenced by natural shapes and biological structures. c. 1930s–1950s" },
  { name: "Suprematism", tooltip: "Malevich's pure geometric abstraction — basic shapes in limited colors, floating free of any representational reference. c. 1913–1935" },
  { name: "UNOVIS", tooltip: "Malevich's Suprematist collective ('Affirmers of the New Art') at the Vitebsk art school, advancing radical abstraction. c. 1919–1922" },
  { name: "Dada", tooltip: "Anti-art movement rejecting logic and convention through absurdity, chance, collage, and provocative performances. c. 1916–1924" },
  { name: "Proletkult", tooltip: "Soviet cultural movement promoting proletarian art created by and for workers, independent of bourgeois traditions. c. 1917–1925" },
  { name: "Productijism", tooltip: "Soviet-era movement merging art with industrial design, advocating that artists should produce socially useful functional objects. c. 1921–1930s" },
  { name: "De Stijl (Neoplasticism)", tooltip: "Dutch movement using only primary colors, black, white, and straight lines in purely geometric, non-representational compositions. c. 1917–1931" },
  { name: "Pittura Metafisica", tooltip: "De Chirico and Morandi's 'Metaphysical Painting' — eerie stillness, enigmatic objects, and unsettling architectural spaces. c. 1911–1920" },
  { name: "Arbeitsrat für Kunst", tooltip: "German 'Workers' Council for Art.' Radical Berlin group seeking to unite art, architecture, and crafts for social renewal. c. 1918–1921" },
  { name: "Bauhaus", tooltip: "Influential German school unifying art, craft, and technology. Clean geometry, functional design, and interdisciplinary education. c. 1919–1933" },
  { name: "Constructivism", tooltip: "Russian movement applying abstract geometric art to architecture, design, and politics as a tool for social transformation. c. 1914–1930s" },
  { name: "Vkhutemas", tooltip: "Soviet state art and technical school ('Higher Art and Technical Studios'), training students in Constructivist design principles. c. 1920–1930" },
  { name: "Precisionism", tooltip: "American style depicting industrial and architectural subjects with crisp, geometric simplification and sharp-edged clarity. c. 1918–1941" },
  { name: "Surrealism", tooltip: "Art exploring the unconscious, dreams, and irrational imagery through automatism and symbolic, hallucinatory scenes. c. 1924–1966" },
  { name: "Acéphale", tooltip: "French secret society and journal founded by Georges Bataille, blending Surrealist-influenced philosophy with Nietzschean thought. c. 1936–1939" },
  { name: "Lettrism", tooltip: "French avant-garde movement by Isidore Isou, focusing on letters and signs as primary artistic material in visual poetry. c. 1945–1960s" },
  { name: "Les Automatistes", tooltip: "Montreal group of painters practicing automatism — spontaneous, non-representational painting influenced by Surrealism. c. 1946–1954" },
  { name: "Devetsil", tooltip: "Czech avant-garde group blending Constructivism, Poetism, and Surrealism in art, design, architecture, and literature. c. 1920–1931" },
  { name: "Group of Seven", tooltip: "Canadian painters who captured the rugged beauty of the Ontario and Canadian wilderness in bold, expressive landscapes. c. 1920–1933" },
  { name: "Harlem Renaissance", tooltip: "African-American cultural movement celebrating Black identity through art, literature, and music. Centered in Harlem, New York. c. 1918–1937" },
  { name: "American scene painting", tooltip: "Broad 1930s American movement depicting everyday life. Includes Regionalists (rural) and Social Realists (urban). c. 1925–1945" },
  { name: "New Objectivity", tooltip: "German post-Expressionist movement ('Neue Sachlichkeit') of coolly detached, satirical, and socially critical realism. c. 1919–1933" },
  { name: "Grupo Montparnasse", tooltip: "Chilean art group who studied in Paris and brought French modernism — Cubism, Post-Impressionism — to Chile. c. 1923–1930s" },
  { name: "Northwest School", tooltip: "Pacific Northwest American painters drawing on Asian aesthetics and regional nature for contemplative, symbolic art. c. 1930s–1950s" },
  { name: "Social realism", tooltip: "Art depicting working-class conditions and social injustice with empathy and political purpose. Distinct from Soviet Socialist Realism. c. 1920s–1960s" },
  { name: "Socialist realism", tooltip: "Official Soviet art doctrine glorifying the worker, the state, and communist ideals through heroic, idealized imagery. c. 1932–1991" },
  { name: "Leningrad School of Painting", tooltip: "Soviet-era representational painters who maintained realist tradition while subtly expanding its boundaries within Socialist Realism. c. 1930s–1990" },
  { name: "Socrealism", tooltip: "Shortened name for Socialist Realism as practiced across Soviet-aligned nations. Heroic figures, optimistic narratives, and state ideals. c. 1932–1991" },
  { name: "Abstraction-Création", tooltip: "Paris-based international group promoting non-figurative abstract art, from geometric to biomorphic approaches. c. 1931–1936" },
  { name: "Allianz", tooltip: "Swiss group of abstract and concrete artists, including Max Bill and Richard Paul Lohse. c. 1937–1950s" },
  { name: "Abstract Expressionism", tooltip: "Post-war American movement of large-scale, emotionally intense abstraction. Action painting and Color Field sub-movements. c. 1943–1965" },
  { name: "Action painting", tooltip: "Spontaneous, gestural painting technique — dripping, splashing, and physical interaction with the canvas (Pollock, de Kooning). c. 1947–1960" },
  { name: "Tachisme", tooltip: "European counterpart to Action Painting. Intuitive blots, stains, and spontaneous gesture in abstract composition. c. 1940s–1960" },
  { name: "Color field painting", tooltip: "Large expanses of flat, solid color to evoke emotional and contemplative responses. Associated with Rothko and Frankenthaler. c. 1950–1970" },
  { name: "Lyrical Abstraction", tooltip: "Emotionally expressive, gestural abstraction emphasizing personal spontaneity and flowing chromatic compositions. c. 1945–1960s" },
  { name: "COBRA", tooltip: "European avant-garde group (Copenhagen, Brussels, Amsterdam) combining childlike spontaneity, folk art, and Expressionist energy. c. 1948–1951" },
  { name: "Abstract Imagists", tooltip: "Painters blending abstract color fields with faint figurative or landscape suggestions, bridging abstraction and representation. c. 1950s–1960s" },
  { name: "Art informel", tooltip: "European post-war abstraction rejecting geometric structure for spontaneous, formless, gesture-driven painting. c. 1945–1960s" },
  { name: "Contemporary art", tooltip: "Art from the late 20th century to present. Diverse practices including installation, digital, conceptual, and socially engaged work. c. 1970–present" },
  { name: "Vienna School of Fantastic Realism", tooltip: "Post-war Austrian painters combining Old Master techniques with Surrealist dreamlike content and symbolic imagery. c. 1946–1960s" },
  { name: "Neo-Dada", tooltip: "1950s–60s revival of Dada's irreverence through found objects, assemblage, and blurring of art and everyday life (Rauschenberg, Johns). c. 1953–1965" },
  { name: "International Typographic Style", tooltip: "Swiss Design. Clean grids, sans-serif typography, objective photography, and systematic visual order. c. 1950s–1970s" },
  { name: "Soviet Nonconformist Art", tooltip: "Unofficial Soviet art defying Socialist Realism, including abstract, conceptual, and ironic works created underground. c. 1953–1986" },
  { name: "Painters Eleven", tooltip: "Toronto-based abstract painters who introduced Abstract Expressionism to Canada. Known for gestural color abstraction. c. 1953–1960" },
  { name: "Pop Art", tooltip: "Art appropriating imagery from mass culture — advertising, comics, consumer products — blurring high and low culture. c. 1955–1970" },
  { name: "Woodlands School", tooltip: "Canadian Indigenous art style originating with Norval Morrisseau. Thick outlines, vibrant color, and Anishinaabe spiritual imagery. c. 1960s–present" },
  { name: "Situationism", tooltip: "French political-artistic movement critiquing capitalist spectacle through détournement, psychogeography, and cultural subversion. c. 1957–1972" },
  { name: "New realism", tooltip: "European movement ('Nouveau Réalisme') assembling real-world objects and detritus into art, paralleling Pop Art. c. 1960–1963" },
  { name: "Magic realism", tooltip: "Painting style rendering fantastical or enigmatic subjects with photographic precision, creating dreamlike verisimilitude. c. 1920s–1960s" },
  { name: "Minimalism", tooltip: "Art reduced to fundamental geometric forms, industrial materials, and repetitive structures, eliminating personal expression. c. 1960–1975" },
  { name: "Hard-edge painting", tooltip: "Geometric abstraction with crisp, sharply defined boundaries between flat color areas, emphasizing clean form. c. 1958–1970" },
  { name: "Fluxus", tooltip: "International anti-art network emphasizing process, intermedia, humor, and blurring the boundary between art and life. c. 1961–1978" },
  { name: "Happening", tooltip: "Theatrical, participatory events combining visual art, performance, and audience interaction as the art itself. c. 1957–1970" },
  { name: "Video art", tooltip: "Art using video technology as a medium, from single-channel to multi-screen installations exploring time-based imagery. c. 1963–present" },
  { name: "Psychedelic art", tooltip: "Art inspired by altered states of consciousness. Vivid, swirling color, fractal patterns, and distorted, kaleidoscopic forms. c. 1960s–1970s" },
  { name: "Conceptual art", tooltip: "Art in which the idea or concept takes priority over traditional aesthetic and material execution. c. 1966–1978" },
  { name: "Graffiti", tooltip: "Art created in public spaces, from tag lettering to elaborate murals. Subcultural origins in 1970s New York City. c. 1970s–present" },
  { name: "Junk art", tooltip: "Art assembled from discarded materials, refuse, and found objects, transforming waste into expressive sculptural forms. c. 1950s–1970s" },
  { name: "Performance art", tooltip: "Live, time-based art using the artist's body as medium. Often interdisciplinary, ephemeral, and site-specific. c. 1960s–present" },
  { name: "Op Art", tooltip: "Art creating optical illusions of movement, vibration, and depth through precise geometric patterns and color contrast. c. 1964–1970" },
  { name: "Post-painterly abstraction", tooltip: "Reaction against Abstract Expressionist gesture. Open, stained color fields, hard edges, and impersonal surfaces. c. 1964–1970s" },
  { name: "Process art", tooltip: "Art emphasizing the process of creation over finished product. Natural materials and entropy as artistic elements. c. 1966–1970s" },
  { name: "Arte Povera", tooltip: "Italian movement using 'poor' or everyday materials — soil, rags, twigs — to challenge commercialization of art. c. 1967–1972" },
  { name: "Art and Language", tooltip: "British Conceptual art group using text, theory, and philosophical inquiry as the primary artistic medium. c. 1968–present" },
  { name: "Photorealism", tooltip: "Painting and drawing replicating photographs with extreme precision. Reflects on perception, reproduction, and visual truth. c. 1968–present" },
  { name: "Land art", tooltip: "Art made directly in landscapes using natural materials — earth, rocks, water — often at monumental scale. c. 1968–present" },
  { name: "Post-minimalism", tooltip: "Art expanding Minimalism's vocabulary through organic forms, soft materials, process, and body-related content. c. 1968–1980s" },
  { name: "Postmodern art", tooltip: "Art questioning modernist certainties through irony, pastiche, appropriation, plurality, and the collapse of high/low boundaries. c. 1970s–present" },
  { name: "Deconstructivism", tooltip: "Architecture and art fragmenting forms, warping geometry, and disrupting predictable structures. Associated with Gehry and Hadid. c. 1980s–present" },
  { name: "Metarealism", tooltip: "Russian artistic movement combining metaphysical imagery with heightened realism for layered, symbolic meaning. c. 1979–present" },
  { name: "Sots Art", tooltip: "Soviet-era art parodying Socialist Realism and consumer culture with irony, blending Pop Art strategies with Soviet imagery. c. 1972–1990s" },
  { name: "Installation art", tooltip: "Three-dimensional works transforming entire spaces into immersive environments engaging the viewer's full sensory experience. c. 1960s–present" },
  { name: "Mail art", tooltip: "Art created and distributed through the postal system. Democratic, network-based creative exchange beyond galleries. c. 1960s–present" },
  { name: "Maximalism", tooltip: "Reaction to Minimalism. Excess, ornament, pattern layering, eclectic references, and sensory abundance in art and design. c. 1980s–present" },
  { name: "Neo-expressionism", tooltip: "Return to figurative painting with raw, emotional intensity, rough textures, and vivid color after Minimalist and Conceptual dominance. c. 1978–1989" },
  { name: "Neoism", tooltip: "International subcultural movement blending Fluxus, Mail Art, and punk into collaborative, anti-commercial interventions. c. 1979–present" },
  { name: "Figuration Libre", tooltip: "French 'Free Figuration' movement using graffiti-inspired, cartoonish imagery and pop-culture references. c. 1981–1985" },
  { name: "Street art", tooltip: "Visual art created in public spaces — murals, stencils, wheatpaste, and installations — engaging urban environments. c. 1980s–present" },
  { name: "Young British Artists", tooltip: "Provocative group (Hirst, Emin, etc.) using shock, everyday materials, and conceptual strategies in 1990s London. c. 1988–2000s" },
  { name: "Digital art", tooltip: "Art created or presented using digital technology — algorithmic, interactive, generative, and virtual media. c. 1980s–present" },
  { name: "Toyism", tooltip: "Dutch art movement using colorful, masked characters and playful, pseudonymous identities to create optimistic, symbolic art. c. 1990–present" },
  { name: "Massurrealism", tooltip: "Blend of mass media imagery with Surrealist techniques, exploring dream-logic within the hyperconnected media age. c. 1992–present" },
  { name: "Stuckism", tooltip: "British international movement advocating figurative painting with sincerity and emotion as opposed to conceptual art. c. 1999–present" },
  { name: "Remodernism", tooltip: "Movement calling for a return to spirituality, authenticity, and craft in art, opposing what it sees as postmodern irony. c. 2000–present" },
  { name: "Excessivism", tooltip: "Art movement embracing visual and conceptual overload — complexity, density, and layered meaning as aesthetic virtues. c. 2015–present" },
  { name: "African art", tooltip: "Diverse artistic traditions across Africa. Includes masks, sculpture, textiles, body art, and contemporary practices spanning millennia." },
  { name: "Indigenous Australian art", tooltip: "Oldest continuous art tradition in the world. Dot painting, bark painting, rock art, and contemporary expressions. c. 65,000 years ago – present" },
  { name: "Art of Ancient Egypt", tooltip: "Highly stylized, hieratic art serving religious and funerary purposes. Flat perspective, symbolic color, and monumental scale. c. 3100–30 BCE" },
  { name: "Asian art", tooltip: "Vast traditions spanning Chinese, Japanese, Korean, Indian, and Southeast Asian painting, calligraphy, ceramics, and sculpture." },
  { name: "Buddhist art", tooltip: "Art depicting Buddha, bodhisattvas, and Buddhist teachings through sculpture, painting, mandalas, and temple architecture. c. 1st century BCE – present" },
  { name: "Confucian art", tooltip: "Art reflecting Confucian values — filial piety, scholarly cultivation, moral virtue — in Chinese painting, calligraphy, and portraiture." },
  { name: "Coptic art", tooltip: "Art of Egypt's Christian community. Textiles, manuscript illumination, frescoes, and icons blending Egyptian, Greek, and Christian motifs. c. 300–1300" },
  { name: "Hindu art", tooltip: "Art depicting Hindu deities, narratives, and philosophy. Temple sculpture, painting, bronze casting, and architectural ornamentation." },
  { name: "Indian art", tooltip: "Art from the Indian subcontinent spanning millennia — Mughal miniatures, temple sculpture, textiles, and contemporary practice." },
  { name: "Islamic art", tooltip: "Art emphasizing geometric patterns, arabesques, calligraphy, and non-figurative decoration across architecture and decorative arts. c. 7th century – present" },
  { name: "Naive Art", tooltip: "Art by self-taught artists with childlike simplicity, flat perspective, vivid color, and direct, unschooled expression." },
  { name: "Pre-Columbian art", tooltip: "Art of the Americas before European contact — Maya, Aztec, Inca, Olmec — in stone, ceramic, gold, and textile. c. 2000 BCE – 1500 CE" },
  { name: "Pre-historic art", tooltip: "Earliest known human art including cave paintings, carved figurines, and petroglyphs. c. 40,000 – 4,000 BCE" }
];
