export const ART_STYLES = [
  "Classical art",
  "Minoan art",
  "Aegean art",
  "Ancient Greek art",
  "Roman art",
  "Medieval art",
  "Early Christian",
  "Migration Period",
  "Anglo-Saxon",
  "Visigothic",
  "Pre-Romanesque",
  "Insular",
  "Viking",
  "Byzantine",
  "Merovingian",
  "Carolingian",
  "Ottonian",
  "Romanesque",
  "Norman-Sicilian",
  "Gothic",
  "International Gothic",
  "Renaissance",
  "Italian Renaissance",
  "Renaissance Classicism",
  "Early Netherlandish painting",
  "Early Cretan School",
  "Mannerism and Late Renaissance",
  "Baroque",
  "Dutch Golden Age painting",
  "Flemish Baroque painting",
  "Caravaggisti",
  "Rococo",
  "Neoclassicism",
  "Later Cretan School",
  "Heptanese School",
  "Romanticism",
  "Nazarene movement",
  "The Ancients",
  "Purismo",
  "Düsseldorf school",
  "Hudson River School",
  "Luminism",
  "Modern Greek art",
  "Norwich school",
  "Biedermeier",
  "Academic art",
  "Realism",
  "Barbizon school",
  "Peredvizhniki",
  "Abramtsevo Colony",
  "Hague School",
  "American Barbizon School",
  "Spanish Eclecticism",
  "Macchiaioli",
  "Pre-Raphaelite Brotherhood",
  "Modern art",
  "Impressionism",
  "American Impressionism",
  "Cos Cob Art Colony",
  "Heidelberg School",
  "Arts and Crafts movement",
  "Tonalism",
  "Symbolism",
  "Russian Symbolism",
  "Aesthetic movement",
  "Post-Impressionism",
  "Les Nabis",
  "Cloisonnism",
  "Synthetism",
  "Neo-impressionism",
  "Pointillism",
  "Divisionism",
  "Art Nouveau",
  "Vienna Secession",
  "Mir iskusstva",
  "Jugendstil",
  "Modernisme",
  "Russian avant-garde",
  "Art à la Rue",
  "Young Poland",
  "Hagenbund",
  "Fauvism",
  "Expressionism",
  "Die Brücke",
  "Der Blaue Reiter",
  "Flemish Expressionism",
  "Bloomsbury Group",
  "Cubism",
  "Jack of Diamonds",
  "Orphism",
  "Purism",
  "Ashcan School",
  "Art Deco",
  "Futurism",
  "Russian Futurism",
  "Cubo-Futurism",
  "Rayonism",
  "Synchromism",
  "Universal Flowering",
  "Vorticism",
  "Biomorphism",
  "Suprematism",
  "UNOVIS",
  "Dada",
  "Proletkult",
  "Productijism",
  "De Stijl (Neoplasticism)",
  "Pittura Metafisica",
  "Arbeitsrat für Kunst",
  "Bauhaus",
  "Constructivism",
  "Vkhutemas",
  "Precisionism",
  "Surrealism",
  "Acéphale",
  "Lettrism",
  "Les Automatistes",
  "Devetsil",
  "Group of Seven",
  "Harlem Renaissance",
  "American scene painting",
  "New Objectivity",
  "Grupo Montparnasse",
  "Northwest School",
  "Social realism",
  "Socialist realism",
  "Leningrad School of Painting",
  "Socrealism",
  "Abstraction-Création",
  "Allianz",
  "Abstract Expressionism",
  "Action painting",
  "Tachisme",
  "Color field painting",
  "Lyrical Abstraction",
  "COBRA",
  "Abstract Imagists",
  "Art informel",
  "Contemporary art",
  "Vienna School of Fantastic Realism",
  "Neo-Dada",
  "International Typographic Style",
  "Soviet Nonconformist Art",
  "Painters Eleven",
  "Pop Art",
  "Woodlands School",
  "Situationism",
  "New realism",
  "Magic realism",
  "Minimalism",
  "Hard-edge painting",
  "Fluxus",
  "Happening",
  "Video art",
  "Psychedelic art",
  "Conceptual art",
  "Graffiti",
  "Junk art",
  "Performance art",
  "Op Art",
  "Post-painterly abstraction",
  "Process art",
  "Arte Povera",
  "Art and Language",
  "Photorealism",
  "Land art",
  "Post-minimalism",
  "Postmodern art",
  "Deconstructivism",
  "Metarealism",
  "Sots Art",
  "Installation art",
  "Mail art",
  "Maximalism",
  "Neo-expressionism",
  "Neoism",
  "Figuration Libre",
  "Street art",
  "Young British Artists",
  "Digital art",
  "Toyism",
  "Massurrealism",
  "Stuckism",
  "Remodernism",
  "Excessivism",
  "African art",
  "Indigenous Australian art",
  "Art of Ancient Egypt",
  "Asian art",
  "Buddhist art",
  "Confucian art",
  "Coptic art",
  "Hindu art",
  "Indian art",
  "Islamic art",
  "Naive Art",
  "Pre-Columbian art",
  "Pre-historic art"
];
