/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

import React, { useEffect, useRef } from 'react';
import { GeneratedSvg } from '../types';

interface SvgPreviewProps {
  data: GeneratedSvg | null;
}

export const SvgPreview: React.FC<SvgPreviewProps> = ({ data }) => {
  const [copied, setCopied] = React.useState(false);
  const containerRef = useRef<HTMLDivElement>(null);

  // Reset copied state when data changes
  useEffect(() => {
    setCopied(false);
  }, [data]);

  if (!data) return null;

  const handleDownload = () => {
    const blob = new Blob([data.content], { type: 'image/svg+xml' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `vectorcraft-${data.id}.svg`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleCopyCode = () => {
    navigator.clipboard.writeText(data.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="w-full max-w-4xl mx-auto mt-12 px-4 animate-in fade-in slide-in-from-bottom-8 duration-700">
      <div className="bg-base-900 border border-white/10 rounded-2xl overflow-hidden shadow-2xl">
        {/* Toolbar */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-white/10 bg-base-800/50">
          <h3 className="text-sm font-medium text-base-300 truncate max-w-[150px] sm:max-w-xs">
            Result: <span className="text-base-500">"{data.prompt}"</span>
          </h3>
          <div className="flex gap-2">
            <button
              onClick={handleCopyCode}
              className="p-2 text-base-400 hover:text-white hover:bg-white/10 rounded-lg transition-colors group relative flex items-center justify-center"
              title="Copy SVG Code"
            >
              {copied ? <span className="material-symbols-outlined text-green-400 text-[20px]">check_circle</span> : <span className="material-symbols-outlined text-[20px]">code</span>}
            </button>
            <button
              onClick={handleDownload}
              className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-base-900 bg-white rounded-lg hover:bg-base-200 transition-colors shadow-sm"
            >
              <span className="material-symbols-outlined text-[18px]">download</span>
              <span className="hidden sm:inline">Download</span>
            </button>
          </div>
        </div>

        {/* Canvas Area */}
        <div className="p-8 flex items-center justify-center bg-[#101A28] min-h-[400px]">
           {/* 
             Using dangerouslySetInnerHTML is intentional here as the content is generated by the LLM for the purpose of display.
           */}
          <div 
            ref={containerRef}
            className="w-full max-w-[512px] h-auto transition-all duration-500 transform hover:scale-[1.02] filter drop-shadow-2xl"
            dangerouslySetInnerHTML={{ __html: data.content }} 
          />
        </div>
        
        {/* Metadata Footer */}
        <div className="p-6 bg-base-900 border-t border-white/10 flex flex-col sm:flex-row sm:items-start justify-between gap-6">
          <div className="flex-1">
            <h4 className="text-xs font-bold text-base-500 uppercase tracking-widest mb-2 flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-brand-500"></span>
              Prompt Used
            </h4>
            <p className="text-sm text-base-300 leading-relaxed bg-base-950/50 p-3 rounded-lg border border-white/5">{data.prompt}</p>
          </div>
          <div className="sm:text-right shrink-0">
            <h4 className="text-xs font-bold text-base-500 uppercase tracking-widest mb-2">Generated On</h4>
            <p className="text-sm text-base-400 font-mono bg-base-950/50 p-3 rounded-lg border border-white/5">
              {new Date(data.timestamp).toLocaleDateString()} <span className="text-base-600 mx-1">•</span> {new Date(data.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
